// packages/constants/src/deployment-labels.ts

import {
  DEPLOYMENT_STATUS,
  DEPLOYMENT_ENVIRONMENT,
  DEPLOYMENT_TRIGGER,
} from "./enums";

export const DEPLOYMENT_STATUS_LABELS: Record<DEPLOYMENT_STATUS, string> = {
  [DEPLOYMENT_STATUS.PENDING]: "Pendente",
  [DEPLOYMENT_STATUS.IN_PROGRESS]: "Em Progresso",
  [DEPLOYMENT_STATUS.BUILDING]: "Construindo",
  [DEPLOYMENT_STATUS.TESTING]: "Testando",
  [DEPLOYMENT_STATUS.DEPLOYING]: "Implantando",
  [DEPLOYMENT_STATUS.COMPLETED]: "Concluído",
  [DEPLOYMENT_STATUS.FAILED]: "Falhou",
  [DEPLOYMENT_STATUS.ROLLED_BACK]: "Revertido",
  [DEPLOYMENT_STATUS.CANCELLED]: "Cancelado",
};

export const DEPLOYMENT_ENVIRONMENT_LABELS: Record<DEPLOYMENT_ENVIRONMENT, string> = {
  [DEPLOYMENT_ENVIRONMENT.DEVELOPMENT]: "Desenvolvimento",
  [DEPLOYMENT_ENVIRONMENT.STAGING]: "Homologação",
  [DEPLOYMENT_ENVIRONMENT.PRODUCTION]: "Produção",
};

export const DEPLOYMENT_TRIGGER_LABELS: Record<DEPLOYMENT_TRIGGER, string> = {
  [DEPLOYMENT_TRIGGER.MANUAL]: "Manual",
  [DEPLOYMENT_TRIGGER.AUTO]: "Automático",
  [DEPLOYMENT_TRIGGER.PUSH]: "Push Git",
  [DEPLOYMENT_TRIGGER.PULL_REQUEST]: "Pull Request",
  [DEPLOYMENT_TRIGGER.TAG]: "Tag Git",
  [DEPLOYMENT_TRIGGER.SCHEDULE]: "Agendado",
  [DEPLOYMENT_TRIGGER.WEBHOOK]: "Webhook",
  [DEPLOYMENT_TRIGGER.ROLLBACK]: "Reversão",
  [DEPLOYMENT_TRIGGER.API]: "API",
};
