// packages/constants/src/deployment-sort-orders.ts

import {
  DEPLOYMENT_STATUS,
  DEPLOYMENT_ENVIRONMENT,
} from "./enums";

export const DEPLOYMENT_STATUS_ORDER: Record<DEPLOYMENT_STATUS, number> = {
  [DEPLOYMENT_STATUS.IN_PROGRESS]: 1,
  [DEPLOYMENT_STATUS.PENDING]: 2,
  [DEPLOYMENT_STATUS.BUILDING]: 3,
  [DEPLOYMENT_STATUS.TESTING]: 4,
  [DEPLOYMENT_STATUS.DEPLOYING]: 5,
  [DEPLOYMENT_STATUS.FAILED]: 6,
  [DEPLOYMENT_STATUS.COMPLETED]: 7,
  [DEPLOYMENT_STATUS.CANCELLED]: 8,
  [DEPLOYMENT_STATUS.ROLLED_BACK]: 9,
};

export const DEPLOYMENT_ENVIRONMENT_ORDER: Record<DEPLOYMENT_ENVIRONMENT, number> = {
  [DEPLOYMENT_ENVIRONMENT.PRODUCTION]: 1,
  [DEPLOYMENT_ENVIRONMENT.STAGING]: 2,
  [DEPLOYMENT_ENVIRONMENT.DEVELOPMENT]: 3,
};
