// packages/constants/src/deployment-enums.ts

export enum DEPLOYMENT_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  BUILDING = "BUILDING",
  TESTING = "TESTING",
  DEPLOYING = "DEPLOYING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ROLLED_BACK = "ROLLED_BACK",
  CANCELLED = "CANCELLED",
}

export enum DEPLOYMENT_ENVIRONMENT {
  DEVELOPMENT = "DEVELOPMENT",
  STAGING = "STAGING",
  PRODUCTION = "PRODUCTION",
}

export enum DEPLOYMENT_TRIGGER {
  MANUAL = "MANUAL",
  AUTO = "AUTO",
  PUSH = "PUSH",
  PULL_REQUEST = "PULL_REQUEST",
  TAG = "TAG",
  SCHEDULE = "SCHEDULE",
  WEBHOOK = "WEBHOOK",
  ROLLBACK = "ROLLBACK",
  API = "API",
}

export enum DEPLOYMENT_TYPE {
  FULL = "FULL",
  INCREMENTAL = "INCREMENTAL",
  HOTFIX = "HOTFIX",
  ROLLBACK = "ROLLBACK",
}
