// packages/interfaces/src/enums.ts

export type ORDER_BY_DIRECTION = "asc" | "desc";

// =====================
// Status Enums
// =====================

// =====================
// ABC/XYZ Analysis Categories
// =====================

export enum ABC_CATEGORY {
  A = "A",
  B = "B",
  C = "C",
}

export enum XYZ_CATEGORY {
  X = "X",
  Y = "Y",
  Z = "Z",
}

export enum ORDER_STATUS {
  CREATED = "CREATED",
  PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED",
  FULFILLED = "FULFILLED",
  OVERDUE = "OVERDUE",
  PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED",
  RECEIVED = "RECEIVED",
  CANCELLED = "CANCELLED",
}

export enum PAYMENT_METHOD {
  PIX = "PIX",
  BANK_SLIP = "BANK_SLIP",
  CREDIT_CARD = "CREDIT_CARD",
}

export const BANK_SLIP_DUE_DAYS_OPTIONS = [30, 60, 90, 120] as const;

export enum SECTOR_PRIVILEGES {
  BASIC = "BASIC",
  PRODUCTION = "PRODUCTION",
  MAINTENANCE = "MAINTENANCE",
  WAREHOUSE = "WAREHOUSE",
  ADMIN = "ADMIN",
  HUMAN_RESOURCES = "HUMAN_RESOURCES",
  EXTERNAL = "EXTERNAL",
  DESIGNER = "DESIGNER",
  FINANCIAL = "FINANCIAL",
  LOGISTIC = "LOGISTIC",
  PLOTTING = "PLOTTING",
  COMMERCIAL = "COMMERCIAL",
  PRODUCTION_MANAGER = "PRODUCTION_MANAGER",
  AIRBRUSHING = "AIRBRUSHING",
  ACCOUNTING = "ACCOUNTING",
}

/**
 * TEAM_LEADER is a virtual privilege - not stored in database
 * Determined by: user.sector.privilege === PRODUCTION && user.id === user.sector.leaderId
 * Use isTeamLeader() helper function to check this status
 */
export const TEAM_LEADER = 'TEAM_LEADER' as const;

// The legal KIND of an employment bond (vínculo). Only meaningful for on-folha CLT-family types.
export enum CONTRACT_TYPE {
  EXPERIENCE_PERIOD_1 = "EXPERIENCE_PERIOD_1",
  EXPERIENCE_PERIOD_2 = "EXPERIENCE_PERIOD_2",
  INDETERMINATE = "INDETERMINATE",
  FIXED_TERM = "FIXED_TERM",
  INTERMITTENT = "INTERMITTENT",
  APPRENTICE = "APPRENTICE",
  TEMPORARY = "TEMPORARY",
}

// The LIFECYCLE status (situação) of an employment bond. Orthogonal to CONTRACT_TYPE.
export enum CONTRACT_STATUS {
  ACTIVE = "ACTIVE",
  TERMINATED = "TERMINATED",
}

// Worker CATEGORY — gates payroll/folha inclusion (eSocial S-2200 vs S-2300 split).
export enum EMPLOYEE_TYPE {
  CLT = "CLT",
  INTERN = "INTERN",
  PJ = "PJ",
  AUTONOMOUS = "AUTONOMOUS",
}

export enum REGISTRATION_STATUS {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  UNFIT = "UNFIT",
  ACTIVE_NOT_REGULAR = "ACTIVE_NOT_REGULAR",
  DEREGISTERED = "DEREGISTERED",
}

export const REGISTRATION_STATUS_OPTIONS = [
  { value: "ACTIVE", label: "Ativa" },
  { value: "SUSPENDED", label: "Suspensa" },
  { value: "UNFIT", label: "Inapta" },
  { value: "ACTIVE_NOT_REGULAR", label: "Ativa Não Regular" },
  { value: "DEREGISTERED", label: "Baixada" },
] as const;

// Map for converting old values to new values (for migration)
export const REGISTRATION_STATUS_MIGRATION_MAP = {
  ATIVA: "ACTIVE",
  SUSPENSA: "SUSPENDED",
  INAPTA: "UNFIT",
  ATIVA_NAO_REGULAR: "ACTIVE_NOT_REGULAR",
  BAIXADA: "DEREGISTERED",
} as const;

export const STREET_TYPE_OPTIONS = [
  { value: "STREET", label: "Street" },
  { value: "AVENUE", label: "Avenue" },
  { value: "ALLEY", label: "Alley" },
  { value: "CROSSING", label: "Crossing" },
  { value: "SQUARE", label: "Square" },
  { value: "HIGHWAY", label: "Highway" },
  { value: "ROAD", label: "Road" },
  { value: "WAY", label: "Way" },
  { value: "PLAZA", label: "Plaza" },
  { value: "LANE", label: "Lane" },
  { value: "DEADEND", label: "Deadend" },
  { value: "SMALL_STREET", label: "Small Street" },
  { value: "PATH", label: "Path" },
  { value: "PASSAGE", label: "Passage" },
  { value: "GARDEN", label: "Garden" },
  { value: "BLOCK", label: "Block" },
  { value: "LOT", label: "Lot" },
  { value: "SITE", label: "Site" },
  { value: "PARK", label: "Park" },
  { value: "FARM", label: "Farm" },
  { value: "RANCH", label: "Ranch" },
  { value: "CONDOMINIUM", label: "Condominium" },
  { value: "COMPLEX", label: "Complex" },
  { value: "RESIDENTIAL", label: "Residential" },
  { value: "OTHER", label: "Other" },
] as const;

// Map for converting old values to new values (for migration)
export const STREET_TYPE_MIGRATION_MAP = {
  RUA: "STREET",
  AVENIDA: "AVENUE",
  ALAMEDA: "ALLEY",
  TRAVESSA: "CROSSING",
  PRACA: "SQUARE",
  RODOVIA: "HIGHWAY",
  ESTRADA: "ROAD",
  VIA: "WAY",
  LARGO: "PLAZA",
  VIELA: "LANE",
  BECO: "DEADEND",
  RUELA: "SMALL_STREET",
  CAMINHO: "PATH",
  PASSAGEM: "PASSAGE",
  JARDIM: "GARDEN",
  QUADRA: "BLOCK",
  LOTE: "LOT",
  SITIO: "SITE",
  PARQUE: "PARK",
  FAZENDA: "FARM",
  CHACARA: "RANCH",
  CONDOMINIO: "CONDOMINIUM",
  CONJUNTO: "COMPLEX",
  RESIDENCIAL: "RESIDENTIAL",
  OUTRO: "OTHER",
} as const;

// Worker categories that belong on the CLT payroll (folha).
export const PAYROLL_EMPLOYEE_TYPES = [EMPLOYEE_TYPE.CLT] as const;

// Bonification eligibility is now a STATUS/eligibility predicate, not a modality list.
// eligible = employeeType CLT && status ACTIVE. The former BONIFIABLE_CONTRACT_TYPES
// modality list has been RETIRED (Part A).

export enum TASK_STATUS {
  PREPARATION = "PREPARATION",
  WAITING_PRODUCTION = "WAITING_PRODUCTION",
  IN_PRODUCTION = "IN_PRODUCTION",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum GOAL_METRIC {
  // Production
  TASKS_COMPLETED = "TASKS_COMPLETED",
  TASKS_PER_ACTIVE_USER = "TASKS_PER_ACTIVE_USER",
  PRODUCTION_AVG_PERFORMANCE = "PRODUCTION_AVG_PERFORMANCE",
  // HR
  COLLABORATORS_PER_SECTOR = "COLLABORATORS_PER_SECTOR",
  HR_HIRES_PER_MONTH = "HR_HIRES_PER_MONTH",
  HR_DISMISSALS_PER_MONTH = "HR_DISMISSALS_PER_MONTH",
  HR_TURNOVER_RATE = "HR_TURNOVER_RATE",
  HR_EXPERIENCE_FAILURE_RATE = "HR_EXPERIENCE_FAILURE_RATE",
  HR_ABSENTEEISM_RATE = "HR_ABSENTEEISM_RATE",
  HR_PAYROLL_GROSS = "HR_PAYROLL_GROSS",
  HR_PAYROLL_BONUSES_TOTAL = "HR_PAYROLL_BONUSES_TOTAL",
  // Finance
  INVOICES_PAID = "INVOICES_PAID",
  FINANCE_DSO_DAYS = "FINANCE_DSO_DAYS",
  FINANCE_OVERDUE_AMOUNT = "FINANCE_OVERDUE_AMOUNT",
  FINANCE_COLLECTION_RATE = "FINANCE_COLLECTION_RATE",
  FINANCE_QUOTES_PER_PERIOD = "FINANCE_QUOTES_PER_PERIOD",
  FINANCE_CONVERSION_RATE = "FINANCE_CONVERSION_RATE",
  // Order / inventory
  ORDER_COUNT_PER_PERIOD = "ORDER_COUNT_PER_PERIOD",
  ORDER_TOTAL_VALUE = "ORDER_TOTAL_VALUE",
  INVENTORY_CONSUMPTION_VALUE = "INVENTORY_CONSUMPTION_VALUE",
  INVENTORY_OUTBOUND_VALUE = "INVENTORY_OUTBOUND_VALUE",
}

/** Metrics that scope a goal to a specific sector; others are company-wide. */
export const SECTOR_SCOPED_GOAL_METRICS = [
  GOAL_METRIC.COLLABORATORS_PER_SECTOR,
  GOAL_METRIC.HR_PAYROLL_GROSS,
  GOAL_METRIC.HR_PAYROLL_BONUSES_TOTAL,
  GOAL_METRIC.HR_HIRES_PER_MONTH,
  GOAL_METRIC.HR_DISMISSALS_PER_MONTH,
] as const;

/** Unit of measure for a goal's targetValue — drives formatting in the admin grid and chart axes. */
export enum GOAL_UNIT {
  COUNT = "COUNT",
  DECIMAL = "DECIMAL",
  CURRENCY = "CURRENCY",
  PERCENTAGE = "PERCENTAGE",
  MINUTES = "MINUTES",
  DAYS = "DAYS",
  LITERS = "LITERS",
}

/** Whether reaching the target is a maximize (higher is better) or minimize (lower is better) goal. */
export enum GOAL_DIRECTION {
  MAXIMIZE = "MAXIMIZE",
  MINIMIZE = "MINIMIZE",
}

export enum SERVICE_ORDER_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING_ARTWORK = "WAITING_ARTWORK",
  PAUSED = "PAUSED",
  WAITING_APPROVE = "WAITING_APPROVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum SERVICE_ORDER_TYPE {
  PRODUCTION = "PRODUCTION",
  COMMERCIAL = "COMMERCIAL",
  LOGISTIC = "LOGISTIC",
  ARTWORK = "ARTWORK",
}

/** Fixed display order for service order type groups */
export const SERVICE_ORDER_TYPE_DISPLAY_ORDER: SERVICE_ORDER_TYPE[] = [
  SERVICE_ORDER_TYPE.COMMERCIAL,
  SERVICE_ORDER_TYPE.ARTWORK,
  SERVICE_ORDER_TYPE.PRODUCTION,
  SERVICE_ORDER_TYPE.LOGISTIC,
];

export enum AIRBRUSHING_STATUS {
  PENDING = "PENDING",
  IN_PRODUCTION = "IN_PRODUCTION",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum AIRBRUSHING_PAYMENT_STATUS {
  PENDING = "PENDING",
  PAID = "PAID",
}

// =====================
// Accounting Area — Departamento Pessoal & Medicina do Trabalho
// =====================

export enum SALARY_ADJUSTMENT_TYPE {
  DISSIDIO_CCT = "DISSIDIO_CCT",
  MERIT = "MERIT",
  PROMOTION = "PROMOTION",
  EQUALIZATION = "EQUALIZATION",
  REFRAME = "REFRAME",
  OTHER = "OTHER",
  // System-applied bonus period reajuste (not a user-selectable salary type).
  BONUS = "BONUS",
}

// CLT: rebaixamento unilateral é ilegal (CF art.7º VI + CLT art.468), por isso
// não é ofertado. Os valores abaixo são reaproveitados (sem migração) como os
// movimentos lícitos: DEMOTION=Reversão (art.468 §único), ADJUSTMENT=Readaptação
// (art.461 §4º), CORRECTION=Reenquadramento (plano de cargos).
export enum POSITION_CHANGE_REASON {
  ADMISSION = "ADMISSION",
  PROMOTION = "PROMOTION",
  TRANSFER = "TRANSFER",
  DEMOTION = "DEMOTION",
  ADJUSTMENT = "ADJUSTMENT",
  CORRECTION = "CORRECTION",
}

export enum BENEFIT_KIND {
  TRANSPORT_VOUCHER = "TRANSPORT_VOUCHER",
  MEAL_VOUCHER = "MEAL_VOUCHER",
  FOOD_VOUCHER = "FOOD_VOUCHER",
  HEALTH_PLAN = "HEALTH_PLAN",
  DENTAL_PLAN = "DENTAL_PLAN",
  PHARMACY_AGREEMENT = "PHARMACY_AGREEMENT",
  PARTNERSHIP = "PARTNERSHIP",
  LIFE_INSURANCE = "LIFE_INSURANCE",
  OTHER = "OTHER",
}

export enum BENEFIT_ENROLLMENT_STATUS {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  OPTED_OUT = "OPTED_OUT",
  TERMINATED = "TERMINATED",
}

export enum ADMISSION_STATUS {
  DOCS_PENDING = "DOCS_PENDING",
  MEDICAL_EXAM = "MEDICAL_EXAM",
  CONTRACT = "CONTRACT",
  REGISTRATION = "REGISTRATION",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum ADMISSION_DOCUMENT_TYPE {
  CPF = "CPF",
  RG = "RG",
  CTPS = "CTPS",
  PROOF_OF_RESIDENCE = "PROOF_OF_RESIDENCE",
  VOTER_ID = "VOTER_ID",
  MILITARY_CERTIFICATE = "MILITARY_CERTIFICATE",
  BIRTH_MARRIAGE_CERTIFICATE = "BIRTH_MARRIAGE_CERTIFICATE",
  PHOTO = "PHOTO",
  PIS = "PIS",
  ADMISSION_EXAM = "ADMISSION_EXAM",
  TRANSPORT_VOUCHER_DECLARATION = "TRANSPORT_VOUCHER_DECLARATION",
  FAMILY_SALARY_FORM = "FAMILY_SALARY_FORM",
  EMPLOYMENT_CONTRACT = "EMPLOYMENT_CONTRACT",
  TIME_BANK_AGREEMENT = "TIME_BANK_AGREEMENT",
  LGPD_TERM = "LGPD_TERM",
  DRIVER_LICENSE = "DRIVER_LICENSE",
  OTHER = "OTHER",
}

export enum ADMISSION_DOCUMENT_STATUS {
  PENDING = "PENDING",
  RECEIVED = "RECEIVED",
  SIGNED = "SIGNED",
  WAIVED = "WAIVED",
}

export enum TERMINATION_TYPE {
  WITHOUT_CAUSE = "WITHOUT_CAUSE",
  WITH_CAUSE = "WITH_CAUSE",
  RESIGNATION = "RESIGNATION",
  MUTUAL_AGREEMENT = "MUTUAL_AGREEMENT",
  EXPERIENCE_END = "EXPERIENCE_END",
  EXPERIENCE_EARLY_EMPLOYER = "EXPERIENCE_EARLY_EMPLOYER",
  EXPERIENCE_EARLY_EMPLOYEE = "EXPERIENCE_EARLY_EMPLOYEE",
  INDIRECT = "INDIRECT",
  DEATH = "DEATH",
  // Art. 480 CLT — rescisão antecipada de contrato a prazo PELO EMPREGADO.
  FIXED_TERM_EARLY_EMPLOYEE = "FIXED_TERM_EARLY_EMPLOYEE",
  // Encerramento de contrato intermitente.
  INTERMITTENT_END = "INTERMITTENT_END",
}

export enum TERMINATION_STATUS {
  INITIATED = "INITIATED",
  NOTICE_PERIOD = "NOTICE_PERIOD",
  DOCUMENTS = "DOCUMENTS",
  MEDICAL_EXAM = "MEDICAL_EXAM",
  CALCULATION = "CALCULATION",
  PAYMENT = "PAYMENT",
  HOMOLOGATION = "HOMOLOGATION",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum NOTICE_TYPE {
  WORKED = "WORKED",
  INDEMNIFIED = "INDEMNIFIED",
  WAIVED = "WAIVED",
}

export enum NOTICE_REDUCTION {
  NONE = "NONE",
  TWO_HOURS_PER_DAY = "TWO_HOURS_PER_DAY",
  SEVEN_DAYS_OFF = "SEVEN_DAYS_OFF",
}

export enum TERMINATION_ITEM_TYPE {
  SALARY_BALANCE = "SALARY_BALANCE",
  NOTICE_INDEMNIFIED = "NOTICE_INDEMNIFIED",
  NOTICE_DISCOUNT = "NOTICE_DISCOUNT",
  THIRTEENTH_PROPORTIONAL = "THIRTEENTH_PROPORTIONAL",
  ACCRUED_VACATION = "ACCRUED_VACATION",
  PROPORTIONAL_VACATION = "PROPORTIONAL_VACATION",
  ART479_INDEMNITY = "ART479_INDEMNITY",
  FGTS_FINE = "FGTS_FINE",
  ART477_FINE = "ART477_FINE",
  INSS_DISCOUNT = "INSS_DISCOUNT",
  IRRF_DISCOUNT = "IRRF_DISCOUNT",
  ADVANCE_DISCOUNT = "ADVANCE_DISCOUNT",
  BENEFIT_DISCOUNT = "BENEFIT_DISCOUNT",
  OTHER_EARNING = "OTHER_EARNING",
  OTHER_DISCOUNT = "OTHER_DISCOUNT",
}

export enum TERMINATION_DOCUMENT_TYPE {
  NOTICE_LETTER = "NOTICE_LETTER",
  WARNING_LETTER = "WARNING_LETTER",
  TRCT = "TRCT",
  TERM_484A = "TERM_484A",
  HOMOLOGATION_TERM = "HOMOLOGATION_TERM",
  FGTS_GUIDE = "FGTS_GUIDE",
  FGTS_STATEMENT = "FGTS_STATEMENT",
  UNEMPLOYMENT_INSURANCE_FORM = "UNEMPLOYMENT_INSURANCE_FORM",
  DISMISSAL_EXAM = "DISMISSAL_EXAM",
  PAYMENT_RECEIPT = "PAYMENT_RECEIPT",
  DOCUMENT_DELIVERY_RECEIPT = "DOCUMENT_DELIVERY_RECEIPT",
  MUTUAL_AGREEMENT_TERM = "MUTUAL_AGREEMENT_TERM",
  OTHER = "OTHER",
}

export enum TERMINATION_DOCUMENT_STATUS {
  PENDING = "PENDING",
  GENERATED = "GENERATED",
  SIGNED = "SIGNED",
  DELIVERED = "DELIVERED",
}

export enum MEDICAL_EXAM_TYPE {
  ADMISSION = "ADMISSION",
  PERIODIC = "PERIODIC",
  RETURN_TO_WORK = "RETURN_TO_WORK",
  RISK_CHANGE = "RISK_CHANGE",
  DISMISSAL = "DISMISSAL",
}

export enum MEDICAL_EXAM_STATUS {
  SCHEDULED = "SCHEDULED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum MEDICAL_EXAM_RESULT {
  PENDING = "PENDING",
  FIT = "FIT",
  FIT_WITH_RESTRICTIONS = "FIT_WITH_RESTRICTIONS",
  UNFIT = "UNFIT",
}

export enum LEAVE_TYPE {
  ILLNESS_UP_TO_15 = "ILLNESS_UP_TO_15",
  ILLNESS_INSS = "ILLNESS_INSS",
  WORK_ACCIDENT = "WORK_ACCIDENT",
  MATERNITY = "MATERNITY",
  PATERNITY = "PATERNITY",
  MARRIAGE = "MARRIAGE",
  BEREAVEMENT = "BEREAVEMENT",
  BLOOD_DONATION = "BLOOD_DONATION",
  MILITARY = "MILITARY",
  COURT_ATTENDANCE = "COURT_ATTENDANCE",
  UNPAID = "UNPAID",
  SUSPENSION = "SUSPENSION",
  OTHER = "OTHER",
}

export enum LEAVE_STATUS {
  SCHEDULED = "SCHEDULED",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum DEPENDENT_RELATIONSHIP {
  CHILD = "CHILD",
  STEPCHILD = "STEPCHILD",
  SPOUSE = "SPOUSE",
  PARTNER = "PARTNER",
  PARENT = "PARENT",
  WARD = "WARD",
  DISABLED_ANY_AGE = "DISABLED_ANY_AGE",
  OTHER = "OTHER",
}

// ============================================================================
// Área Andressa — new enums (Parts B/C/D/E)
// ============================================================================

// Grau de insalubridade (NR-15) → % do adicional sobre o salário-mínimo.
export enum INSALUBRITY_DEGREE {
  NONE = "NONE", // 0%
  MIN = "MIN", // 10%
  MED = "MED", // 20%
  MAX = "MAX", // 40%
}

// Tipo de janela de estabilidade (estabilidade) que bloqueia o desligamento.
export enum STABILITY_TYPE {
  ACCIDENT = "ACCIDENT",
  PREGNANCY = "PREGNANCY",
  UNION = "UNION",
  CIPA = "CIPA",
  OTHER = "OTHER",
}

// Espécie de benefício INSS (afastamento).
export enum INSS_BENEFIT_SPECIES {
  B31 = "B31", // auxílio-doença previdenciário
  B91 = "B91", // auxílio-doença acidentário (gera estabilidade)
  B32 = "B32", // aposentadoria por invalidez previdenciária
  B92 = "B92", // aposentadoria por invalidez acidentária
  B80 = "B80", // salário-maternidade
  B36 = "B36", // auxílio-acidente
  OTHER = "OTHER",
}

// Status de um período de férias.
// "Em gozo" não é mais um status persistido — é derivado das datas
// (ver isVacationInProgress).
export enum VACATION_STATUS {
  SCHEDULED = "SCHEDULED",
  PAID = "PAID",
  EXPIRED = "EXPIRED",
}

// Tipo de abrangência das férias coletivas.
export enum VACATION_GROUP_TYPE {
  ALL = "ALL",
  SECTOR = "SECTOR",
  POSITION = "POSITION",
}

// Status do 13º salário.
export enum THIRTEENTH_STATUS {
  OPEN = "OPEN",
  FIRST_PAID = "FIRST_PAID",
  SECOND_PAID = "SECOND_PAID",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
}

// Tipo de CAT (Comunicação de Acidente de Trabalho).
export enum WORK_ACCIDENT_REPORT_TYPE {
  INITIAL = "INITIAL",
  REOPENING = "REOPENING",
  DEATH = "DEATH",
}

// Tipos de lançamento da folha (descontos e proventos). Espelha o enum Prisma
// PayrollDiscountType (que carrega ambos os lados do holerite).
export enum PAYROLL_DISCOUNT_TYPE {
  INSS = "INSS",
  IRRF = "IRRF",
  FGTS = "FGTS",
  ABSENCE = "ABSENCE",
  PARTIAL_ABSENCE = "PARTIAL_ABSENCE",
  DSR_ABSENCE = "DSR_ABSENCE",
  LATE_ARRIVAL = "LATE_ARRIVAL",
  SICK_LEAVE = "SICK_LEAVE",
  UNION = "UNION",
  ALIMONY = "ALIMONY",
  GARNISHMENT = "GARNISHMENT",
  HEALTH_INSURANCE = "HEALTH_INSURANCE",
  DENTAL_INSURANCE = "DENTAL_INSURANCE",
  MEAL_VOUCHER = "MEAL_VOUCHER",
  TRANSPORT_VOUCHER = "TRANSPORT_VOUCHER",
  LOAN = "LOAN",
  ADVANCE = "ADVANCE",
  AUTHORIZED_DISCOUNT = "AUTHORIZED_DISCOUNT",
  CUSTOM = "CUSTOM",
  // Proventos (earnings)
  FAMILY_ALLOWANCE = "FAMILY_ALLOWANCE",
  INSALUBRIDADE = "INSALUBRIDADE",
  PERICULOSIDADE = "PERICULOSIDADE",
  HABITUAL_GRATIFICATION = "HABITUAL_GRATIFICATION",
}

export enum ORDER_PAYMENT_STATUS {
  PENDING = "PENDING",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  PARTIALLY_PAID = "PARTIALLY_PAID",
  PAID = "PAID",
}

export enum ORDER_INSTALLMENT_STATUS {
  PENDING = "PENDING",
  PARTIALLY_PAID = "PARTIALLY_PAID",
  PAID = "PAID",
  OVERDUE = "OVERDUE",
  CANCELLED = "CANCELLED",
}

export enum LAYOUT_STATUS {
  DRAFT = "DRAFT",
  APPROVED = "APPROVED",
  REPROVED = "REPROVED",
}

export enum CUT_TYPE {
  VINYL = "VINYL",
  STENCIL = "STENCIL",
}

export enum CUT_STATUS {
  PENDING = "PENDING",
  CUTTING = "CUTTING",
  COMPLETED = "COMPLETED",
}

export enum CUT_ORIGIN {
  PLAN = "PLAN",
  REQUEST = "REQUEST",
}

export enum CUT_REQUEST_REASON {
  WRONG_APPLY = "WRONG_APPLY",
  LOST = "LOST",
  WRONG = "WRONG",
}


export enum PPE_REQUEST_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}

export enum PPE_DELIVERY_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  DELIVERED = "DELIVERED",
  WAITING_SIGNATURE = "WAITING_SIGNATURE",
  COMPLETED = "COMPLETED",
  SIGNATURE_REJECTED = "SIGNATURE_REJECTED",
  REPROVED = "REPROVED",
  CANCELLED = "CANCELLED",
}

export enum ASSIGNMENT_TYPE {
  ALL = "ALL",
  ALL_EXCEPT = "ALL_EXCEPT",
  SPECIFIC = "SPECIFIC",
}

export enum BORROW_STATUS {
  ACTIVE = "ACTIVE",
  RETURNED = "RETURNED",
  LOST = "LOST",
}

export enum EXTERNAL_OPERATION_STATUS {
  // Common statuses
  PENDING = "PENDING",
  CANCELLED = "CANCELLED",
  // Returnable specific
  PARTIALLY_RETURNED = "PARTIALLY_RETURNED",
  FULLY_RETURNED = "FULLY_RETURNED",
  // Chargeable specific
  CHARGED = "CHARGED",
  LIQUIDATED = "LIQUIDATED",
  // Complimentary specific
  DELIVERED = "DELIVERED",
}

export enum EXTERNAL_OPERATION_TYPE {
  RETURNABLE = "RETURNABLE",
  CHARGEABLE = "CHARGEABLE",
  COMPLIMENTARY = "COMPLIMENTARY",
}

// =====================
// Analytics & Trends
// =====================

export enum TREND_DIRECTION {
  UP = "UP",
  DOWN = "DOWN",
  STABLE = "STABLE",
}

export enum TREND_TYPE {
  POSITIVE = "POSITIVE",
  NEGATIVE = "NEGATIVE",
  NEUTRAL = "NEUTRAL",
  VOLATILE = "VOLATILE",
  SEASONAL = "SEASONAL",
}

export enum PERIOD_TYPE {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  YEARLY = "YEARLY",
}

// =====================
// Chart Types
// =====================

export enum CHART_TYPE {
  PIE = "PIE",
  DONUT = "DONUT",
  AREA = "AREA",
  BAR = "BAR",
  LINE = "LINE",
  STACKED = "STACKED",
}


// =====================
// Statistics & Analytics Enums
// =====================

export enum STATISTICS_GROUP_BY {
  SECTOR = "SECTOR",
  USER = "USER",
  CATEGORY = "CATEGORY",
  BRAND = "BRAND",
  SUPPLIER = "SUPPLIER",
  ITEM = "ITEM",
  DATE = "DATE",
  ACTIVITY_REASON = "ACTIVITY_REASON",
  ACTIVITY_OPERATION = "ACTIVITY_OPERATION",
}

export enum STATISTICS_METRIC {
  QUANTITY = "QUANTITY",
  TOTAL_PRICE = "TOTAL_PRICE",
  UNIT_PRICE = "UNIT_PRICE",
  COUNT = "COUNT",
  FREQUENCY = "FREQUENCY",
  PERCENTAGE = "PERCENTAGE",
  AVERAGE = "AVERAGE",
  SUM = "SUM",
  MIN = "MIN",
  MAX = "MAX",
}

export enum STATISTICS_PERIOD {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  YEARLY = "YEARLY",
  CUSTOM = "CUSTOM",
  LAST_7_DAYS = "LAST_7_DAYS",
  LAST_30_DAYS = "LAST_30_DAYS",
  LAST_90_DAYS = "LAST_90_DAYS",
  LAST_YEAR = "LAST_YEAR",
  THIS_WEEK = "THIS_WEEK",
  THIS_MONTH = "THIS_MONTH",
  THIS_QUARTER = "THIS_QUARTER",
  THIS_YEAR = "THIS_YEAR",
}

// =====================
// Priority & Risk Levels
// =====================

export enum PRIORITY_TYPE {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum RISK_LEVEL {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum STOCK_LEVEL {
  NEGATIVE_STOCK = "NEGATIVE_STOCK",
  OUT_OF_STOCK = "OUT_OF_STOCK",
  CRITICAL = "CRITICAL",
  LOW = "LOW",
  OPTIMAL = "OPTIMAL",
  OVERSTOCKED = "OVERSTOCKED",
}

export enum HEALTH_STATUS {
  EXCELLENT = "EXCELLENT",
  GOOD = "GOOD",
  FAIR = "FAIR",
  POOR = "POOR",
  CRITICAL = "CRITICAL",
}

export enum PERFORMANCE_LEVEL {
  EXCELLENT = "EXCELLENT",
  GOOD = "GOOD",
  FAIR = "FAIR",
  POOR = "POOR",
}

export enum URGENCY_LEVEL {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum EFFORT_LEVEL {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

export enum CONFIDENCE_LEVEL {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

// =====================
// Adjustment Types
// =====================

export enum PERCENTAGE_ADJUST_TYPE {
  INCREASE = "INCREASE",
  DECREASE = "DECREASE",
}

// =====================
// Export & Import
// =====================

export enum EXPORT_FORMAT {
  CSV = "CSV",
  EXCEL = "EXCEL",
  PDF = "PDF",
  JSON = "JSON",
}

// =====================
// Validation & Batch Operations
// =====================

export enum BATCH_OPERATION_STATUS {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  PARTIAL = "PARTIAL",
}

export enum VALIDATION_SEVERITY {
  ERROR = "ERROR",
  WARNING = "WARNING",
  INFO = "INFO",
}

// =====================
// =====================
// Warning Types
// =====================

export enum WARNING_SEVERITY {
  VERBAL = "VERBAL",
  WRITTEN = "WRITTEN",
  SUSPENSION = "SUSPENSION",
  FINAL_WARNING = "FINAL_WARNING",
}

export enum WARNING_CATEGORY {
  SAFETY = "SAFETY",
  MISCONDUCT = "MISCONDUCT",
  INSUBORDINATION = "INSUBORDINATION",
  POLICY_VIOLATION = "POLICY_VIOLATION",
  ATTENDANCE = "ATTENDANCE",
  PERFORMANCE = "PERFORMANCE",
  BEHAVIOR = "BEHAVIOR",
  OTHER = "OTHER",
}

// =====================
// Calendar Types
// =====================

export enum WEEK_DAY {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY",
}

// Alias for Prisma compatibility
export { WEEK_DAY as DAY_OF_WEEK };

export enum MONTH {
  JANUARY = "JANUARY",
  FEBRUARY = "FEBRUARY",
  MARCH = "MARCH",
  APRIL = "APRIL",
  MAY = "MAY",
  JUNE = "JUNE",
  JULY = "JULY",
  AUGUST = "AUGUST",
  SEPTEMBER = "SEPTEMBER",
  OCTOBER = "OCTOBER",
  NOVEMBER = "NOVEMBER",
  DECEMBER = "DECEMBER",
}

export enum MONTH_OCCURRENCE {
  FIRST = "FIRST",
  SECOND = "SECOND",
  THIRD = "THIRD",
  FOURTH = "FOURTH",
  LAST = "LAST",
}

export enum SCHEDULE_FREQUENCY {
  ONCE = "ONCE",
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  BIWEEKLY = "BIWEEKLY",
  MONTHLY = "MONTHLY",
  BIMONTHLY = "BIMONTHLY",
  QUARTERLY = "QUARTERLY",
  TRIANNUAL = "TRIANNUAL",
  QUADRIMESTRAL = "QUADRIMESTRAL",
  SEMI_ANNUAL = "SEMI_ANNUAL",
  ANNUAL = "ANNUAL",
  CUSTOM = "CUSTOM",
}

// =====================
// Size Types
// =====================

export enum PANTS_SIZE {
  SIZE_36 = "SIZE_36",
  SIZE_38 = "SIZE_38",
  SIZE_40 = "SIZE_40",
  SIZE_42 = "SIZE_42",
  SIZE_44 = "SIZE_44",
  SIZE_46 = "SIZE_46",
  SIZE_48 = "SIZE_48",
  SIZE_50 = "SIZE_50",
}

export enum SHIRT_SIZE {
  P = "P",
  M = "M",
  G = "G",
  GG = "GG",
  XG = "XG",
}

export enum BOOT_SIZE {
  SIZE_35 = "SIZE_35",
  SIZE_36 = "SIZE_36",
  SIZE_37 = "SIZE_37",
  SIZE_38 = "SIZE_38",
  SIZE_39 = "SIZE_39",
  SIZE_40 = "SIZE_40",
  SIZE_41 = "SIZE_41",
  SIZE_42 = "SIZE_42",
  SIZE_43 = "SIZE_43",
  SIZE_44 = "SIZE_44",
  SIZE_45 = "SIZE_45",
  SIZE_46 = "SIZE_46",
  SIZE_47 = "SIZE_47",
  SIZE_48 = "SIZE_48",
}

export enum SLEEVES_SIZE {
  P = "P",
  M = "M",
  G = "G",
  GG = "GG",
  XG = "XG",
}

export enum MASK_SIZE {
  P = "P",
  M = "M",
}

export enum GLOVES_SIZE {
  P = "P",
  M = "M",
  G = "G",
}

export enum RAIN_BOOTS_SIZE {
  SIZE_35 = "SIZE_35",
  SIZE_36 = "SIZE_36",
  SIZE_37 = "SIZE_37",
  SIZE_38 = "SIZE_38",
  SIZE_39 = "SIZE_39",
  SIZE_40 = "SIZE_40",
  SIZE_41 = "SIZE_41",
  SIZE_42 = "SIZE_42",
  SIZE_43 = "SIZE_43",
  SIZE_44 = "SIZE_44",
  SIZE_45 = "SIZE_45",
  SIZE_46 = "SIZE_46",
  SIZE_47 = "SIZE_47",
  SIZE_48 = "SIZE_48",
}

// =====================
// Unified PPE Size Enum
// =====================

export enum PPE_SIZE {
  // Shirt, Manguito, Mask, and Gloves sizes
  P = "P",
  M = "M",
  G = "G",
  GG = "GG",
  XG = "XG",

  // Pants and Boots sizes
  SIZE_35 = "SIZE_35",
  SIZE_36 = "SIZE_36",
  SIZE_37 = "SIZE_37",
  SIZE_38 = "SIZE_38",
  SIZE_39 = "SIZE_39",
  SIZE_40 = "SIZE_40",
  SIZE_41 = "SIZE_41",
  SIZE_42 = "SIZE_42",
  SIZE_43 = "SIZE_43",
  SIZE_44 = "SIZE_44",
  SIZE_45 = "SIZE_45",
  SIZE_46 = "SIZE_46",
  SIZE_47 = "SIZE_47",
  SIZE_48 = "SIZE_48",
  SIZE_50 = "SIZE_50",
}

// Alias for Prisma compatibility
export { PPE_SIZE as PPE_SIZE_ENUM };

export enum MEASURE_UNIT {
  // Weight units
  KILOGRAM = "KILOGRAM",
  GRAM = "GRAM",

  // Volume units
  MILLILITER = "MILLILITER",
  LITER = "LITER",
  CUBIC_METER = "CUBIC_METER",
  CUBIC_CENTIMETER = "CUBIC_CENTIMETER",

  // Length units
  MILLIMETER = "MILLIMETER",
  CENTIMETER = "CENTIMETER",
  METER = "METER",
  INCHES = "INCHES",

  // Diameter units (fractional inches)
  INCH_1_8 = "INCH_1_8",
  INCH_1_4 = "INCH_1_4",
  INCH_3_8 = "INCH_3_8",
  INCH_1_2 = "INCH_1_2",
  INCH_5_8 = "INCH_5_8",
  INCH_3_4 = "INCH_3_4",
  INCH_7_8 = "INCH_7_8",
  INCH_1 = "INCH_1",
  INCH_1_1_4 = "INCH_1_1_4",
  INCH_1_1_2 = "INCH_1_1_2",
  INCH_2 = "INCH_2",

  // Thread pitch units
  THREAD_MM = "THREAD_MM",
  THREAD_TPI = "THREAD_TPI",

  // Electrical units
  WATT = "WATT",
  VOLT = "VOLT",
  AMPERE = "AMPERE",

  // Area units
  SQUARE_CENTIMETER = "SQUARE_CENTIMETER",
  SQUARE_METER = "SQUARE_METER",

  // Count and packaging units
  UNIT = "UNIT",
  PAIR = "PAIR",
  DOZEN = "DOZEN",
  HUNDRED = "HUNDRED",
  THOUSAND = "THOUSAND",

  // Container and packaging units
  PACKAGE = "PACKAGE",
  BOX = "BOX",
  ROLL = "ROLL",
  SHEET = "SHEET",
  SET = "SET",
  SACK = "SACK",

  // PPE Size units (letter sizes)
  P = "P",
  M = "M",
  G = "G",
  GG = "GG",
  XG = "XG",
}

export enum MEASURE_TYPE {
  WEIGHT = "WEIGHT",
  VOLUME = "VOLUME",
  LENGTH = "LENGTH",
  WIDTH = "WIDTH",
  THICKNESS = "THICKNESS",
  AREA = "AREA",
  COUNT = "COUNT",
  DIAMETER = "DIAMETER",
  THREAD = "THREAD",
  ELECTRICAL = "ELECTRICAL",
  SIZE = "SIZE",
}

// =====================
// Paint Types
// =====================

// PAINT_TYPE is now a model instead of enum
// Paint types are managed dynamically in the database

export enum PAINT_TYPE_ENUM {
  POLYESTER = "POLYESTER",
  ACRYLIC = "ACRYLIC",
  LACQUER = "LACQUER",
  POLYURETHANE = "POLYURETHANE",
  EPOXY = "EPOXY",
}

export enum PAINT_BRAND_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum PAINT_BRAND {
  PPG = "PPG",
  FARBEN = "FARBEN",
  LAZZURIL = "LAZZURIL",
}

export enum PAINT_FINISH {
  SOLID = "SOLID",
  METALLIC = "METALLIC",
  PEARL = "PEARL",
  MATTE = "MATTE",
  SATIN = "SATIN",
}

// Paint base relationships are now handled via PaintGround model
export enum PAINT_BASE_TYPE {
  TRANSPARENT = "TRANSPARENT",
  WHITE = "WHITE",
  ALUMINUM = "ALUMINUM",
  BLACK = "BLACK",
  MIXING = "MIXING",
}


// =====================
// Truck & Fleet Enums
// =====================

/**
 * Truck spot positions in garage
 * Format: B{garage}_F{lane}_V{spot}
 * - B1, B2, B3: Barracão 1, 2, 3
 * - F1, F2, F3: Faixa (Lane) 1, 2, 3
 * - V1, V2, V3: Vaga (Spot) 1, 2, 3
 * - Each lane can have up to 3 spots (V1, V2, V3)
 * - Minimum spacing between trucks: 2m
 */
export enum TRUCK_SPOT {
  // Yard (Patio)
  YARD_WAIT = 'YARD_WAIT',
  YARD_EXIT = 'YARD_EXIT',
  // Garage 1 (B1)
  B1_F1_V1 = 'B1_F1_V1',
  B1_F1_V2 = 'B1_F1_V2',
  B1_F1_V3 = 'B1_F1_V3',
  B1_F2_V1 = 'B1_F2_V1',
  B1_F2_V2 = 'B1_F2_V2',
  B1_F2_V3 = 'B1_F2_V3',
  B1_F3_V1 = 'B1_F3_V1',
  B1_F3_V2 = 'B1_F3_V2',
  B1_F3_V3 = 'B1_F3_V3',
  // Garage 2 (B2)
  B2_F1_V1 = 'B2_F1_V1',
  B2_F1_V2 = 'B2_F1_V2',
  B2_F1_V3 = 'B2_F1_V3',
  B2_F2_V1 = 'B2_F2_V1',
  B2_F2_V2 = 'B2_F2_V2',
  B2_F2_V3 = 'B2_F2_V3',
  B2_F3_V1 = 'B2_F3_V1',
  B2_F3_V2 = 'B2_F3_V2',
  B2_F3_V3 = 'B2_F3_V3',
  // Garage 3 (B3)
  B3_F1_V1 = 'B3_F1_V1',
  B3_F1_V2 = 'B3_F1_V2',
  B3_F1_V3 = 'B3_F1_V3',
  B3_F2_V1 = 'B3_F2_V1',
  B3_F2_V2 = 'B3_F2_V2',
  B3_F2_V3 = 'B3_F2_V3',
  B3_F3_V1 = 'B3_F3_V1',
  B3_F3_V2 = 'B3_F3_V2',
  B3_F3_V3 = 'B3_F3_V3',
}

export enum TRUCK_MANUFACTURER {
  VOLKSWAGEN = "VOLKSWAGEN",
  MERCEDES_BENZ = "MERCEDES_BENZ",
  SCANIA = "SCANIA",
  VOLVO = "VOLVO",
  DAF = "DAF",
  IVECO = "IVECO",
}

/**
 * Truck categories/types
 * Categories define the size and configuration of the truck
 */
export enum TRUCK_CATEGORY {
  MINI = 'MINI', // Mini truck (small urban delivery)
  VUC = 'VUC', // VUC - Veículo Urbano de Carga (Urban Cargo Vehicle)
  THREE_QUARTER = 'THREE_QUARTER', // 3/4 truck (light commercial)
  RIGID = 'RIGID', // Toco - Rigid truck with single rear axle
  TRUCK = 'TRUCK', // Standard truck
  SEMI_TRAILER = 'SEMI_TRAILER', // Carreta - Semi-trailer truck
  SEMI_TRAILER_2_AXLES = 'SEMI_TRAILER_2_AXLES', // Semirreboque 2 Eixos
  B_DOUBLE_FRONT = 'B_DOUBLE_FRONT', // Bitrem Compartimento Frontal - front compartment of B-Double trailer
  B_DOUBLE_REAR = 'B_DOUBLE_REAR', // Bitrem Compartimento Traseiro - rear compartment of B-Double trailer
  BITRUCK = 'BITRUCK', // Bitruck - Rigid truck with dual steering axle
}

/**
 * Truck body/implement types
 * Defines the type of body or implement mounted on the truck
 */
export enum IMPLEMENT_TYPE {
  DRY_CARGO = 'DRY_CARGO', // Carga Seca - Dry cargo body
  REFRIGERATED = 'REFRIGERATED', // Refrigerado - Refrigerated body
  INSULATED = 'INSULATED', // Isoplastic - Insulated body
  CURTAIN_SIDE = 'CURTAIN_SIDE', // Sider - Curtain-side body
  TANK = 'TANK', // Tanque - Tank truck
  FLATBED = 'FLATBED', // Carroceria - Open flatbed/stake body
}

// =====================
// Operations & Actions
// =====================

export enum ACTIVITY_OPERATION {
  INBOUND = "INBOUND",
  OUTBOUND = "OUTBOUND",
}

export enum AUDIT_ACTION {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
}

export enum ENTITY_TYPE {
  ACTIVITY = "ACTIVITY",
  AIRBRUSHING = "AIRBRUSHING",
  BONUS = "BONUS",
  BORROW = "BORROW",
  CATEGORY = "CATEGORY",
  COLLECTION = "COLLECTION",
  BONIFICATION = "BONIFICATION",
  CUT = "CUT",
  CUT_ITEM = "CUT_ITEM",
  CUT_PLAN = "CUT_PLAN",
  CUT_REQUEST = "CUT_REQUEST",
  CUSTOMER = "CUSTOMER",
  DASHBOARD = "DASHBOARD",
  DEPLOYMENT = "DEPLOYMENT",
  DELIVERY = "DELIVERY",
  DISCOUNT = "DISCOUNT",
  PPE_CONFIG = "PPE_CONFIG",
  PPE_DELIVERY = "PPE_DELIVERY",
  PPE_REQUEST = "PPE_REQUEST",
  PPE_DELIVERY_SCHEDULE = "PPE_DELIVERY_SCHEDULE",
  PPE_SIZE = "PPE_SIZE",
  EXTERNAL_OPERATION = "EXTERNAL_OPERATION",
  EXTERNAL_OPERATION_ITEM = "EXTERNAL_OPERATION_ITEM",
  FILE = "FILE",
  HOLIDAY = "HOLIDAY",
  ITEM = "ITEM",
  ITEM_BRAND = "ITEM_BRAND",
  ITEM_CATEGORY = "ITEM_CATEGORY",
  IMPLEMENT_MEASURE = "IMPLEMENT_MEASURE",
  MAINTENANCE = "MAINTENANCE",
  MAINTENANCE_ITEM = "MAINTENANCE_ITEM",
  MAINTENANCE_SCHEDULE = "MAINTENANCE_SCHEDULE",
  MEASURE = "MEASURE",
  NOTIFICATION = "NOTIFICATION",
  NOTIFICATION_PREFERENCE = "NOTIFICATION_PREFERENCE",
  OBSERVATION = "OBSERVATION",
  ORDER = "ORDER",
  ORDER_ITEM = "ORDER_ITEM",
  ORDER_RULE = "ORDER_RULE",
  ORDER_SCHEDULE = "ORDER_SCHEDULE",
  PAINT = "PAINT",
  PAINT_TYPE = "PAINT_TYPE",
  PAINT_BRAND = "PAINT_BRAND",
  PAINT_GROUND = "PAINT_GROUND",
  PAINT_FORMULA = "PAINT_FORMULA",
  PAINT_FORMULA_COMPONENT = "PAINT_FORMULA_COMPONENT",
  PAINT_PRODUCTION = "PAINT_PRODUCTION",
  PARKING_SPOT = "PARKING_SPOT",
  PAYROLL = "PAYROLL",
  PIECE = "PIECE",
  POSITION = "POSITION",
  POSITION_REMUNERATION = "POSITION_REMUNERATION",
  PREFERENCES = "PREFERENCES",
  PRICE = "PRICE",
  PRODUCTION = "PRODUCTION",
  PURCHASE = "PURCHASE",
  WARNING = "WARNING",
  SECTOR = "SECTOR",
  SEEN_NOTIFICATION = "SEEN_NOTIFICATION",
  SERVICE = "SERVICE",
  SERVICE_ORDER = "SERVICE_ORDER",
  SUPPLIER = "SUPPLIER",
  TASK = "TASK",
  TIME_CLOCK_ENTRY = "TIME_CLOCK_ENTRY",
  TRUCK = "TRUCK",
  USER = "USER",
  VACATION = "VACATION",
  THIRTEENTH = "THIRTEENTH",
  VERIFICATION = "VERIFICATION",
  SALARY_ADJUSTMENT = "SALARY_ADJUSTMENT",
  USER_POSITION_HISTORY = "USER_POSITION_HISTORY",
  BENEFIT = "BENEFIT",
  USER_BENEFIT = "USER_BENEFIT",
  ADMISSION = "ADMISSION",
  TERMINATION = "TERMINATION",
  MEDICAL_EXAM = "MEDICAL_EXAM",
  LEAVE = "LEAVE",
  DEPENDENT = "DEPENDENT",
  AGENDA_EVENT = "AGENDA_EVENT",
  NOTE = "NOTE",
  FISPQ = "FISPQ",
  RESPONSIBLE = "RESPONSIBLE",
  WAREHOUSE_LOCATION = "WAREHOUSE_LOCATION",
  TASK_QUOTE = "TASK_QUOTE",
  TASK_QUOTE_ITEM = "TASK_QUOTE_ITEM",
  TASK_QUOTE_SERVICE = "TASK_QUOTE_SERVICE",
  TASK_QUOTE_CUSTOMER_CONFIG = "TASK_QUOTE_CUSTOMER_CONFIG",
  VACATION_GROUP = "VACATION_GROUP",
}

export enum CHANGE_ACTION {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  RESTORE = "RESTORE",
  ROLLBACK = "ROLLBACK",
  ARCHIVE = "ARCHIVE",
  UNARCHIVE = "UNARCHIVE",
  ACTIVATE = "ACTIVATE",
  DEACTIVATE = "DEACTIVATE",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  CANCEL = "CANCEL",
  COMPLETE = "COMPLETE",
  RESCHEDULE = "RESCHEDULE",
  BATCH_CREATE = "BATCH_CREATE",
  BATCH_UPDATE = "BATCH_UPDATE",
  BATCH_DELETE = "BATCH_DELETE",
  VIEW = "VIEW",
}

export enum CHANGE_TRIGGERED_BY {
  TASK_CREATE = "TASK_CREATE",
  TASK_UPDATE = "TASK_UPDATE",
  TASK_COPY_FROM_TASK = "TASK_COPY_FROM_TASK",
  ITEM_UPDATE = "ITEM_UPDATE",
  USER_ACTION = "USER_ACTION",
  BATCH_CREATE = "BATCH_CREATE",
  BATCH_UPDATE = "BATCH_UPDATE",
  BATCH_DELETE = "BATCH_DELETE",
  BATCH_OPERATION = "BATCH_OPERATION",
  SYSTEM = "SYSTEM",
  SYSTEM_GENERATED = "SYSTEM_GENERATED",
  USER = "USER",
  EXTERNAL_OPERATION = "EXTERNAL_OPERATION",
  EXTERNAL_OPERATION_DELETE = "EXTERNAL_OPERATION_DELETE",
  EXTERNAL_OPERATION_RETURN = "EXTERNAL_OPERATION_RETURN",
  EXTERNAL_OPERATION_ITEM = "EXTERNAL_OPERATION_ITEM",
  EXTERNAL_OPERATION_ITEM_UPDATE = "EXTERNAL_OPERATION_ITEM_UPDATE",
  EXTERNAL_OPERATION_ITEM_DELETE = "EXTERNAL_OPERATION_ITEM_DELETE",
  PAINT_FORMULA_COMPONENT_CREATE = "PAINT_FORMULA_COMPONENT_CREATE",
  PAINT_FORMULA_COMPONENT_UPDATE = "PAINT_FORMULA_COMPONENT_UPDATE",
  PAINT_FORMULA_COMPONENT_DELETE = "PAINT_FORMULA_COMPONENT_DELETE",
  PAINT_FORMULA_COMPONENT_BATCH_CREATE = "PAINT_FORMULA_COMPONENT_BATCH_CREATE",
  PAINT_FORMULA_COMPONENT_BATCH_UPDATE = "PAINT_FORMULA_COMPONENT_BATCH_UPDATE",
  PAINT_FORMULA_COMPONENT_BATCH_DELETE = "PAINT_FORMULA_COMPONENT_BATCH_DELETE",
  PAINT_PRODUCTION_CREATE = "PAINT_PRODUCTION_CREATE",
  PAINT_PRODUCTION_UPDATE = "PAINT_PRODUCTION_UPDATE",
  PAINT_PRODUCTION_DELETE = "PAINT_PRODUCTION_DELETE",
  PAINT_PRODUCTION_BATCH_CREATE = "PAINT_PRODUCTION_BATCH_CREATE",
  PAINT_PRODUCTION_BATCH_UPDATE = "PAINT_PRODUCTION_BATCH_UPDATE",
  PAINT_PRODUCTION_BATCH_DELETE = "PAINT_PRODUCTION_BATCH_DELETE",
  PAINT_CREATE = "PAINT_CREATE",
  PAINT_UPDATE = "PAINT_UPDATE",
  PAINT_DELETE = "PAINT_DELETE",
  PAINT_BATCH_CREATE = "PAINT_BATCH_CREATE",
  PAINT_BATCH_UPDATE = "PAINT_BATCH_UPDATE",
  PAINT_BATCH_DELETE = "PAINT_BATCH_DELETE",
  PAINT_FORMULA_CREATE = "PAINT_FORMULA_CREATE",
  PAINT_FORMULA_UPDATE = "PAINT_FORMULA_UPDATE",
  PAINT_FORMULA_DELETE = "PAINT_FORMULA_DELETE",
  PAINT_FORMULA_BATCH_CREATE = "PAINT_FORMULA_BATCH_CREATE",
  PAINT_FORMULA_BATCH_UPDATE = "PAINT_FORMULA_BATCH_UPDATE",
  PAINT_FORMULA_BATCH_DELETE = "PAINT_FORMULA_BATCH_DELETE",
  PAINT_TYPE_CREATE = "PAINT_TYPE_CREATE",
  PAINT_TYPE_UPDATE = "PAINT_TYPE_UPDATE",
  PAINT_TYPE_DELETE = "PAINT_TYPE_DELETE",
  PAINT_TYPE_BATCH_CREATE = "PAINT_TYPE_BATCH_CREATE",
  PAINT_TYPE_BATCH_UPDATE = "PAINT_TYPE_BATCH_UPDATE",
  PAINT_TYPE_BATCH_DELETE = "PAINT_TYPE_BATCH_DELETE",
  PAINT_BRAND_CREATE = "PAINT_BRAND_CREATE",
  PAINT_BRAND_UPDATE = "PAINT_BRAND_UPDATE",
  PAINT_BRAND_DELETE = "PAINT_BRAND_DELETE",
  PAINT_BRAND_BATCH_CREATE = "PAINT_BRAND_BATCH_CREATE",
  PAINT_BRAND_BATCH_UPDATE = "PAINT_BRAND_BATCH_UPDATE",
  PAINT_BRAND_BATCH_DELETE = "PAINT_BRAND_BATCH_DELETE",
  PAINT_GROUND_CREATE = "PAINT_GROUND_CREATE",
  PAINT_GROUND_UPDATE = "PAINT_GROUND_UPDATE",
  PAINT_GROUND_DELETE = "PAINT_GROUND_DELETE",
  PAINT_GROUND_BATCH_CREATE = "PAINT_GROUND_BATCH_CREATE",
  PAINT_GROUND_BATCH_UPDATE = "PAINT_GROUND_BATCH_UPDATE",
  PAINT_GROUND_BATCH_DELETE = "PAINT_GROUND_BATCH_DELETE",
  ORDER_UPDATE = "ORDER_UPDATE",
  ORDER_CREATE = "ORDER_CREATE",
  ORDER_STATUS_CHANGE = "ORDER_STATUS_CHANGE",
  ORDER_CANCEL = "ORDER_CANCEL",
  ORDER_ITEM_UPDATE = "ORDER_ITEM_UPDATE",
  ORDER_ITEM_RECEIVED = "ORDER_ITEM_RECEIVED",
  ORDER_ITEM_SYNC = "ORDER_ITEM_SYNC",
  EXTERNAL_OPERATION_SYNC = "EXTERNAL_OPERATION_SYNC",
  SCHEDULE = "SCHEDULE",
  ACTIVITY_CREATE = "ACTIVITY_CREATE",
  ACTIVITY_UPDATE = "ACTIVITY_UPDATE",
  ACTIVITY_DELETE = "ACTIVITY_DELETE",
  PPE_DELIVERY = "PPE_DELIVERY",
  ACTIVITY_SYNC = "ACTIVITY_SYNC",
  INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT",
  INVENTORY_COUNT = "INVENTORY_COUNT",
  ITEM_MONTHLY_CONSUMPTION_UPDATE = "ITEM_MONTHLY_CONSUMPTION_UPDATE",
  AUTOMATIC_MIN_MAX_UPDATE = "AUTOMATIC_MIN_MAX_UPDATE",
  SMS_VERIFICATION_CREATE = "SMS_VERIFICATION_CREATE",
  SMS_VERIFICATION_SEND = "SMS_VERIFICATION_SEND",
  SMS_VERIFICATION_VERIFY = "SMS_VERIFICATION_VERIFY",
  SMS_VERIFICATION_EXPIRE = "SMS_VERIFICATION_EXPIRE",
  SMS_VERIFICATION_CANCEL = "SMS_VERIFICATION_CANCEL",
  EMAIL_SERVICE = "EMAIL_SERVICE",
  VERIFICATION_CREATE = "VERIFICATION_CREATE",
  VERIFICATION_SEND = "VERIFICATION_SEND",
  VERIFICATION_VERIFY = "VERIFICATION_VERIFY",
  VERIFICATION_EXPIRE = "VERIFICATION_EXPIRE",
  VERIFICATION_CANCEL = "VERIFICATION_CANCEL",
  VERIFICATION_RESEND = "VERIFICATION_RESEND",
  VEHICLE_MOVEMENT = "VEHICLE_MOVEMENT",
  PARKING_ASSIGNMENT = "PARKING_ASSIGNMENT",
  OBSERVATION_CREATE = "OBSERVATION_CREATE",
  OBSERVATION_DELETE = "OBSERVATION_DELETE",
  SCHEDULED_JOB = "SCHEDULED_JOB",
  API = "API",
  WEBHOOK = "WEBHOOK",
  ADMIN = "ADMIN",
}

// Alias for Prisma compatibility
export { CHANGE_TRIGGERED_BY as ChangeLogTriggeredByType };

// =====================
// Notification Types
// =====================

export enum NOTIFICATION_IMPORTANCE {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum NOTIFICATION_TYPE {
  SYSTEM = "SYSTEM",
  PRODUCTION = "PRODUCTION", // Replaces TASK, SERVICE_ORDER, CUT
  STOCK = "STOCK", // Replaces ORDER
  USER = "USER", // Replaces PPE, VACATION, WARNING
  GENERAL = "GENERAL",
}

export enum NOTIFICATION_CHANNEL {
  IN_APP = "IN_APP",
  PUSH = "PUSH",
  EMAIL = "EMAIL",
  WHATSAPP = "WHATSAPP",
}

// =====================
// File Types
// =====================

export enum FILE_ENTITY_TYPE {
  TASK = "TASK",
  CUSTOMER_LOGO = "CUSTOMER_LOGO",
  SUPPLIER_LOGO = "SUPPLIER_LOGO",
  OBSERVATION = "OBSERVATION",
  WARNING = "WARNING",
  ORDER_BUDGET = "ORDER_BUDGET",
  ORDER_NFE = "ORDER_NFE",
  ORDER_RECEIPT = "ORDER_RECEIPT",
  TASK_BUDGET = "TASK_BUDGET",
  TASK_NFE = "TASK_NFE",
  TASK_RECEIPT = "TASK_RECEIPT",
  AIRBRUSHING_RECEIPT = "AIRBRUSHING_RECEIPT",
  AIRBRUSHING_NFE = "AIRBRUSHING_NFE",
  EXTERNAL_OPERATION_BUDGET = "EXTERNAL_OPERATION_BUDGET",
  EXTERNAL_OPERATION_NFE = "EXTERNAL_OPERATION_NFE",
  EXTERNAL_OPERATION_RECEIPT = "EXTERNAL_OPERATION_RECEIPT",
  EXPENSE = "EXPENSE",
}

// =====================
// PPE Types
// =====================

export enum PPE_TYPE {
  SHIRT = "SHIRT",
  PANTS = "PANTS",
  SHORT = "SHORT",
  BOOTS = "BOOTS",
  SLEEVES = "SLEEVES",
  MASK = "MASK",
  GLOVES = "GLOVES",
  RAIN_BOOTS = "RAIN_BOOTS",
  OVERALL = "OVERALL",
  OTHERS = "OTHERS",
}

export enum PPE_SIZE_TYPE {
  SHIRT = "SHIRT",
  PANTS = "PANTS",
  BOOT = "BOOT",
  GLOVE = "GLOVE",
  MASK = "MASK",
  OVERALL = "OVERALL",
  HELMET = "HELMET",
  UNIFORM = "UNIFORM",
}

export enum PPE_DELIVERY_MODE {
  SCHEDULED = "SCHEDULED",
  ON_DEMAND = "ON_DEMAND",
  BOTH = "BOTH",
}

// =====================
// =====================

// =====================
// Order & Stock Types
// =====================

export enum ORDER_TRIGGER_TYPE {
  STOCK_LEVEL = "STOCK_LEVEL",
  CONSUMPTION_RATE = "CONSUMPTION_RATE",
  SCHEDULED = "SCHEDULED",
}

export enum MAINTENANCE_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  OVERDUE = "OVERDUE",
}

export enum ACTIVITY_REASON {
  ORDER_RECEIVED = "ORDER_RECEIVED",
  PRODUCTION_USAGE = "PRODUCTION_USAGE",
  PPE_DELIVERY = "PPE_DELIVERY",
  RETURN = "RETURN",
  EXTERNAL_OPERATION = "EXTERNAL_OPERATION",
  EXTERNAL_OPERATION_RETURN = "EXTERNAL_OPERATION_RETURN",
  INVENTORY_COUNT = "INVENTORY_COUNT",
  MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT",
  MAINTENANCE = "MAINTENANCE",
  DAMAGE = "DAMAGE",
  LOSS = "LOSS",
  PAINT_PRODUCTION = "PAINT_PRODUCTION",
  OTHER = "OTHER",
}

// =====================
// Color Schema
// =====================

export enum COLOR_SCHEMA {
  LIGHT = "LIGHT",
  DARK = "DARK",
  SYSTEM = "SYSTEM",
}

// =====================
// Verification Type
// =====================

export enum VERIFICATION_TYPE {
  EMAIL = "EMAIL",
  PHONE = "PHONE",
  PASSWORD_RESET = "PASSWORD_RESET",
}

// =====================
// Verification Error Codes
// =====================

export enum VERIFICATION_ERROR_CODE {
  // Request validation errors
  INVALID_CONTACT = "INVALID_CONTACT",
  CONTACT_REQUIRED = "CONTACT_REQUIRED",
  CODE_REQUIRED = "CODE_REQUIRED",
  INVALID_CONTACT_FORMAT = "INVALID_CONTACT_FORMAT",

  // User-related errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
  USER_INACTIVE = "USER_INACTIVE",

  // Code validation errors
  INVALID_CODE = "INVALID_CODE",
  CODE_EXPIRED = "CODE_EXPIRED",
  NO_CODE_SENT = "NO_CODE_SENT",
  CODE_MISMATCH = "CODE_MISMATCH",

  // Rate limiting errors
  TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  CONTACT_COOLDOWN = "CONTACT_COOLDOWN",
  IP_RATE_LIMITED = "IP_RATE_LIMITED",
  PROGRESSIVE_DELAY = "PROGRESSIVE_DELAY",

  // Service errors
  SMS_SEND_FAILED = "SMS_SEND_FAILED",
  EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",
  NOTIFICATION_FAILED = "NOTIFICATION_FAILED",
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",

  // System errors
  DATABASE_ERROR = "DATABASE_ERROR",
  CACHE_ERROR = "CACHE_ERROR",
  CONFIGURATION_ERROR = "CONFIGURATION_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",

  // Security errors
  SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",
  BLOCKED_IP = "BLOCKED_IP",
  BLACKLISTED_CONTACT = "BLACKLISTED_CONTACT",
  SECURITY_VIOLATION = "SECURITY_VIOLATION",
}

// =====================
// Verification Error Severity
// =====================

export enum VERIFICATION_ERROR_SEVERITY {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

// =====================
// Verification Error Category
// =====================

export enum VERIFICATION_ERROR_CATEGORY {
  VALIDATION = "VALIDATION",
  RATE_LIMITING = "RATE_LIMITING",
  AUTHENTICATION = "AUTHENTICATION",
  EXTERNAL_SERVICE = "EXTERNAL_SERVICE",
  SYSTEM = "SYSTEM",
  SECURITY = "SECURITY",
}

// =====================
// Workload Level
// =====================

export enum WORKLOAD_LEVEL {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

// =====================
// File Formats
// =====================

export enum FILE_FORMAT {
  JSON = "JSON",
  YAML = "YAML",
  CSV = "CSV",
  EXCEL = "EXCEL",
  PDF = "PDF",
}

// =====================
// Activity Levels
// =====================

export enum ACTIVITY_LEVEL {
  VERY_ACTIVE = "VERY_ACTIVE",
  ACTIVE = "ACTIVE",
  OCCASIONAL = "OCCASIONAL",
  DORMANT = "DORMANT",
  LOST = "LOST",
}

// =====================
// Change Actions
// =====================
// Event Types
// =====================

export enum EVENT_TYPE {
  CREATED = "CREATED",
  STARTED = "STARTED",
  PAUSED = "PAUSED",
  RESUMED = "RESUMED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

// =====================
// Timeline Event Types
// =====================

export enum TIMELINE_EVENT_TYPE {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  STATUS_CHANGED = "STATUS_CHANGED",
  FILE_ADDED = "FILE_ADDED",
  FILE_REMOVED = "FILE_REMOVED",
  NOTE_ADDED = "NOTE_ADDED",
  ASSIGNED = "ASSIGNED",
  COMPLETED = "COMPLETED",
}

// =====================
// Merge Strategy
// =====================

export enum MERGE_STRATEGY {
  KEEP_PRIMARY = "KEEP_PRIMARY",
  KEEP_NEWEST = "KEEP_NEWEST",
  MANUAL = "MANUAL",
}

// =====================
// Group By Options
// =====================

export enum GROUP_BY {
  DAY = "DAY",
  WEEK = "WEEK",
  MONTH = "MONTH",
  YEAR = "YEAR",
  ITEM = "ITEM",
  USER = "USER",
}

// =====================
// Holiday Types
// =====================

export enum HOLIDAY_TYPE {
  NATIONAL = "NATIONAL",
  STATE = "STATE",
  MUNICIPAL = "MUNICIPAL",
  OPTIONAL = "OPTIONAL",
}

// =====================
// Alert Types
// =====================

export enum ALERT_TYPE {
  // Activity Alerts
  HIGH_SPENDING = "HIGH_SPENDING",
  UNUSUAL_PATTERN = "UNUSUAL_PATTERN",
  DISCREPANCY = "DISCREPANCY",
  LOW_STOCK = "LOW_STOCK",

  // Item Alerts
  STOCK_OUT = "STOCK_OUT",
  OVERSTOCK = "OVERSTOCK",
  SLOW_MOVING = "SLOW_MOVING",
  REORDER_NEEDED = "REORDER_NEEDED",

  // User Alerts
  HIGH_TURNOVER = "HIGH_TURNOVER",
  ATTENDANCE_ISSUE = "ATTENDANCE_ISSUE",

  // Order Alerts
  DELIVERY_DELAY = "DELIVERY_DELAY",

  // Customer Alerts
  SERVICE_ISSUE = "SERVICE_ISSUE",
  PAYMENT_DELAY = "PAYMENT_DELAY",

  // Task Alerts
  OVERDUE = "OVERDUE",
  CUSTOMER_COMPLAINT = "CUSTOMER_COMPLAINT",

  // Borrow Alerts
  HIGH_DEMAND = "HIGH_DEMAND",
  USER_VIOLATION = "USER_VIOLATION",

  // Warning Alerts
  REPEAT_OFFENDER = "REPEAT_OFFENDER",
  ESCALATION_NEEDED = "ESCALATION_NEEDED",
  PATTERN_DETECTED = "PATTERN_DETECTED",

  // PPE Alerts
  STOCK_SHORTAGE = "STOCK_SHORTAGE",
  MISSING_DELIVERY = "MISSING_DELIVERY",

  // Supplier Alerts
  DELIVERY_DELAYS = "DELIVERY_DELAYS",
}

export enum TASK_OBSERVATION_TYPE {
  DAMAGE = "DAMAGE",
  OVERDUE = "OVERDUE",
  QUALITY = "QUALITY",
}

export enum ITEM_ISSUE_TYPE {
  OVERAGE = "OVERAGE",
  SHORTAGE = "SHORTAGE",
  DAMAGE = "DAMAGE",
  MISMATCH = "MISMATCH",
}

// =====================
// Time Ranges
// =====================

export enum TIME_RANGE {
  LAST_7_DAYS = "LAST_7_DAYS",
  LAST_30_DAYS = "LAST_30_DAYS",
  LAST_90_DAYS = "LAST_90_DAYS",
  LAST_YEAR = "LAST_YEAR",
  CUSTOM = "CUSTOM",
}

export enum DASHBOARD_TIME_PERIOD {
  TODAY = "TODAY",
  THIS_WEEK = "THIS_WEEK",
  THIS_MONTH = "THIS_MONTH",
  THIS_YEAR = "THIS_YEAR",
  TOTAL = "TOTAL",
  ALL_TIME = "ALL_TIME",
}

// =====================
// Schedule & Order Enums
// =====================

export enum RESCHEDULE_REASON {
  CUSTOMER_REQUEST = "CUSTOMER_REQUEST",
  RESOURCE_UNAVAILABLE = "RESOURCE_UNAVAILABLE",
  MATERIAL_SHORTAGE = "MATERIAL_SHORTAGE",
  EQUIPMENT_FAILURE = "EQUIPMENT_FAILURE",
  WEATHER_CONDITIONS = "WEATHER_CONDITIONS",
  STAFF_UNAVAILABLE = "STAFF_UNAVAILABLE",
  PRIORITY_CHANGE = "PRIORITY_CHANGE",
  TECHNICAL_ISSUES = "TECHNICAL_ISSUES",
  OTHER = "OTHER",
}

export enum MAINTENANCE_SCHEDULE_STATUS {
  PENDING = "PENDING",
  FINISHED = "FINISHED",
  CANCELLED = "CANCELLED",
}

// =====================
// Change Log Enums
// =====================

export enum CHANGE_LOG_ENTITY_TYPE {
  ABSENCE = "ABSENCE",
  ACTIVITY = "ACTIVITY",
  AIRBRUSHING = "AIRBRUSHING",
  BONUS = "BONUS",
  BORROW = "BORROW",
  CALCULATION = "CALCULATION",
  CALCULATION_DETAIL = "CALCULATION_DETAIL",
  CALCULATION_DECOMPOSITION = "CALCULATION_DECOMPOSITION",
  CATEGORY = "CATEGORY",
  COLLECTION = "COLLECTION",
  BONIFICATION = "BONIFICATION",
  CUT = "CUT",
  CUT_ITEM = "CUT_ITEM",
  CUT_PLAN = "CUT_PLAN",
  CUT_REQUEST = "CUT_REQUEST",
  CUSTOMER = "CUSTOMER",
  DEPLOYMENT = "DEPLOYMENT",
  DELIVERY = "DELIVERY",
  DISCOUNT = "DISCOUNT",
  ECONOMIC_ACTIVITY = "ECONOMIC_ACTIVITY",
  EXPENSE = "EXPENSE",
  EXTERNAL_OPERATION = "EXTERNAL_OPERATION",
  EXTERNAL_OPERATION_ITEM = "EXTERNAL_OPERATION_ITEM",
  FILE = "FILE",
  HOLIDAY = "HOLIDAY",
  ITEM = "ITEM",
  ITEM_BRAND = "ITEM_BRAND",
  ITEM_CATEGORY = "ITEM_CATEGORY",
  IMPLEMENT_MEASURE = "IMPLEMENT_MEASURE",
  MAINTENANCE = "MAINTENANCE",
  MAINTENANCE_ITEM = "MAINTENANCE_ITEM",
  MAINTENANCE_SCHEDULE = "MAINTENANCE_SCHEDULE",
  NOTIFICATION = "NOTIFICATION",
  NOTIFICATION_PREFERENCE = "NOTIFICATION_PREFERENCE",
  OBSERVATION = "OBSERVATION",
  ORDER = "ORDER",
  ORDER_ITEM = "ORDER_ITEM",
  ORDER_RULE = "ORDER_RULE",
  ORDER_SCHEDULE = "ORDER_SCHEDULE",
  PAINT = "PAINT",
  PAINT_FORMULA = "PAINT_FORMULA",
  PAINT_FORMULA_COMPONENT = "PAINT_FORMULA_COMPONENT",
  PAINT_GROUND = "PAINT_GROUND",
  PAINT_PRODUCTION = "PAINT_PRODUCTION",
  PAINT_TYPE = "PAINT_TYPE",
  PARKING_SPOT = "PARKING_SPOT",
  PAYROLL = "PAYROLL",
  PIECE = "PIECE",
  POSITION = "POSITION",
  PPE_CONFIG = "PPE_CONFIG",
  PPE_DELIVERY = "PPE_DELIVERY",
  PPE_DELIVERY_ITEM = "PPE_DELIVERY_ITEM",
  PPE_DELIVERY_SCHEDULE = "PPE_DELIVERY_SCHEDULE",
  PPE_REQUEST = "PPE_REQUEST",
  PPE_SIZE = "PPE_SIZE",
  PRICE = "PRICE",
  PRODUCTION = "PRODUCTION",
  PURCHASE = "PURCHASE",
  REPRESENTATIVE = "REPRESENTATIVE",
  SECTOR = "SECTOR",
  SEEN_NOTIFICATION = "SEEN_NOTIFICATION",
  SERVICE = "SERVICE",
  SERVICE_ORDER = "SERVICE_ORDER",
  SUPPLIER = "SUPPLIER",
  TASK = "TASK",
  TASK_QUOTE = "TASK_QUOTE",
  TASK_QUOTE_ITEM = "TASK_QUOTE_ITEM",
  TIME_CLOCK_ENTRY = "TIME_CLOCK_ENTRY",
  TRUCK = "TRUCK",
  USER = "USER",
  VACATION = "VACATION",
  THIRTEENTH = "THIRTEENTH",
  VERIFICATION = "VERIFICATION",
  WARNING = "WARNING",
  SALARY_ADJUSTMENT = "SALARY_ADJUSTMENT",
  USER_POSITION_HISTORY = "USER_POSITION_HISTORY",
  BENEFIT = "BENEFIT",
  USER_BENEFIT = "USER_BENEFIT",
  ADMISSION = "ADMISSION",
  TERMINATION = "TERMINATION",
  MEDICAL_EXAM = "MEDICAL_EXAM",
  LEAVE = "LEAVE",
  DEPENDENT = "DEPENDENT",
  AGENDA_EVENT = "AGENDA_EVENT",
  NOTE = "NOTE",
  FISPQ = "FISPQ",
  PREFERENCES = "PREFERENCES",
  RESPONSIBLE = "RESPONSIBLE",
  WAREHOUSE_LOCATION = "WAREHOUSE_LOCATION",
  TASK_QUOTE_SERVICE = "TASK_QUOTE_SERVICE",
  TASK_QUOTE_CUSTOMER_CONFIG = "TASK_QUOTE_CUSTOMER_CONFIG",
  VACATION_GROUP = "VACATION_GROUP",
}

// Alias for Prisma compatibility
export { CHANGE_LOG_ENTITY_TYPE as ChangeLogEntityType };

// =====================
// FISPQ / FDS (Ficha de Informações de Segurança de Produtos Químicos / Safety Data Sheet)
// =====================

export enum GHS_PICTOGRAM {
  GHS01_EXPLOSIVE = "GHS01_EXPLOSIVE",
  GHS02_FLAMMABLE = "GHS02_FLAMMABLE",
  GHS03_OXIDIZING = "GHS03_OXIDIZING",
  GHS04_GAS_UNDER_PRESSURE = "GHS04_GAS_UNDER_PRESSURE",
  GHS05_CORROSIVE = "GHS05_CORROSIVE",
  GHS06_TOXIC = "GHS06_TOXIC",
  GHS07_HARMFUL = "GHS07_HARMFUL",
  GHS08_HEALTH_HAZARD = "GHS08_HEALTH_HAZARD",
  GHS09_ENVIRONMENTAL = "GHS09_ENVIRONMENTAL",
}

export enum GHS_SIGNAL_WORD {
  DANGER = "DANGER",
  WARNING = "WARNING",
}

export enum FISPQ_STATUS {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  ARCHIVED = "ARCHIVED",
}

export enum CHANGE_LOG_ACTION {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  RESTORE = "RESTORE",
  ROLLBACK = "ROLLBACK",
  ARCHIVE = "ARCHIVE",
  UNARCHIVE = "UNARCHIVE",
  ACTIVATE = "ACTIVATE",
  DEACTIVATE = "DEACTIVATE",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  CANCEL = "CANCEL",
  COMPLETE = "COMPLETE",
  RESCHEDULE = "RESCHEDULE",
  BATCH_CREATE = "BATCH_CREATE",
  BATCH_UPDATE = "BATCH_UPDATE",
  BATCH_DELETE = "BATCH_DELETE",
  VIEW = "VIEW",
}

// Alias for Prisma compatibility
export { CHANGE_LOG_ACTION as ChangeLogAction };

// =====================
// Notification Action Types
// =====================

export enum NOTIFICATION_ACTION_TYPE {
  VIEW_DETAILS = "VIEW_DETAILS",
  APPROVE_REQUEST = "APPROVE_REQUEST",
  REJECT_REQUEST = "REJECT_REQUEST",
  COMPLETE_TASK = "COMPLETE_TASK",
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  VIEW_ORDER = "VIEW_ORDER",
  VIEW_SERVICE_ORDER = "VIEW_SERVICE_ORDER",
  VIEW_REPORT = "VIEW_REPORT",
  ACKNOWLEDGE = "ACKNOWLEDGE",
  DISMISS = "DISMISS",
}

// =====================
// SMS Verification Enums
// =====================

export enum SMS_VERIFICATION_TYPE {
  PHONE_VERIFICATION = "PHONE_VERIFICATION",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  PASSWORD_RESET = "PASSWORD_RESET",
  TWO_FACTOR_AUTH = "TWO_FACTOR_AUTH",
  ACCOUNT_CONFIRMATION = "ACCOUNT_CONFIRMATION",
}

export enum SMS_VERIFICATION_STATUS {
  PENDING = "PENDING",
  SENT = "SENT",
  VERIFIED = "VERIFIED",
  EXPIRED = "EXPIRED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  RATE_LIMITED = "RATE_LIMITED",
  BLOCKED = "BLOCKED",
}

// =====================
// Rate Limiting Enums
// =====================

export enum RATE_LIMIT_TYPE {
  PER_CODE_ATTEMPT = "PER_CODE_ATTEMPT",
  IP_VERIFICATION = "IP_VERIFICATION",
  CODE_SEND_CONTACT = "CODE_SEND_CONTACT",
  CODE_SEND_IP = "CODE_SEND_IP",
  ACCOUNT_LOCKOUT = "ACCOUNT_LOCKOUT",
  GLOBAL_RATE_LIMIT = "GLOBAL_RATE_LIMIT",
}

export enum LOCKOUT_REASON {
  EXCESSIVE_FAILED_ATTEMPTS = "EXCESSIVE_FAILED_ATTEMPTS",
  IP_ABUSE_DETECTED = "IP_ABUSE_DETECTED",
  PATTERN_ABUSE = "PATTERN_ABUSE",
  CAPTCHA_FAILURES = "CAPTCHA_FAILURES",
  MANUAL_ADMIN_LOCK = "MANUAL_ADMIN_LOCK",
  SECURITY_VIOLATION = "SECURITY_VIOLATION",
}

export enum CAPTCHA_REQUIREMENT_LEVEL {
  NONE = "NONE",
  BASIC = "BASIC",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
  MAXIMUM = "MAXIMUM",
}

export enum VERIFICATION_ABUSE_LEVEL {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
  SEVERE = "SEVERE",
}

export enum PROGRESSIVE_DELAY_TIER {
  TIER_1 = "TIER_1", // 5 seconds
  TIER_2 = "TIER_2", // 15 seconds
  TIER_3 = "TIER_3", // 30 seconds
  TIER_4 = "TIER_4", // 1 minute
  TIER_5 = "TIER_5", // 5 minutes
  TIER_6 = "TIER_6", // 15 minutes
  TIER_7 = "TIER_7", // 30 minutes
  TIER_8 = "TIER_8", // 1 hour
}

export enum VERIFICATION_SECURITY_ACTION {
  LOG_ATTEMPT = "LOG_ATTEMPT",
  DELAY_RESPONSE = "DELAY_RESPONSE",
  REQUIRE_CAPTCHA = "REQUIRE_CAPTCHA",
  TEMPORARY_BLOCK = "TEMPORARY_BLOCK",
  ESCALATE_SECURITY = "ESCALATE_SECURITY",
  NOTIFY_ADMIN = "NOTIFY_ADMIN",
  PERMANENT_BLOCK = "PERMANENT_BLOCK",
}

// =====================
// Verification System Enums (Unified)
// =====================

export enum VERIFICATION_STATUS {
  PENDING = "PENDING",
  SENT = "SENT",
  VERIFIED = "VERIFIED",
  EXPIRED = "EXPIRED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum VERIFICATION_METHOD {
  EMAIL = "EMAIL",
  PHONE = "PHONE",
  EMAIL_AND_PHONE = "EMAIL_AND_PHONE",
}

export enum VERIFICATION_PURPOSE {
  ACCOUNT_VERIFICATION = "ACCOUNT_VERIFICATION",
  PASSWORD_RESET = "PASSWORD_RESET",
  PHONE_VERIFICATION = "PHONE_VERIFICATION",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  TWO_FACTOR_AUTH = "TWO_FACTOR_AUTH",
  LOGIN_VERIFICATION = "LOGIN_VERIFICATION",
}

// =====================
// Email Enums
// =====================

export enum EMAIL_TYPE {
  PASSWORD_RESET = "PASSWORD_RESET",
  TEMPORARY_PASSWORD = "TEMPORARY_PASSWORD",
  ACCOUNT_VERIFICATION = "ACCOUNT_VERIFICATION",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  ACCOUNT_STATUS_CHANGE = "ACCOUNT_STATUS_CHANGE",
  WELCOME = "WELCOME",
  NOTIFICATION = "NOTIFICATION",
}

export enum EMAIL_STATUS {
  PENDING = "PENDING",
  SENT = "SENT",
  DELIVERED = "DELIVERED",
  FAILED = "FAILED",
  BOUNCED = "BOUNCED",
  CANCELLED = "CANCELLED",
}

// =====================
// Default Notification Settings
// =====================

export const DEFAULT_NOTIFICATION_SETTINGS: Record<string, { importance: string; channels: string[] }> = {
  // Activity Alerts
  [ALERT_TYPE.HIGH_SPENDING]: { importance: NOTIFICATION_IMPORTANCE.URGENT, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.UNUSUAL_PATTERN]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },
  [ALERT_TYPE.DISCREPANCY]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.LOW_STOCK]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.PUSH] },

  // Item Alerts
  [ALERT_TYPE.STOCK_OUT]: { importance: NOTIFICATION_IMPORTANCE.URGENT, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },
  [ALERT_TYPE.OVERSTOCK]: { importance: NOTIFICATION_IMPORTANCE.LOW, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.SLOW_MOVING]: { importance: NOTIFICATION_IMPORTANCE.LOW, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.REORDER_NEEDED]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },

  // User Alerts
  [ALERT_TYPE.HIGH_TURNOVER]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.ATTENDANCE_ISSUE]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },

  // Order Alerts
  [ALERT_TYPE.DELIVERY_DELAY]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP] },

  // Customer Alerts
  [ALERT_TYPE.SERVICE_ISSUE]: { importance: NOTIFICATION_IMPORTANCE.URGENT, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.PAYMENT_DELAY]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },

  // Task Alerts
  [ALERT_TYPE.OVERDUE]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.CUSTOMER_COMPLAINT]: { importance: NOTIFICATION_IMPORTANCE.URGENT, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },

  // Borrow Alerts
  [ALERT_TYPE.HIGH_DEMAND]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.USER_VIOLATION]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },

  // Warning Alerts
  [ALERT_TYPE.REPEAT_OFFENDER]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },
  [ALERT_TYPE.ESCALATION_NEEDED]: { importance: NOTIFICATION_IMPORTANCE.URGENT, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },
  [ALERT_TYPE.PATTERN_DETECTED]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },

  // PPE Alerts
  [ALERT_TYPE.STOCK_SHORTAGE]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.MISSING_DELIVERY]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP] },

  // Supplier Alerts
  [ALERT_TYPE.DELIVERY_DELAYS]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.PUSH] },
};

// =====================
// Item Notes & Documents Enums
// =====================

export enum NOTE_CATEGORY {
  GENERAL = "GENERAL",
  QUALITY = "QUALITY",
  MAINTENANCE = "MAINTENANCE",
  COMPLIANCE = "COMPLIANCE",
  SPECIFICATION = "SPECIFICATION",
  USAGE = "USAGE",
  SUPPLIER = "SUPPLIER",
  SAFETY = "SAFETY",
  OTHER = "OTHER",
}

export enum DOCUMENT_CATEGORY {
  TECHNICAL_SPEC = "TECHNICAL_SPEC",
  CERTIFICATE = "CERTIFICATE",
  MANUAL = "MANUAL",
  SAFETY_DATA = "SAFETY_DATA",
  WARRANTY = "WARRANTY",
  INVOICE = "INVOICE",
  CONTRACT = "CONTRACT",
  COMPLIANCE = "COMPLIANCE",
  PHOTO = "PHOTO",
  OTHER = "OTHER",
}

export enum LINK_TYPE {
  MANUFACTURER = "MANUFACTURER",
  DOCUMENTATION = "DOCUMENTATION",
  TUTORIAL = "TUTORIAL",
  SUPPLIER = "SUPPLIER",
  INTERNAL = "INTERNAL",
  OTHER = "OTHER",
}

// =====================
// Item Category Types
// =====================

export enum ITEM_CATEGORY_TYPE {
  REGULAR = "REGULAR",
  TOOL = "TOOL",
  PPE = "PPE",
}

// Stock math model on the Item itself (capability fields)
export enum STOCK_MODEL {
  CONSUMPTION = "CONSUMPTION",
  FIXED_TARGET = "FIXED_TARGET",
}

// Physical structure type of a warehouse location (used by the warehouse map).
export enum WAREHOUSE_LOCATION_TYPE {
  ESTANTE = "ESTANTE",
  ESTANTE_DUPLA = "ESTANTE_DUPLA",
  ESTANTE_KANBAN = "ESTANTE_KANBAN",
  PAINEL = "PAINEL",
  PALETE = "PALETE",
}

// Accounting classification (DRE bucket) for item/transaction categories.
export enum ACCOUNTING_TYPE {
  SALARIOS = "SALARIOS",
  DESPESAS_FIXAS = "DESPESAS_FIXAS",
  PRODUTIVO = "PRODUTIVO",
  IMPOSTO_TARIFAS = "IMPOSTO_TARIFAS",
  MATERIA_PRIMA = "MATERIA_PRIMA",
  INVESTIMENTO = "INVESTIMENTO",
  MANUTENCAO = "MANUTENCAO",
  PRESTACAO_SERVICO = "PRESTACAO_SERVICO",
  COZINHA_ALIMENTACAO = "COZINHA_ALIMENTACAO",
  EPI = "EPI",
  ESCRITORIO = "ESCRITORIO",
  APLICACAO_FINANCEIRA = "APLICACAO_FINANCEIRA",
  ESTORNO = "ESTORNO",
  LUCRO_DISTRIBUIDO = "LUCRO_DISTRIBUIDO",
  RECEITA_SERVICOS = "RECEITA_SERVICOS",
  EXTRAORDINARIO = "EXTRAORDINARIO",
}

// Category hierarchy depth: 1 = top-level category, 2 = subcategory.
export enum ITEM_CATEGORY_LEVEL {
  CATEGORY = 1,
  SUBCATEGORY = 2,
}

// =====================
// Financial - Expense Management
// =====================

// =====================
// Favorite Pages
// =====================

export enum FAVORITE_PAGES {
  // Production - List Pages
  PRODUCAO_AGENDA_LISTAR = "/producao/agenda",
  PRODUCAO_CRONOGRAMA_LISTAR = "/producao/cronograma",
  PRODUCAO_RECORTE_LISTAR = "/producao/recorte",
  PRODUCAO_SERVICOS_LISTAR = "/producao/servicos",
  PRODUCAO_OBSERVACOES_LISTAR = "/producao/observacoes",
  PRODUCAO_AEROGRAFIA_LISTAR = "/producao/aerografia/listar",
  PRODUCAO_GARAGENS_LISTAR = "/producao/barracoes",
  PRODUCAO_ORDENS_SERVICO_LISTAR = "/producao/ordens-de-servico",
  PRODUCAO_HISTORICO_LISTAR = "/producao/historico",

  // Production - Create Pages
  PRODUCAO_AGENDA_CADASTRAR = "/producao/agenda/cadastrar",
  PRODUCAO_CRONOGRAMA_CADASTRAR = "/producao/cronograma/cadastrar",
  PRODUCAO_RECORTE_CADASTRAR = "/producao/recorte/cadastrar",
  PRODUCAO_SERVICOS_CADASTRAR = "/producao/servicos/cadastrar",
  PRODUCAO_OBSERVACOES_CADASTRAR = "/producao/observacoes/cadastrar",
  PRODUCAO_AEROGRAFIA_CADASTRAR = "/producao/aerografia/cadastrar",
  PRODUCAO_GARAGENS_CADASTRAR = "/producao/barracoes/cadastrar",
  PRODUCAO_ORDENS_SERVICO_CADASTRAR = "/producao/ordens-de-servico/cadastrar",

  // Inventory - List Pages
  ESTOQUE_MOVIMENTACOES_LISTAR = "/estoque/movimentacoes",
  ESTOQUE_PRODUTOS_LISTAR = "/estoque/produtos",
  ESTOQUE_PRODUTOS_CATEGORIAS_LISTAR = "/estoque/produtos/categorias",
  ESTOQUE_PRODUTOS_MARCAS_LISTAR = "/estoque/produtos/marcas",
  ESTOQUE_PEDIDOS_LISTAR = "/estoque/pedidos",
  ESTOQUE_PEDIDOS_AGENDAMENTOS_LISTAR = "/estoque/pedidos/agendamentos",
  ESTOQUE_PEDIDOS_AUTOMATICOS_LISTAR = "/estoque/pedidos/automaticos",
  ESTOQUE_MANUTENCAO_LISTAR = "/estoque/manutencao/listar",
  ESTOQUE_MANUTENCAO_AGENDAMENTOS_LISTAR = "/estoque/manutencao/agendamentos",
  ESTOQUE_RETIRADAS_EXTERNAS_LISTAR = "/estoque/operacoes-externas",
  ESTOQUE_FORNECEDORES_LISTAR = "/estoque/fornecedores",
  ESTOQUE_EPI_LISTAR = "/estoque/epi",
  ESTOQUE_EPI_ENTREGAS_LISTAR = "/estoque/epi/entregas",
  ESTOQUE_EPI_AGENDAMENTOS_LISTAR = "/estoque/epi/agendamentos",
  ESTOQUE_EMPRESTIMOS_LISTAR = "/estoque/emprestimos",

  // Statistics Pages
  ESTATISTICAS = "/estatisticas",
  // Entity-Specific Statistics
  ESTATISTICAS_ESTOQUE = "/estatisticas/estoque",
  ESTOQUE_ESTATISTICAS = "/estatisticas/estoque",
  ESTOQUE_ESTATISTICAS_MOVIMENTACAO = "/estatisticas/estoque/movimentacao",
  STATISTICS_CONSUMPTION = "/estatisticas/estoque/consumo",
  ESTATISTICAS_PRODUCAO = "/estatisticas/producao",
  ESTATISTICAS_PEDIDOS = "/estatisticas/estoque/pedidos",
  ESTATISTICAS_DEPARTAMENTO_PESSOAL = "/estatisticas/departamento-pessoal",
  ESTATISTICAS_FINANCEIRO = "/estatisticas/financeiro",
  ESTATISTICAS_FINANCEIRO_COBRANCAS = "/estatisticas/financeiro/cobrancas",
  ESTATISTICAS_FINANCEIRO_BOLETOS = "/estatisticas/financeiro/boletos",
  ESTATISTICAS_FINANCEIRO_RECEITA = "/estatisticas/financeiro/receita-orcamentos",
  ESTATISTICAS_FINANCEIRO_NFSE = "/estatisticas/financeiro/nfse",
  ESTATISTICAS_FINANCEIRO_CONCILIACAO = "/estatisticas/financeiro/conciliacao",
  // Advanced Analytics
  ESTATISTICAS_ANALYTICS_PREDITIVA = "/estatisticas/analytics/preditiva",
  ESTATISTICAS_ANALYTICS_COMPARATIVA = "/estatisticas/analytics/comparativa",
  ESTATISTICAS_ANALYTICS_CORRELACAO = "/estatisticas/analytics/correlacao",
  ESTATISTICAS_ANALYTICS_COHORT = "/estatisticas/analytics/cohort",
  // Dashboards
  ESTATISTICAS_DASHBOARD_EXECUTIVO = "/estatisticas/dashboards/executivo",
  ESTATISTICAS_DASHBOARD_METAS = "/estatisticas/dashboards/metas",
  ESTATISTICAS_DASHBOARD_TEMPO_REAL = "/estatisticas/dashboards/tempo-real",
  ESTATISTICAS_DASHBOARD_EXPLORADOR = "/estatisticas/dashboards/explorador",
  // Reports
  ESTATISTICAS_RELATORIOS_CONSTRUTOR = "/estatisticas/relatorios/construtor",

  // Inventory - Create Pages
  ESTOQUE_MOVIMENTACOES_CADASTRAR = "/estoque/movimentacoes/cadastrar",
  ESTOQUE_PRODUTOS_CADASTRAR = "/estoque/produtos/cadastrar",
  ESTOQUE_PRODUTOS_CATEGORIAS_CADASTRAR = "/estoque/produtos/categorias/cadastrar",
  ESTOQUE_PRODUTOS_MARCAS_CADASTRAR = "/estoque/produtos/marcas/cadastrar",
  ESTOQUE_PEDIDOS_CADASTRAR = "/estoque/pedidos/cadastrar",
  ESTOQUE_PEDIDOS_AGENDAMENTOS_CADASTRAR = "/estoque/pedidos/agendamentos/cadastrar",
  ESTOQUE_MANUTENCAO_CADASTRAR = "/estoque/manutencao/cadastrar",
  ESTOQUE_MANUTENCAO_AGENDAMENTOS_CADASTRAR = "/estoque/manutencao/agendamentos/cadastrar",
  ESTOQUE_RETIRADAS_EXTERNAS_CADASTRAR = "/estoque/operacoes-externas/cadastrar",
  ESTOQUE_FORNECEDORES_CADASTRAR = "/estoque/fornecedores/cadastrar",
  ESTOQUE_EPI_CADASTRAR = "/estoque/epi/cadastrar",
  ESTOQUE_EPI_ENTREGAS_CADASTRAR = "/estoque/epi/entregas/cadastrar",
  ESTOQUE_EPI_AGENDAMENTOS_CADASTRAR = "/estoque/epi/agendamentos/cadastrar",
  ESTOQUE_EMPRESTIMOS_CADASTRAR = "/estoque/emprestimos/cadastrar",

  // Inventory - Edit Pages
  ESTOQUE_MANUTENCAO_AGENDAMENTOS_EDITAR = "/estoque/manutencao/agendamentos/editar/:id",

  // Painting - List Pages
  PINTURA_CATALOGO_LISTAR = "/pintura/catalogo",
  PINTURA_PRODUCOES_LISTAR = "/pintura/producoes",
  PINTURA_TIPOS_TINTA_LISTAR = "/pintura/tipos-de-tinta",
  PINTURA_FORMULAS_LISTAR = "/pintura/formulas/listar",
  PINTURA_FORMULACOES_LISTAR = "/pintura/formulacoes/listar",
  PINTURA_COMPONENTES_LISTAR = "/pintura/componentes/listar",
  PINTURA_MARCAS_TINTA_LISTAR = "/pintura/marcas-de-tinta/listar",

  // Painting - Create Pages
  PINTURA_CATALOGO_CADASTRAR = "/pintura/catalogo/cadastrar",
  PINTURA_PRODUCOES_CADASTRAR = "/pintura/producoes/cadastrar",
  PINTURA_TIPOS_TINTA_CADASTRAR = "/pintura/tipos-de-tinta/cadastrar",
  PINTURA_FORMULAS_CADASTRAR = "/pintura/formulas/cadastrar",
  PINTURA_FORMULACOES_CADASTRAR = "/pintura/formulacoes/cadastrar",
  PINTURA_COMPONENTES_CADASTRAR = "/pintura/componentes/cadastrar",
  PINTURA_MARCAS_TINTA_CADASTRAR = "/pintura/marcas-de-tinta/cadastrar",

  // Painting - Edit Pages
  PINTURA_TIPOS_TINTA_EDITAR = "/pintura/tipos-de-tinta/editar/:id",
  PINTURA_MARCAS_TINTA_EDITAR = "/pintura/marcas-de-tinta/editar/:id",

  // Administration - List Pages
  ADMINISTRACAO_CLIENTES_LISTAR = "/financeiro/clientes",
  ADMINISTRACAO_RESPONSAVEIS_LISTAR = "/financeiro/clientes/responsaveis",
  ADMINISTRACAO_COLABORADORES_LISTAR = "/departamento-pessoal/colaboradores",
  ADMINISTRACAO_ORCAMENTOS_LISTAR = "/administracao/orcamentos",
  ADMINISTRACAO_REGISTROS_ALTERACOES_LISTAR = "/administracao/registros-de-alteracoes",
  ADMINISTRACAO_ARQUIVOS_LISTAR = "/administracao/arquivos",
  ADMINISTRACAO_SETORES_LISTAR = "/administracao/setores",
  ADMINISTRACAO_METAS_LISTAR = "/administracao/metas",
  ADMINISTRACAO_NOTIFICACOES_LISTAR = "/administracao/notificacoes",
  ADMINISTRACAO_MENSAGENS_LISTAR = "/administracao/mensagens",
  ADMINISTRACAO_FOLHA_DE_PAGAMENTO = "/departamento-pessoal/folha-de-pagamento",

  // Administration - Create Pages
  ADMINISTRACAO_CLIENTES_CADASTRAR = "/financeiro/clientes/cadastrar",
  ADMINISTRACAO_COLABORADORES_CADASTRAR = "/departamento-pessoal/colaboradores/cadastrar",
  ADMINISTRACAO_ORCAMENTOS_CADASTRAR = "/administracao/orcamentos/cadastrar",
  ADMINISTRACAO_ARQUIVOS_CADASTRAR = "/administracao/arquivos/upload",
  ADMINISTRACAO_SETORES_CADASTRAR = "/administracao/setores/cadastrar",
  ADMINISTRACAO_NOTIFICACOES_CADASTRAR = "/administracao/notificacoes/cadastrar/enviar",
  ADMINISTRACAO_NOTIFICACOES_EDITAR = "/administracao/notificacoes/editar",
  ADMINISTRACAO_MENSAGENS_CRIAR = "/administracao/mensagens/criar",
  ADMINISTRACAO_MENSAGENS_EDITAR = "/administracao/mensagens/editar/:id",

  // Financeiro - Dashboard & List Pages
  FINANCEIRO_DASHBOARD = "/financeiro",
  FINANCEIRO_CLIENTES_LISTAR = "/financeiro/clientes",
  FINANCEIRO_FATURAMENTO = "/financeiro/faturamento",
  FINANCEIRO_ORCAMENTO = "/financeiro/orcamento",
  FINANCEIRO_ORCAMENTO_CADASTRAR = "/financeiro/orcamento/cadastrar",
  FINANCEIRO_CONCILIACAO_TRANSACOES = "/financeiro/conciliacao/transacoes",
  FINANCEIRO_CONCILIACAO_NOTAS = "/financeiro/conciliacao/notas",

  // Personnel Department - List Pages
  DEPARTAMENTO_PESSOAL_CARGOS_LISTAR = "/departamento-pessoal/cargos",
  DEPARTAMENTO_PESSOAL_FERIAS_LISTAR = "/departamento-pessoal/ferias",
  DEPARTAMENTO_PESSOAL_CALENDARIO = "/departamento-pessoal/calendario",
  DEPARTAMENTO_PESSOAL_FERIADOS_LISTAR = "/departamento-pessoal/feriados",
  DEPARTAMENTO_PESSOAL_AVISOS_LISTAR = "/departamento-pessoal/avisos",
  DEPARTAMENTO_PESSOAL_CALCULOS = "/departamento-pessoal/calculos",
  DEPARTAMENTO_PESSOAL_CONTROLE_PONTO_LISTAR = "/departamento-pessoal/controle-ponto",
  DEPARTAMENTO_PESSOAL_CONTROLE_PONTO_ASSINATURA_DIGITAL_LISTAR = "/departamento-pessoal/controle-ponto/assinatura-digital",
  DEPARTAMENTO_PESSOAL_EPI_ENTREGAS_LISTAR = "/medicina-do-trabalho/epi/entregas",
  DEPARTAMENTO_PESSOAL_EPI_AGENDAMENTOS_LISTAR = "/medicina-do-trabalho/epi/agendamentos",
  DEPARTAMENTO_PESSOAL_SETORES_LISTAR = "/departamento-pessoal/setores",

  // Personnel Department - Create Pages
  DEPARTAMENTO_PESSOAL_CARGOS_CADASTRAR = "/departamento-pessoal/cargos/cadastrar",
  DEPARTAMENTO_PESSOAL_FERIAS_CADASTRAR = "/departamento-pessoal/ferias/cadastrar",
  DEPARTAMENTO_PESSOAL_FERIADOS_CADASTRAR = "/departamento-pessoal/feriados/cadastrar",
  DEPARTAMENTO_PESSOAL_AVISOS_CADASTRAR = "/departamento-pessoal/avisos/cadastrar",
  DEPARTAMENTO_PESSOAL_EPI_ENTREGAS_CADASTRAR = "/medicina-do-trabalho/epi/entregas/cadastrar",
  DEPARTAMENTO_PESSOAL_EPI_AGENDAMENTOS_CADASTRAR = "/medicina-do-trabalho/epi/agendamentos/cadastrar",
  DEPARTAMENTO_PESSOAL_SETORES_CADASTRAR = "/departamento-pessoal/setores/cadastrar",
  DEPARTAMENTO_PESSOAL_BONUS_LISTAR = "/departamento-pessoal/bonus",
  DEPARTAMENTO_PESSOAL_NIVEIS_DESEMPENHO_LISTAR = "/departamento-pessoal/bonus/nivel-de-performance",

  // Personal - List Pages
  PESSOAL_FERIADOS_LISTAR = "/pessoal/feriados",
  PESSOAL_MEUS_EPIS_LISTAR = "/pessoal/meus-epis",
  PESSOAL_MEUS_EMPRESTIMOS_LISTAR = "/pessoal/meus-emprestimos",
  PESSOAL_MINHAS_ATIVIDADES_LISTAR = "/pessoal/minhas-movimentacoes",
  PESSOAL_MINHAS_ADVERTENCIAS_LISTAR = "/pessoal/minhas-advertencias",
  PESSOAL_MEUS_PONTOS = "/pessoal/meus-pontos",

  // Catalog Basic - List Pages
  CATALOGO_BASICO_LISTAR = "/pintura/catalogo-basico",

  // Server - List Pages
  SERVIDOR_USUARIOS = "/servidor/usuarios",

  // Personnel Department - Edit Pages
  DEPARTAMENTO_PESSOAL_CARGOS_EDITAR = "/departamento-pessoal/cargos/editar/:id",
  DEPARTAMENTO_PESSOAL_FERIAS_EDITAR = "/departamento-pessoal/ferias/editar/:id",
  DEPARTAMENTO_PESSOAL_FERIADOS_EDITAR = "/departamento-pessoal/feriados/editar/:id",
  DEPARTAMENTO_PESSOAL_AVISOS_EDITAR = "/departamento-pessoal/avisos/editar/:id",
  DEPARTAMENTO_PESSOAL_SETORES_EDITAR = "/departamento-pessoal/setores/editar/:id",

  // Personnel Department - Details Pages
  DEPARTAMENTO_PESSOAL_CARGOS_DETALHES = "/departamento-pessoal/cargos/detalhes/:id",
  DEPARTAMENTO_PESSOAL_FERIAS_DETALHES = "/departamento-pessoal/ferias/detalhes/:id",
  DEPARTAMENTO_PESSOAL_FERIADOS_DETALHES = "/departamento-pessoal/feriados/detalhes/:id",
  DEPARTAMENTO_PESSOAL_AVISOS_DETALHES = "/departamento-pessoal/avisos/detalhes/:id",

  // Personnel Department - Batch Edit Pages
  DEPARTAMENTO_PESSOAL_CARGOS_EDITAR_LOTE = "/departamento-pessoal/cargos/editar-lote",
  DEPARTAMENTO_PESSOAL_FERIADOS_EDITAR_LOTE = "/departamento-pessoal/feriados/editar-lote",
  DEPARTAMENTO_PESSOAL_AVISOS_EDITAR_LOTE = "/departamento-pessoal/avisos/editar-lote",

  // Personnel Department - Calendar Pages
  DEPARTAMENTO_PESSOAL_FERIADOS_CALENDARIO = "/departamento-pessoal/feriados/calendario",

  // Personnel Department - Additional Pages
  DEPARTAMENTO_PESSOAL_CARGOS_REMUNERACOES = "/departamento-pessoal/cargos/:positionId/remuneracoes",

  // Administration - Edit Pages
  ADMINISTRACAO_SETORES_EDITAR = "/administracao/setores/editar/:id",

  // Administration - Details Pages
  ADMINISTRACAO_SETORES_DETALHES = "/administracao/setores/detalhes/:id",

  // Administration - Batch Edit Pages
  ADMINISTRACAO_SETORES_EDITAR_LOTE = "/administracao/setores/editar-lote",

  // Personnel Department (Departamento Pessoal) - List Pages
  DEPARTAMENTO_PESSOAL_ADMISSOES_LISTAR = "/departamento-pessoal/admissoes",
  DEPARTAMENTO_PESSOAL_RESCISOES_LISTAR = "/departamento-pessoal/rescisoes",
  DEPARTAMENTO_PESSOAL_REAJUSTES_LISTAR = "/departamento-pessoal/reajustes",
  DEPARTAMENTO_PESSOAL_PROMOCOES_LISTAR = "/departamento-pessoal/promocoes",
  DEPARTAMENTO_PESSOAL_PROMOCOES_SIMULACAO = "/departamento-pessoal/promocoes/simulacao-de-promocoes",
  DEPARTAMENTO_PESSOAL_BENEFICIOS_LISTAR = "/departamento-pessoal/beneficios",
  DEPARTAMENTO_PESSOAL_BENEFICIOS_ADESOES_LISTAR = "/departamento-pessoal/beneficios/adesoes",

  // Occupational Health (Medicina do Trabalho) - List Pages
  MEDICINA_DO_TRABALHO_ASO_LISTAR = "/medicina-do-trabalho/aso",
  MEDICINA_DO_TRABALHO_EXAMES_PERIODICOS_LISTAR = "/medicina-do-trabalho/exames-periodicos",
  MEDICINA_DO_TRABALHO_AFASTAMENTOS_LISTAR = "/medicina-do-trabalho/afastamentos",
  MEDICINA_DO_TRABALHO_FISPQ_LISTAR = "/medicina-do-trabalho/fispq",

  // Financeiro - Contas a Pagar
  FINANCEIRO_CONTAS_A_PAGAR_LISTAR = "/financeiro/contas-a-pagar",

  // Ferramentas
  FERRAMENTAS_CUSTO_DE_FUNCIONARIO = "/ferramentas/custo-de-funcionario",
  FERRAMENTAS_NOTAS = "/ferramentas/notas",

  // Favorites coverage — list/index pages wired for the favorites button
  // Administração
  ADMINISTRACAO_NOTIFICACOES_CONFIGURACOES_LISTAR = "/administracao/notificacoes/configuracoes",
  ADMINISTRACAO_QUESTIONARIOS_LISTAR = "/administracao/questionarios",
  ADMINISTRACAO_QUESTIONARIOS_PERGUNTAS_LISTAR = "/administracao/questionarios-perguntas",
  ADMINISTRACAO_QUESTIONARIOS_TEMAS_LISTAR = "/administracao/questionarios-temas",
  ADMINISTRACAO_AVALIACAO_COMPETENCIAS_LISTAR = "/administracao/avaliacao-competencias",
  ADMINISTRACAO_COMPETENCIAS_LISTAR = "/administracao/competencias",
  ADMINISTRACAO_TOPICOS_LISTAR = "/administracao/topicos",

  // Financeiro
  FINANCEIRO_NOTAS_FISCAIS_LISTAR = "/financeiro/notas-fiscais",
  FINANCEIRO_CONTAS_A_RECEBER_LISTAR = "/financeiro/contas-a-receber",
  FINANCEIRO_CONTAS_RECORRENTES_LISTAR = "/financeiro/contas-recorrentes",

  // Departamento Pessoal
  DEPARTAMENTO_PESSOAL_REQUISICOES_LISTAR = "/departamento-pessoal/controle-ponto/requisicoes",
  DEPARTAMENTO_PESSOAL_HORARIOS_LISTAR = "/departamento-pessoal/horarios",
  DEPARTAMENTO_PESSOAL_EMPRESTIMOS_LISTAR = "/departamento-pessoal/emprestimos",

  // Estoque
  ESTOQUE_LOCALIZACOES_LISTAR = "/estoque/localizacoes",

  // Minha Equipe / Produção
  MINHA_EQUIPE = "/meu-pessoal",
  PRODUCAO_AVALIACAO_COMPETENCIAS_LISTAR = "/meu-pessoal/avaliacoes-competencias",

  // Medicina do Trabalho
  MEDICINA_DO_TRABALHO_CAT_LISTAR = "/medicina-do-trabalho/cat",

  // Perfil / Servidor / Ferramentas
  PERFIL = "/perfil",
  SERVIDOR_IMPLANTACOES_LISTAR = "/servidor/implantacoes",
  FERRAMENTAS_PALETA = "/ferramentas/paleta",
  FERRAMENTAS = "/ferramentas",

  // ===== Favorites coverage batch 2 — navigable pages previously missing the star =====

  // Departamento Pessoal — Controle de Ponto subviews
  DEPARTAMENTO_PESSOAL_CONTROLE_PONTO_COLABORADOR_LISTAR = "/departamento-pessoal/controle-ponto/colaborador",
  DEPARTAMENTO_PESSOAL_CONTROLE_PONTO_DIA_LISTAR = "/departamento-pessoal/controle-ponto/dia",
  DEPARTAMENTO_PESSOAL_CONTROLE_PONTO_EDICAO_LISTAR = "/departamento-pessoal/controle-ponto/edicao",
  DEPARTAMENTO_PESSOAL_CONTROLE_PONTO_AUSENCIAS_LISTAR = "/departamento-pessoal/controle-ponto/ausencias",
  DEPARTAMENTO_PESSOAL_CONTROLE_PONTO_FECHAMENTO_LISTAR = "/departamento-pessoal/controle-ponto/fechamento",

  // Domain root/dashboard pages
  ESTOQUE_RAIZ = "/estoque",
  ADMINISTRACAO_DASHBOARD = "/administracao",
  PINTURA_DASHBOARD = "/pintura",
  DEPARTAMENTO_PESSOAL_RAIZ = "/departamento-pessoal",
  PESSOAL_INICIO = "/pessoal",
  SERVIDOR_INICIO = "/servidor",

  // Produção
  PRODUCAO_CALENDARIO = "/producao/calendario",
  ESTATISTICAS_PRODUCAO_PRODUTIVIDADE = "/estatisticas/producao/produtividade",
  ESTATISTICAS_PRODUCAO_DESEMPENHO = "/estatisticas/producao/desempenho",
  ESTATISTICAS_PRODUCAO_GARGALOS = "/estatisticas/producao/gargalos",
  ESTATISTICAS_PRODUCAO_VALOR_BONUS = "/estatisticas/producao/valor-bonus",

  // Departamento Pessoal — bonus/cargos/integrações/cadastros + estatísticas
  DEPARTAMENTO_PESSOAL_BONUS_SIMULACAO = "/departamento-pessoal/bonus/simulacao-de-bonus",
  DEPARTAMENTO_PESSOAL_CARGOS_HIERARQUIA = "/departamento-pessoal/cargos/hierarquia",
  DEPARTAMENTO_PESSOAL_INTEGRACAO_SECULLUM = "/departamento-pessoal/integracoes/secullum",
  DEPARTAMENTO_PESSOAL_RESCISOES_CADASTRAR = "/departamento-pessoal/rescisoes/cadastrar",
  DEPARTAMENTO_PESSOAL_BENEFICIOS_CADASTRAR = "/departamento-pessoal/beneficios/cadastrar",
  DEPARTAMENTO_PESSOAL_BENEFICIOS_ADESOES_CADASTRAR = "/departamento-pessoal/beneficios/adesoes/cadastrar",
  ESTATISTICAS_DP_FOLHA = "/estatisticas/departamento-pessoal/folha",
  ESTATISTICAS_DP_CUSTO_FOLHA = "/estatisticas/departamento-pessoal/custo-folha",
  ESTATISTICAS_DP_EQUIPE = "/estatisticas/departamento-pessoal/equipe",
  ESTATISTICAS_DP_FALTAS = "/estatisticas/departamento-pessoal/faltas",
  ESTATISTICAS_DP_COMPETENCIAS = "/estatisticas/departamento-pessoal/competencias",

  // Financeiro
  FINANCEIRO_CONCILIACAO_EXTRATO = "/financeiro/conciliacao/extrato",
  FINANCEIRO_CONCILIACAO_CATEGORIAS = "/financeiro/conciliacao/categorias",
  FINANCEIRO_CONTAS_RECORRENTES_CADASTRAR = "/financeiro/contas-recorrentes/cadastrar",

  // Medicina do Trabalho — cadastros
  MEDICINA_DO_TRABALHO_ASO_CADASTRAR = "/medicina-do-trabalho/aso/cadastrar",
  MEDICINA_DO_TRABALHO_AFASTAMENTOS_CADASTRAR = "/medicina-do-trabalho/afastamentos/cadastrar",
  MEDICINA_DO_TRABALHO_FISPQ_CADASTRAR = "/medicina-do-trabalho/fispq/cadastrar",
  MEDICINA_DO_TRABALHO_CAT_CADASTRAR = "/medicina-do-trabalho/cat/cadastrar",

  // Pessoal
  PESSOAL_MENSAGENS_LISTAR = "/pessoal/mensagens",
  PESSOAL_ADVERTENCIAS_LISTAR = "/pessoal/advertencias",

  // Minha Equipe
  MINHA_EQUIPE_MEMBROS_LISTAR = "/meu-pessoal/usuarios",
  MINHA_EQUIPE_EMPRESTIMOS_LISTAR = "/meu-pessoal/emprestimos",
  MINHA_EQUIPE_ADVERTENCIAS_LISTAR = "/meu-pessoal/advertencias",
  MINHA_EQUIPE_EPIS_LISTAR = "/meu-pessoal/epis",
  MINHA_EQUIPE_MOVIMENTACOES_LISTAR = "/meu-pessoal/movimentacoes",
  MINHA_EQUIPE_CONTROLE_PONTO_LISTAR = "/meu-pessoal/calculos",

  // Ferramentas
  FERRAMENTAS_QR_CODE = "/ferramentas/qr-code",
  FERRAMENTAS_CALCULADORA_MISTURA = "/ferramentas/calculadora-de-mistura",
  FERRAMENTAS_CALCULADORA_HORAS = "/ferramentas/calculadora-de-horas",
  FERRAMENTAS_CUSTO_HORAS_EXTRAS = "/ferramentas/custo-horas-extras",
  FERRAMENTAS_CERTIFICADO_RESIDUOS = "/ferramentas/certificado-residuos",

  // Servidor
  SERVIDOR_BACKUP = "/servidor/backup",
  SERVIDOR_SINCRONIZACAO_BD = "/servidor/sincronizacao-bd",
  SERVIDOR_GERENCIADOR_ARQUIVOS = "/servidor/gerenciador-de-arquivos",
  SERVIDOR_LOGS = "/servidor/logs",
  SERVIDOR_METRICAS = "/servidor/metricas",
  SERVIDOR_SERVICOS = "/servidor/servicos",
  SERVIDOR_REGISTROS_ALTERACOES_LISTAR = "/servidor/registros-de-alteracoes",

  // Perfil
  PERFIL_NOTIFICACOES = "/perfil/notificacoes",

  // Administração
  ADMINISTRACAO_APLICATIVOS_LISTAR = "/administracao/aplicativos",
}

export enum MEASURE_SIDE {
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  BACK = "BACK",
}

// =====================
// Bonus & Payroll Enums
// =====================

export enum BONUS_DISCOUNT_REASON {
  ABSENCE = "ABSENCE",
  LATE_DELIVERY = "LATE_DELIVERY",
  QUALITY_ISSUE = "QUALITY_ISSUE",
  DISCIPLINARY = "DISCIPLINARY",
  OTHER = "OTHER",
}

export enum BONUS_STATUS {
  DRAFT = "DRAFT",
  CONFIRMED = "CONFIRMED",
}

export enum BONIFICATION_STATUS {
  NO_BONIFICATION = "NO_BONIFICATION",
  PARTIAL_BONIFICATION = "PARTIAL_BONIFICATION",
  FULL_BONIFICATION = "FULL_BONIFICATION",
  SUSPENDED_BONIFICATION = "SUSPENDED_BONIFICATION",
}


export enum DISCOUNT_TYPE {
  NONE = "NONE",
  PERCENTAGE = "PERCENTAGE",
  FIXED_VALUE = "FIXED_VALUE",
}

export enum RESPONSIBLE_ROLE {
  COMMERCIAL = "COMMERCIAL",
  OWNER = "OWNER",
  SELLER = "SELLER",
  REPRESENTATIVE = "REPRESENTATIVE",
  COORDINATOR = "COORDINATOR",
  MARKETING = "MARKETING",
  FINANCIAL = "FINANCIAL",
  FLEET_MANAGER = "FLEET_MANAGER",
  DRIVER = "DRIVER",
}

// Payment condition enum - controls payment structure
export enum PAYMENT_CONDITION {
  CASH_5 = "CASH_5",
  CASH_40 = "CASH_40",
  INSTALLMENTS_2 = "INSTALLMENTS_2",
  INSTALLMENTS_3 = "INSTALLMENTS_3",
  INSTALLMENTS_4 = "INSTALLMENTS_4",
  INSTALLMENTS_5 = "INSTALLMENTS_5",
  INSTALLMENTS_6 = "INSTALLMENTS_6",
  INSTALLMENTS_7 = "INSTALLMENTS_7",
  CUSTOM = "CUSTOM",
}

// Guarantee years options
export const GUARANTEE_YEARS_OPTIONS = [5, 10, 15] as const;

export enum PAYROLL_STATUS {
  DRAFT = "DRAFT",
  FINALIZED = "FINALIZED",
}

export enum PAYROLL_MONTH {
  JANUARY = "JANUARY",
  FEBRUARY = "FEBRUARY",
  MARCH = "MARCH",
  APRIL = "APRIL",
  MAY = "MAY",
  JUNE = "JUNE",
  JULY = "JULY",
  AUGUST = "AUGUST",
  SEPTEMBER = "SEPTEMBER",
  OCTOBER = "OCTOBER",
  NOVEMBER = "NOVEMBER",
  DECEMBER = "DECEMBER",
}

// =====================
// Task Quote Enums
// =====================

export enum TASK_QUOTE_STATUS {
  PENDING = "PENDING",
  BUDGET_APPROVED = "BUDGET_APPROVED",
  BILLING_APPROVED = "BILLING_APPROVED",
  UPCOMING = "UPCOMING",
  DUE = "DUE",
  PARTIAL = "PARTIAL",
  SETTLED = "SETTLED",
  CANCELLED = "CANCELLED",
}

// =====================
// Invoice / Billing Enums
// =====================

export enum INVOICE_STATUS {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  PARTIALLY_PAID = "PARTIALLY_PAID",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
}

export enum INSTALLMENT_STATUS {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  PAID = "PAID",
  OVERDUE = "OVERDUE",
  CANCELLED = "CANCELLED",
}

export enum BANK_SLIP_STATUS {
  CREATING = "CREATING",
  REGISTERING = "REGISTERING",
  ACTIVE = "ACTIVE",
  OVERDUE = "OVERDUE",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
  REJECTED = "REJECTED",
  ERROR = "ERROR",
}

export enum BANK_SLIP_TYPE {
  NORMAL = "NORMAL",
  HIBRIDO = "HIBRIDO",
}

export enum NFSE_STATUS {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  AUTHORIZED = "AUTHORIZED",
  CANCEL_REQUESTED = "CANCEL_REQUESTED",
  CANCEL_REJECTED = "CANCEL_REJECTED",
  CANCELLED = "CANCELLED",
  ERROR = "ERROR",
}

// =====================
// Deployment Enums
// =====================

export enum DEPLOYMENT_ENVIRONMENT {
  DEVELOPMENT = "DEVELOPMENT",
  STAGING = "STAGING",
  PRODUCTION = "PRODUCTION",
}

export enum DEPLOYMENT_APPLICATION {
  API = "API",
  WEB = "WEB",
  MOBILE = "MOBILE",
}

export enum DEPLOYMENT_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  BUILDING = "BUILDING",
  TESTING = "TESTING",
  DEPLOYING = "DEPLOYING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ROLLED_BACK = "ROLLED_BACK",
  CANCELLED = "CANCELLED",
}

export enum DEPLOYMENT_TRIGGER {
  MANUAL = "MANUAL",
  AUTO = "AUTO",
  PUSH = "PUSH",
  PULL_REQUEST = "PULL_REQUEST",
  TAG = "TAG",
  SCHEDULE = "SCHEDULE",
  WEBHOOK = "WEBHOOK",
  ROLLBACK = "ROLLBACK",
  API = "API",
}

// Aliases for Prisma compatibility
export { DEPLOYMENT_ENVIRONMENT as DeploymentEnvironment };
export { DEPLOYMENT_APPLICATION as DeploymentApplication };
export { DEPLOYMENT_STATUS as DeploymentStatus };
export { DEPLOYMENT_TRIGGER as DeploymentTrigger };

// =====================
// Skill Assessment Enums (mirror Prisma enums)
// =====================
//
// Note: SKILL_AREA was removed. A Skill IS the area — the parallel enum was
// redundant. Grouping/filtering now uses skillId / skill.name directly.

export enum ASSESSMENT_STATUS {
  DRAFT = "DRAFT",
  OPEN = "OPEN",
  CLOSED = "CLOSED",
  CANCELLED = "CANCELLED",
}

export enum ASSESSMENT_ENTRY_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  SUBMITTED = "SUBMITTED",
}

export const ASSESSMENT_STATUS_LABELS: Record<ASSESSMENT_STATUS, string> = {
  [ASSESSMENT_STATUS.DRAFT]: "Rascunho",
  [ASSESSMENT_STATUS.OPEN]: "Aberta",
  [ASSESSMENT_STATUS.CLOSED]: "Fechada",
  [ASSESSMENT_STATUS.CANCELLED]: "Cancelada",
};

export const ASSESSMENT_ENTRY_STATUS_LABELS: Record<ASSESSMENT_ENTRY_STATUS, string> = {
  [ASSESSMENT_ENTRY_STATUS.PENDING]: "Pendente",
  [ASSESSMENT_ENTRY_STATUS.IN_PROGRESS]: "Em andamento",
  [ASSESSMENT_ENTRY_STATUS.SUBMITTED]: "Enviada",
};

// Questionnaire (self-fill) — mirrors the assessment status enums.
export enum QUESTIONNAIRE_STATUS {
  DRAFT = "DRAFT",
  OPEN = "OPEN",
  CLOSED = "CLOSED",
  CANCELLED = "CANCELLED",
}

export enum QUESTIONNAIRE_ENTRY_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  SUBMITTED = "SUBMITTED",
}

export const QUESTIONNAIRE_STATUS_LABELS: Record<QUESTIONNAIRE_STATUS, string> = {
  [QUESTIONNAIRE_STATUS.DRAFT]: "Rascunho",
  [QUESTIONNAIRE_STATUS.OPEN]: "Aberto",
  [QUESTIONNAIRE_STATUS.CLOSED]: "Fechado",
  [QUESTIONNAIRE_STATUS.CANCELLED]: "Cancelado",
};

export const QUESTIONNAIRE_ENTRY_STATUS_LABELS: Record<QUESTIONNAIRE_ENTRY_STATUS, string> = {
  [QUESTIONNAIRE_ENTRY_STATUS.PENDING]: "Pendente",
  [QUESTIONNAIRE_ENTRY_STATUS.IN_PROGRESS]: "Em andamento",
  [QUESTIONNAIRE_ENTRY_STATUS.SUBMITTED]: "Enviado",
};
