// packages/interfaces/src/enums.ts

export type ORDER_BY_DIRECTION = "asc" | "desc";

// =====================
// Status Enums
// =====================

// =====================
// ABC/XYZ Analysis Categories
// =====================

export enum ABC_CATEGORY {
  A = "A",
  B = "B",
  C = "C",
}

export enum XYZ_CATEGORY {
  X = "X",
  Y = "Y",
  Z = "Z",
}

export enum ORDER_STATUS {
  CREATED = "CREATED",
  PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED",
  FULFILLED = "FULFILLED",
  OVERDUE = "OVERDUE",
  PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED",
  RECEIVED = "RECEIVED",
  CANCELLED = "CANCELLED",
}

export enum SECTOR_PRIVILEGES {
  BASIC = "BASIC",
  MAINTENANCE = "MAINTENANCE",
  WAREHOUSE = "WAREHOUSE",
  ADMIN = "ADMIN",
  PRODUCTION = "PRODUCTION",
  LEADER = "LEADER",
  HUMAN_RESOURCES = "HUMAN_RESOURCES",
  EXTERNAL = "EXTERNAL",
  FINANCIAL = "FINANCIAL",
}

export enum USER_STATUS {
  EXPERIENCE_PERIOD_1 = "EXPERIENCE_PERIOD_1",
  EXPERIENCE_PERIOD_2 = "EXPERIENCE_PERIOD_2",
  CONTRACTED = "CONTRACTED",
  DISMISSED = "DISMISSED",
}

// Helper constants for common user status queries
export const ACTIVE_USER_STATUSES = [
  USER_STATUS.EXPERIENCE_PERIOD_1,
  USER_STATUS.EXPERIENCE_PERIOD_2,
  USER_STATUS.CONTRACTED,
] as const;

export enum TASK_STATUS {
  PENDING = "PENDING",
  IN_PRODUCTION = "IN_PRODUCTION",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  ON_HOLD = "ON_HOLD",
}

export enum SERVICE_ORDER_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum AIRBRUSHING_STATUS {
  PENDING = "PENDING",
  IN_PRODUCTION = "IN_PRODUCTION",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum CUT_TYPE {
  VINYL = "VINYL",
  STENCIL = "STENCIL",
}

export enum CUT_STATUS {
  PENDING = "PENDING",
  CUTTING = "CUTTING",
  COMPLETED = "COMPLETED",
}

export enum CUT_ORIGIN {
  PLAN = "PLAN",
  REQUEST = "REQUEST",
}

export enum CUT_REQUEST_REASON {
  WRONG_APPLY = "WRONG_APPLY",
  LOST = "LOST",
  WRONG = "WRONG",
}

export enum GARAGE_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  MAINTENANCE = "MAINTENANCE",
}

export enum VACATION_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
}


export enum PPE_REQUEST_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}

export enum PPE_DELIVERY_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  DELIVERED = "DELIVERED",
  REPROVED = "REPROVED",
  CANCELLED = "CANCELLED",
}

export enum ASSIGNMENT_TYPE {
  ALL = "ALL",
  ALL_EXCEPT = "ALL_EXCEPT",
  SPECIFIC = "SPECIFIC",
}

export enum BORROW_STATUS {
  ACTIVE = "ACTIVE",
  RETURNED = "RETURNED",
  LOST = "LOST",
}

export enum EXTERNAL_WITHDRAWAL_STATUS {
  PENDING = "PENDING",
  PARTIALLY_RETURNED = "PARTIALLY_RETURNED",
  FULLY_RETURNED = "FULLY_RETURNED",
  CHARGED = "CHARGED",
  CANCELLED = "CANCELLED",
}

// =====================
// Analytics & Trends
// =====================

export enum TREND_DIRECTION {
  UP = "UP",
  DOWN = "DOWN",
  STABLE = "STABLE",
}

export enum TREND_TYPE {
  POSITIVE = "POSITIVE",
  NEGATIVE = "NEGATIVE",
  NEUTRAL = "NEUTRAL",
  VOLATILE = "VOLATILE",
  SEASONAL = "SEASONAL",
}

export enum PERIOD_TYPE {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  YEARLY = "YEARLY",
}

// =====================
// Chart Types
// =====================

export enum CHART_TYPE {
  PIE = "PIE",
  DONUT = "DONUT",
  AREA = "AREA",
  BAR = "BAR",
  LINE = "LINE",
  STACKED = "STACKED",
}

export enum COLOR_PALETTE {
  BLACK = "BLACK",
  GRAY = "GRAY",
  WHITE = "WHITE",
  SILVER = "SILVER",
  GOLDEN = "GOLDEN",
  YELLOW = "YELLOW",
  ORANGE = "ORANGE",
  BROWN = "BROWN",
  RED = "RED",
  PINK = "PINK",
  PURPLE = "PURPLE",
  BLUE = "BLUE",
  GREEN = "GREEN",
  BEIGE = "BEIGE",
}

// =====================
// Statistics & Analytics Enums
// =====================

export enum STATISTICS_GROUP_BY {
  SECTOR = "SECTOR",
  USER = "USER",
  CATEGORY = "CATEGORY",
  BRAND = "BRAND",
  SUPPLIER = "SUPPLIER",
  ITEM = "ITEM",
  DATE = "DATE",
  ACTIVITY_REASON = "ACTIVITY_REASON",
  ACTIVITY_OPERATION = "ACTIVITY_OPERATION",
}

export enum STATISTICS_METRIC {
  QUANTITY = "QUANTITY",
  TOTAL_PRICE = "TOTAL_PRICE",
  UNIT_PRICE = "UNIT_PRICE",
  COUNT = "COUNT",
  FREQUENCY = "FREQUENCY",
  PERCENTAGE = "PERCENTAGE",
  AVERAGE = "AVERAGE",
  SUM = "SUM",
  MIN = "MIN",
  MAX = "MAX",
}

export enum STATISTICS_PERIOD {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  YEARLY = "YEARLY",
  CUSTOM = "CUSTOM",
  LAST_7_DAYS = "LAST_7_DAYS",
  LAST_30_DAYS = "LAST_30_DAYS",
  LAST_90_DAYS = "LAST_90_DAYS",
  LAST_YEAR = "LAST_YEAR",
  THIS_WEEK = "THIS_WEEK",
  THIS_MONTH = "THIS_MONTH",
  THIS_QUARTER = "THIS_QUARTER",
  THIS_YEAR = "THIS_YEAR",
}

// =====================
// Priority & Risk Levels
// =====================

export enum PRIORITY_TYPE {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum RISK_LEVEL {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum STOCK_LEVEL {
  NEGATIVE_STOCK = "NEGATIVE_STOCK",
  OUT_OF_STOCK = "OUT_OF_STOCK",
  CRITICAL = "CRITICAL",
  LOW = "LOW",
  OPTIMAL = "OPTIMAL",
  OVERSTOCKED = "OVERSTOCKED",
}

export enum HEALTH_STATUS {
  EXCELLENT = "EXCELLENT",
  GOOD = "GOOD",
  FAIR = "FAIR",
  POOR = "POOR",
  CRITICAL = "CRITICAL",
}

export enum PERFORMANCE_LEVEL {
  EXCELLENT = "EXCELLENT",
  GOOD = "GOOD",
  FAIR = "FAIR",
  POOR = "POOR",
}

export enum URGENCY_LEVEL {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum EFFORT_LEVEL {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

export enum CONFIDENCE_LEVEL {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
}

// =====================
// Adjustment Types
// =====================

export enum PERCENTAGE_ADJUST_TYPE {
  INCREASE = "INCREASE",
  DECREASE = "DECREASE",
}

// =====================
// Export & Import
// =====================

export enum EXPORT_FORMAT {
  CSV = "CSV",
  EXCEL = "EXCEL",
  PDF = "PDF",
  JSON = "JSON",
}

// =====================
// Validation & Batch Operations
// =====================

export enum BATCH_OPERATION_STATUS {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  PARTIAL = "PARTIAL",
}

export enum VALIDATION_SEVERITY {
  ERROR = "ERROR",
  WARNING = "WARNING",
  INFO = "INFO",
}

// =====================
// Vacation & Leave Types
// =====================

export enum VACATION_TYPE {
  ANNUAL = "ANNUAL",
  COLLECTIVE = "COLLECTIVE",
  MEDICAL = "MEDICAL",
  MATERNITY = "MATERNITY",
  PATERNITY = "PATERNITY",
  EMERGENCY = "EMERGENCY",
  STUDY = "STUDY",
  UNPAID = "UNPAID",
  OTHER = "OTHER",
}

// =====================
// Warning Types
// =====================

export enum WARNING_SEVERITY {
  VERBAL = "VERBAL",
  WRITTEN = "WRITTEN",
  SUSPENSION = "SUSPENSION",
  FINAL_WARNING = "FINAL_WARNING",
}

export enum WARNING_CATEGORY {
  SAFETY = "SAFETY",
  MISCONDUCT = "MISCONDUCT",
  INSUBORDINATION = "INSUBORDINATION",
  POLICY_VIOLATION = "POLICY_VIOLATION",
  ATTENDANCE = "ATTENDANCE",
  PERFORMANCE = "PERFORMANCE",
  BEHAVIOR = "BEHAVIOR",
  OTHER = "OTHER",
}

// =====================
// Calendar Types
// =====================

export enum WEEK_DAY {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY",
}

// Alias for Prisma compatibility
export { WEEK_DAY as DAY_OF_WEEK };

export enum MONTH {
  JANUARY = "JANUARY",
  FEBRUARY = "FEBRUARY",
  MARCH = "MARCH",
  APRIL = "APRIL",
  MAY = "MAY",
  JUNE = "JUNE",
  JULY = "JULY",
  AUGUST = "AUGUST",
  SEPTEMBER = "SEPTEMBER",
  OCTOBER = "OCTOBER",
  NOVEMBER = "NOVEMBER",
  DECEMBER = "DECEMBER",
}

export enum MONTH_OCCURRENCE {
  FIRST = "FIRST",
  SECOND = "SECOND",
  THIRD = "THIRD",
  FOURTH = "FOURTH",
  LAST = "LAST",
}

export enum SCHEDULE_FREQUENCY {
  ONCE = "ONCE",
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  BIWEEKLY = "BIWEEKLY",
  MONTHLY = "MONTHLY",
  BIMONTHLY = "BIMONTHLY",
  QUARTERLY = "QUARTERLY",
  TRIANNUAL = "TRIANNUAL",
  QUADRIMESTRAL = "QUADRIMESTRAL",
  SEMI_ANNUAL = "SEMI_ANNUAL",
  ANNUAL = "ANNUAL",
  CUSTOM = "CUSTOM",
}

// =====================
// Size Types
// =====================

export enum PANTS_SIZE {
  SIZE_36 = "SIZE_36",
  SIZE_38 = "SIZE_38",
  SIZE_40 = "SIZE_40",
  SIZE_42 = "SIZE_42",
  SIZE_44 = "SIZE_44",
  SIZE_46 = "SIZE_46",
  SIZE_48 = "SIZE_48",
}

export enum SHIRT_SIZE {
  P = "P",
  M = "M",
  G = "G",
  GG = "GG",
  XG = "XG",
}

export enum BOOT_SIZE {
  SIZE_36 = "SIZE_36",
  SIZE_38 = "SIZE_38",
  SIZE_40 = "SIZE_40",
  SIZE_42 = "SIZE_42",
  SIZE_44 = "SIZE_44",
  SIZE_46 = "SIZE_46",
  SIZE_48 = "SIZE_48",
}

export enum SLEEVES_SIZE {
  P = "P",
  M = "M",
  G = "G",
  GG = "GG",
  XG = "XG",
}

export enum MASK_SIZE {
  P = "P",
  M = "M",
}

export enum GLOVES_SIZE {
  P = "P",
  M = "M",
  G = "G",
}

export enum RAIN_BOOTS_SIZE {
  SIZE_36 = "SIZE_36",
  SIZE_38 = "SIZE_38",
  SIZE_40 = "SIZE_40",
  SIZE_42 = "SIZE_42",
  SIZE_44 = "SIZE_44",
  SIZE_46 = "SIZE_46",
}

// =====================
// Unified PPE Size Enum
// =====================

export enum PPE_SIZE {
  // Shirt, Manguito, Mask, and Gloves sizes
  P = "P",
  M = "M",
  G = "G",
  GG = "GG",
  XG = "XG",

  // Pants and Boots sizes
  SIZE_36 = "SIZE_36",
  SIZE_38 = "SIZE_38",
  SIZE_40 = "SIZE_40",
  SIZE_42 = "SIZE_42",
  SIZE_44 = "SIZE_44",
  SIZE_46 = "SIZE_46",
  SIZE_48 = "SIZE_48",
}

// Alias for Prisma compatibility
export { PPE_SIZE as PPE_SIZE_ENUM };

export enum MEASURE_UNIT {
  // Weight units
  KILOGRAM = "KILOGRAM",
  GRAM = "GRAM",

  // Volume units
  MILLILITER = "MILLILITER",
  LITER = "LITER",
  CUBIC_METER = "CUBIC_METER",
  CUBIC_CENTIMETER = "CUBIC_CENTIMETER",

  // Length units
  MILLIMETER = "MILLIMETER",
  CENTIMETER = "CENTIMETER",
  METER = "METER",
  INCHES = "INCHES",

  // Diameter units (fractional inches)
  INCH_1_8 = "INCH_1_8",
  INCH_1_4 = "INCH_1_4",
  INCH_3_8 = "INCH_3_8",
  INCH_1_2 = "INCH_1_2",
  INCH_5_8 = "INCH_5_8",
  INCH_3_4 = "INCH_3_4",
  INCH_7_8 = "INCH_7_8",
  INCH_1 = "INCH_1",
  INCH_1_1_4 = "INCH_1_1_4",
  INCH_1_1_2 = "INCH_1_1_2",
  INCH_2 = "INCH_2",

  // Thread pitch units
  THREAD_MM = "THREAD_MM",
  THREAD_TPI = "THREAD_TPI",

  // Electrical units
  WATT = "WATT",
  VOLT = "VOLT",
  AMPERE = "AMPERE",

  // Area units
  SQUARE_CENTIMETER = "SQUARE_CENTIMETER",
  SQUARE_METER = "SQUARE_METER",

  // Count and packaging units
  UNIT = "UNIT",
  PAIR = "PAIR",
  DOZEN = "DOZEN",
  HUNDRED = "HUNDRED",
  THOUSAND = "THOUSAND",

  // Container and packaging units
  PACKAGE = "PACKAGE",
  BOX = "BOX",
  ROLL = "ROLL",
  SHEET = "SHEET",
  SET = "SET",
  SACK = "SACK",

  // PPE Size units (letter sizes)
  P = "P",
  M = "M",
  G = "G",
  GG = "GG",
  XG = "XG",
}

export enum MEASURE_TYPE {
  WEIGHT = "WEIGHT",
  VOLUME = "VOLUME",
  LENGTH = "LENGTH",
  AREA = "AREA",
  COUNT = "COUNT",
  DIAMETER = "DIAMETER",
  THREAD = "THREAD",
  ELECTRICAL = "ELECTRICAL",
  SIZE = "SIZE",
}

// =====================
// Paint Types
// =====================

// PAINT_TYPE is now a model instead of enum
// Paint types are managed dynamically in the database

export enum PAINT_TYPE_ENUM {
  POLYESTER = "POLYESTER",
  ACRYLIC = "ACRYLIC",
  LACQUER = "LACQUER",
  POLYURETHANE = "POLYURETHANE",
  EPOXY = "EPOXY",
}

export enum PAINT_BRAND_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum PAINT_BRAND {
  PPG = "PPG",
  FARBEN = "FARBEN",
  LAZZURIL = "LAZZURIL",
}

export enum PAINT_FINISH {
  SOLID = "SOLID",
  METALLIC = "METALLIC",
  PEARL = "PEARL",
  MATTE = "MATTE",
  SATIN = "SATIN",
}

// Paint base relationships are now handled via PaintGround model
export enum PAINT_BASE_TYPE {
  TRANSPARENT = "TRANSPARENT",
  WHITE = "WHITE",
  ALUMINUM = "ALUMINUM",
  BLACK = "BLACK",
  MIXING = "MIXING",
}

export enum TRUCK_MANUFACTURER {
  SCANIA = "SCANIA",
  VOLVO = "VOLVO",
  DAF = "DAF",
  VOLKSWAGEN = "VOLKSWAGEN",
  IVECO = "IVECO",
  MERCEDES_BENZ = "MERCEDES_BENZ",
}

// =====================
// Fleet & Fuel Management
// =====================

// =====================
// Operations & Actions
// =====================

export enum ACTIVITY_OPERATION {
  INBOUND = "INBOUND",
  OUTBOUND = "OUTBOUND",
}

export enum AUDIT_ACTION {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
}

export enum ENTITY_TYPE {
  ACTIVITY = "ACTIVITY",
  AIRBRUSHING = "AIRBRUSHING",
  BONUS = "BONUS",
  BORROW = "BORROW",
  CATEGORY = "CATEGORY",
  COLLECTION = "COLLECTION",
  COMMISSION = "COMMISSION",
  CUT = "CUT",
  CUT_ITEM = "CUT_ITEM",
  CUT_PLAN = "CUT_PLAN",
  CUT_REQUEST = "CUT_REQUEST",
  CUSTOMER = "CUSTOMER",
  DASHBOARD = "DASHBOARD",
  DEPLOYMENT = "DEPLOYMENT",
  DELIVERY = "DELIVERY",
  DISCOUNT = "DISCOUNT",
  PPE_CONFIG = "PPE_CONFIG",
  PPE_DELIVERY = "PPE_DELIVERY",
  PPE_REQUEST = "PPE_REQUEST",
  PPE_DELIVERY_SCHEDULE = "PPE_DELIVERY_SCHEDULE",
  PPE_SIZE = "PPE_SIZE",
  EXTERNAL_WITHDRAWAL = "EXTERNAL_WITHDRAWAL",
  EXTERNAL_WITHDRAWAL_ITEM = "EXTERNAL_WITHDRAWAL_ITEM",
  FILE = "FILE",
  FUEL = "FUEL",
  GARAGE = "GARAGE",
  GARAGE_LANE = "GARAGE_LANE",
  HOLIDAY = "HOLIDAY",
  ITEM = "ITEM",
  ITEM_BRAND = "ITEM_BRAND",
  ITEM_CATEGORY = "ITEM_CATEGORY",
  LAYOUT = "LAYOUT",
  MAINTENANCE = "MAINTENANCE",
  MAINTENANCE_ITEM = "MAINTENANCE_ITEM",
  MAINTENANCE_SCHEDULE = "MAINTENANCE_SCHEDULE",
  MEASURE = "MEASURE",
  NOTIFICATION = "NOTIFICATION",
  NOTIFICATION_PREFERENCE = "NOTIFICATION_PREFERENCE",
  OBSERVATION = "OBSERVATION",
  ORDER = "ORDER",
  ORDER_ITEM = "ORDER_ITEM",
  ORDER_RULE = "ORDER_RULE",
  ORDER_SCHEDULE = "ORDER_SCHEDULE",
  PAINT = "PAINT",
  PAINT_TYPE = "PAINT_TYPE",
  PAINT_BRAND = "PAINT_BRAND",
  PAINT_GROUND = "PAINT_GROUND",
  PAINT_FORMULA = "PAINT_FORMULA",
  PAINT_FORMULA_COMPONENT = "PAINT_FORMULA_COMPONENT",
  PAINT_PRODUCTION = "PAINT_PRODUCTION",
  PARKING_SPOT = "PARKING_SPOT",
  PAYROLL = "PAYROLL",
  PIECE = "PIECE",
  POSITION = "POSITION",
  POSITION_REMUNERATION = "POSITION_REMUNERATION",
  PREFERENCES = "PREFERENCES",
  PRICE = "PRICE",
  PRODUCTION = "PRODUCTION",
  PURCHASE = "PURCHASE",
  WARNING = "WARNING",
  SECTOR = "SECTOR",
  SEEN_NOTIFICATION = "SEEN_NOTIFICATION",
  SERVICE = "SERVICE",
  SERVICE_ORDER = "SERVICE_ORDER",
  SUPPLIER = "SUPPLIER",
  TASK = "TASK",
  TIME_CLOCK_ENTRY = "TIME_CLOCK_ENTRY",
  TRUCK = "TRUCK",
  USER = "USER",
  VACATION = "VACATION",
  VERIFICATION = "VERIFICATION",
}

export enum CHANGE_ACTION {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  RESTORE = "RESTORE",
  ROLLBACK = "ROLLBACK",
  ARCHIVE = "ARCHIVE",
  UNARCHIVE = "UNARCHIVE",
  ACTIVATE = "ACTIVATE",
  DEACTIVATE = "DEACTIVATE",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  CANCEL = "CANCEL",
  COMPLETE = "COMPLETE",
  RESCHEDULE = "RESCHEDULE",
  BATCH_CREATE = "BATCH_CREATE",
  BATCH_UPDATE = "BATCH_UPDATE",
  BATCH_DELETE = "BATCH_DELETE",
  VIEW = "VIEW",
}

export enum CHANGE_TRIGGERED_BY {
  TASK_CREATE = "TASK_CREATE",
  TASK_UPDATE = "TASK_UPDATE",
  ITEM_UPDATE = "ITEM_UPDATE",
  USER_ACTION = "USER_ACTION",
  BATCH_CREATE = "BATCH_CREATE",
  BATCH_UPDATE = "BATCH_UPDATE",
  BATCH_DELETE = "BATCH_DELETE",
  BATCH_OPERATION = "BATCH_OPERATION",
  SYSTEM = "SYSTEM",
  SYSTEM_GENERATED = "SYSTEM_GENERATED",
  USER = "USER",
  EXTERNAL_WITHDRAWAL = "EXTERNAL_WITHDRAWAL",
  EXTERNAL_WITHDRAWAL_DELETE = "EXTERNAL_WITHDRAWAL_DELETE",
  EXTERNAL_WITHDRAWAL_RETURN = "EXTERNAL_WITHDRAWAL_RETURN",
  EXTERNAL_WITHDRAWAL_ITEM = "EXTERNAL_WITHDRAWAL_ITEM",
  EXTERNAL_WITHDRAWAL_ITEM_UPDATE = "EXTERNAL_WITHDRAWAL_ITEM_UPDATE",
  EXTERNAL_WITHDRAWAL_ITEM_DELETE = "EXTERNAL_WITHDRAWAL_ITEM_DELETE",
  PAINT_FORMULA_COMPONENT_CREATE = "PAINT_FORMULA_COMPONENT_CREATE",
  PAINT_FORMULA_COMPONENT_UPDATE = "PAINT_FORMULA_COMPONENT_UPDATE",
  PAINT_FORMULA_COMPONENT_DELETE = "PAINT_FORMULA_COMPONENT_DELETE",
  PAINT_FORMULA_COMPONENT_BATCH_CREATE = "PAINT_FORMULA_COMPONENT_BATCH_CREATE",
  PAINT_FORMULA_COMPONENT_BATCH_UPDATE = "PAINT_FORMULA_COMPONENT_BATCH_UPDATE",
  PAINT_FORMULA_COMPONENT_BATCH_DELETE = "PAINT_FORMULA_COMPONENT_BATCH_DELETE",
  PAINT_PRODUCTION_CREATE = "PAINT_PRODUCTION_CREATE",
  PAINT_PRODUCTION_UPDATE = "PAINT_PRODUCTION_UPDATE",
  PAINT_PRODUCTION_DELETE = "PAINT_PRODUCTION_DELETE",
  PAINT_PRODUCTION_BATCH_CREATE = "PAINT_PRODUCTION_BATCH_CREATE",
  PAINT_PRODUCTION_BATCH_UPDATE = "PAINT_PRODUCTION_BATCH_UPDATE",
  PAINT_PRODUCTION_BATCH_DELETE = "PAINT_PRODUCTION_BATCH_DELETE",
  PAINT_CREATE = "PAINT_CREATE",
  PAINT_UPDATE = "PAINT_UPDATE",
  PAINT_DELETE = "PAINT_DELETE",
  PAINT_BATCH_CREATE = "PAINT_BATCH_CREATE",
  PAINT_BATCH_UPDATE = "PAINT_BATCH_UPDATE",
  PAINT_BATCH_DELETE = "PAINT_BATCH_DELETE",
  PAINT_FORMULA_CREATE = "PAINT_FORMULA_CREATE",
  PAINT_FORMULA_UPDATE = "PAINT_FORMULA_UPDATE",
  PAINT_FORMULA_DELETE = "PAINT_FORMULA_DELETE",
  PAINT_FORMULA_BATCH_CREATE = "PAINT_FORMULA_BATCH_CREATE",
  PAINT_FORMULA_BATCH_UPDATE = "PAINT_FORMULA_BATCH_UPDATE",
  PAINT_FORMULA_BATCH_DELETE = "PAINT_FORMULA_BATCH_DELETE",
  PAINT_TYPE_CREATE = "PAINT_TYPE_CREATE",
  PAINT_TYPE_UPDATE = "PAINT_TYPE_UPDATE",
  PAINT_TYPE_DELETE = "PAINT_TYPE_DELETE",
  PAINT_TYPE_BATCH_CREATE = "PAINT_TYPE_BATCH_CREATE",
  PAINT_TYPE_BATCH_UPDATE = "PAINT_TYPE_BATCH_UPDATE",
  PAINT_TYPE_BATCH_DELETE = "PAINT_TYPE_BATCH_DELETE",
  PAINT_BRAND_CREATE = "PAINT_BRAND_CREATE",
  PAINT_BRAND_UPDATE = "PAINT_BRAND_UPDATE",
  PAINT_BRAND_DELETE = "PAINT_BRAND_DELETE",
  PAINT_BRAND_BATCH_CREATE = "PAINT_BRAND_BATCH_CREATE",
  PAINT_BRAND_BATCH_UPDATE = "PAINT_BRAND_BATCH_UPDATE",
  PAINT_BRAND_BATCH_DELETE = "PAINT_BRAND_BATCH_DELETE",
  PAINT_GROUND_CREATE = "PAINT_GROUND_CREATE",
  PAINT_GROUND_UPDATE = "PAINT_GROUND_UPDATE",
  PAINT_GROUND_DELETE = "PAINT_GROUND_DELETE",
  PAINT_GROUND_BATCH_CREATE = "PAINT_GROUND_BATCH_CREATE",
  PAINT_GROUND_BATCH_UPDATE = "PAINT_GROUND_BATCH_UPDATE",
  PAINT_GROUND_BATCH_DELETE = "PAINT_GROUND_BATCH_DELETE",
  ORDER_UPDATE = "ORDER_UPDATE",
  ORDER_CREATE = "ORDER_CREATE",
  ORDER_STATUS_CHANGE = "ORDER_STATUS_CHANGE",
  ORDER_CANCEL = "ORDER_CANCEL",
  ORDER_ITEM_UPDATE = "ORDER_ITEM_UPDATE",
  ORDER_ITEM_RECEIVED = "ORDER_ITEM_RECEIVED",
  ORDER_ITEM_SYNC = "ORDER_ITEM_SYNC",
  EXTERNAL_WITHDRAWAL_SYNC = "EXTERNAL_WITHDRAWAL_SYNC",
  SCHEDULE = "SCHEDULE",
  ACTIVITY_CREATE = "ACTIVITY_CREATE",
  ACTIVITY_UPDATE = "ACTIVITY_UPDATE",
  ACTIVITY_DELETE = "ACTIVITY_DELETE",
  PPE_DELIVERY = "PPE_DELIVERY",
  ACTIVITY_SYNC = "ACTIVITY_SYNC",
  INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT",
  INVENTORY_COUNT = "INVENTORY_COUNT",
  ITEM_MONTHLY_CONSUMPTION_UPDATE = "ITEM_MONTHLY_CONSUMPTION_UPDATE",
  AUTOMATIC_MIN_MAX_UPDATE = "AUTOMATIC_MIN_MAX_UPDATE",
  SMS_VERIFICATION_CREATE = "SMS_VERIFICATION_CREATE",
  SMS_VERIFICATION_SEND = "SMS_VERIFICATION_SEND",
  SMS_VERIFICATION_VERIFY = "SMS_VERIFICATION_VERIFY",
  SMS_VERIFICATION_EXPIRE = "SMS_VERIFICATION_EXPIRE",
  SMS_VERIFICATION_CANCEL = "SMS_VERIFICATION_CANCEL",
  EMAIL_SERVICE = "EMAIL_SERVICE",
  VERIFICATION_CREATE = "VERIFICATION_CREATE",
  VERIFICATION_SEND = "VERIFICATION_SEND",
  VERIFICATION_VERIFY = "VERIFICATION_VERIFY",
  VERIFICATION_EXPIRE = "VERIFICATION_EXPIRE",
  VERIFICATION_CANCEL = "VERIFICATION_CANCEL",
  VERIFICATION_RESEND = "VERIFICATION_RESEND",
  VEHICLE_MOVEMENT = "VEHICLE_MOVEMENT",
  PARKING_ASSIGNMENT = "PARKING_ASSIGNMENT",
  GARAGE_CAPACITY_CHANGE = "GARAGE_CAPACITY_CHANGE",
  OBSERVATION_CREATE = "OBSERVATION_CREATE",
  OBSERVATION_DELETE = "OBSERVATION_DELETE",
  SCHEDULED_JOB = "SCHEDULED_JOB",
  API = "API",
  WEBHOOK = "WEBHOOK",
  ADMIN = "ADMIN",
}

// Alias for Prisma compatibility
export { CHANGE_TRIGGERED_BY as ChangeLogTriggeredByType };

// =====================
// Notification Types
// =====================

export enum NOTIFICATION_IMPORTANCE {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum NOTIFICATION_TYPE {
  SYSTEM = "SYSTEM",
  TASK = "TASK",
  ORDER = "ORDER",
  PPE = "PPE",
  VACATION = "VACATION",
  WARNING = "WARNING",
  STOCK = "STOCK",
  GENERAL = "GENERAL",
}

export enum NOTIFICATION_CHANNEL {
  EMAIL = "EMAIL",
  SMS = "SMS",
  PUSH = "PUSH",
  IN_APP = "IN_APP",
}

// =====================
// File Types
// =====================

export enum FILE_ENTITY_TYPE {
  TASK = "TASK",
  CUSTOMER_LOGO = "CUSTOMER_LOGO",
  SUPPLIER_LOGO = "SUPPLIER_LOGO",
  OBSERVATION = "OBSERVATION",
  WARNING = "WARNING",
  ORDER_BUDGET = "ORDER_BUDGET",
  ORDER_NFE = "ORDER_NFE",
  ORDER_RECEIPT = "ORDER_RECEIPT",
  TASK_BUDGET = "TASK_BUDGET",
  TASK_NFE = "TASK_NFE",
  TASK_RECEIPT = "TASK_RECEIPT",
  AIRBRUSHING_RECEIPT = "AIRBRUSHING_RECEIPT",
  AIRBRUSHING_NFE = "AIRBRUSHING_NFE",
  EXTERNAL_WITHDRAWAL_BUDGET = "EXTERNAL_WITHDRAWAL_BUDGET",
  EXTERNAL_WITHDRAWAL_NFE = "EXTERNAL_WITHDRAWAL_NFE",
  EXTERNAL_WITHDRAWAL_RECEIPT = "EXTERNAL_WITHDRAWAL_RECEIPT",
  EXPENSE = "EXPENSE",
}

// =====================
// PPE Types
// =====================

export enum PPE_TYPE {
  SHIRT = "SHIRT",
  PANTS = "PANTS",
  BOOTS = "BOOTS",
  SLEEVES = "SLEEVES",
  MASK = "MASK",
  GLOVES = "GLOVES",
  RAIN_BOOTS = "RAIN_BOOTS",
}

export enum PPE_SIZE_TYPE {
  SHIRT = "SHIRT",
  PANTS = "PANTS",
  BOOT = "BOOT",
  GLOVE = "GLOVE",
  MASK = "MASK",
  OVERALL = "OVERALL",
  HELMET = "HELMET",
  UNIFORM = "UNIFORM",
}

export enum PPE_DELIVERY_MODE {
  SCHEDULED = "SCHEDULED",
  ON_DEMAND = "ON_DEMAND",
  BOTH = "BOTH",
}

// =====================
// Fleet & Fuel Card Types
// =====================

// =====================
// Order & Stock Types
// =====================

export enum ORDER_TRIGGER_TYPE {
  STOCK_LEVEL = "STOCK_LEVEL",
  CONSUMPTION_RATE = "CONSUMPTION_RATE",
  SCHEDULED = "SCHEDULED",
}

export enum MAINTENANCE_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  OVERDUE = "OVERDUE",
}

export enum ACTIVITY_REASON {
  ORDER_RECEIVED = "ORDER_RECEIVED",
  PRODUCTION_USAGE = "PRODUCTION_USAGE",
  PPE_DELIVERY = "PPE_DELIVERY",
  BORROW = "BORROW",
  RETURN = "RETURN",
  EXTERNAL_WITHDRAWAL = "EXTERNAL_WITHDRAWAL",
  EXTERNAL_WITHDRAWAL_RETURN = "EXTERNAL_WITHDRAWAL_RETURN",
  INVENTORY_COUNT = "INVENTORY_COUNT",
  MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT",
  MAINTENANCE = "MAINTENANCE",
  DAMAGE = "DAMAGE",
  LOSS = "LOSS",
  PAINT_PRODUCTION = "PAINT_PRODUCTION",
  OTHER = "OTHER",
}

// =====================
// Color Schema
// =====================

export enum COLOR_SCHEMA {
  LIGHT = "LIGHT",
  DARK = "DARK",
  SYSTEM = "SYSTEM",
}

// =====================
// Verification Type
// =====================

export enum VERIFICATION_TYPE {
  EMAIL = "EMAIL",
  PHONE = "PHONE",
  PASSWORD_RESET = "PASSWORD_RESET",
}

// =====================
// Verification Error Codes
// =====================

export enum VERIFICATION_ERROR_CODE {
  // Request validation errors
  INVALID_CONTACT = "INVALID_CONTACT",
  CONTACT_REQUIRED = "CONTACT_REQUIRED",
  CODE_REQUIRED = "CODE_REQUIRED",
  INVALID_CONTACT_FORMAT = "INVALID_CONTACT_FORMAT",

  // User-related errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
  USER_INACTIVE = "USER_INACTIVE",

  // Code validation errors
  INVALID_CODE = "INVALID_CODE",
  CODE_EXPIRED = "CODE_EXPIRED",
  NO_CODE_SENT = "NO_CODE_SENT",
  CODE_MISMATCH = "CODE_MISMATCH",

  // Rate limiting errors
  TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  CONTACT_COOLDOWN = "CONTACT_COOLDOWN",
  IP_RATE_LIMITED = "IP_RATE_LIMITED",
  PROGRESSIVE_DELAY = "PROGRESSIVE_DELAY",

  // Service errors
  SMS_SEND_FAILED = "SMS_SEND_FAILED",
  EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",
  NOTIFICATION_FAILED = "NOTIFICATION_FAILED",
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",

  // System errors
  DATABASE_ERROR = "DATABASE_ERROR",
  CACHE_ERROR = "CACHE_ERROR",
  CONFIGURATION_ERROR = "CONFIGURATION_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",

  // Security errors
  SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",
  BLOCKED_IP = "BLOCKED_IP",
  BLACKLISTED_CONTACT = "BLACKLISTED_CONTACT",
  SECURITY_VIOLATION = "SECURITY_VIOLATION",
}

// =====================
// Verification Error Severity
// =====================

export enum VERIFICATION_ERROR_SEVERITY {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

// =====================
// Verification Error Category
// =====================

export enum VERIFICATION_ERROR_CATEGORY {
  VALIDATION = "VALIDATION",
  RATE_LIMITING = "RATE_LIMITING",
  AUTHENTICATION = "AUTHENTICATION",
  EXTERNAL_SERVICE = "EXTERNAL_SERVICE",
  SYSTEM = "SYSTEM",
  SECURITY = "SECURITY",
}

// =====================
// Workload Level
// =====================

export enum WORKLOAD_LEVEL {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

// =====================
// File Formats
// =====================

export enum FILE_FORMAT {
  JSON = "JSON",
  YAML = "YAML",
  CSV = "CSV",
  EXCEL = "EXCEL",
  PDF = "PDF",
}

// =====================
// Activity Levels
// =====================

export enum ACTIVITY_LEVEL {
  VERY_ACTIVE = "VERY_ACTIVE",
  ACTIVE = "ACTIVE",
  OCCASIONAL = "OCCASIONAL",
  DORMANT = "DORMANT",
  LOST = "LOST",
}

// =====================
// Change Actions
// =====================
// Event Types
// =====================

export enum EVENT_TYPE {
  CREATED = "CREATED",
  STARTED = "STARTED",
  PAUSED = "PAUSED",
  RESUMED = "RESUMED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

// =====================
// Timeline Event Types
// =====================

export enum TIMELINE_EVENT_TYPE {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  STATUS_CHANGED = "STATUS_CHANGED",
  FILE_ADDED = "FILE_ADDED",
  FILE_REMOVED = "FILE_REMOVED",
  NOTE_ADDED = "NOTE_ADDED",
  ASSIGNED = "ASSIGNED",
  COMPLETED = "COMPLETED",
}

// =====================
// Merge Strategy
// =====================

export enum MERGE_STRATEGY {
  KEEP_PRIMARY = "KEEP_PRIMARY",
  KEEP_NEWEST = "KEEP_NEWEST",
  MANUAL = "MANUAL",
}

// =====================
// Group By Options
// =====================

export enum GROUP_BY {
  DAY = "DAY",
  WEEK = "WEEK",
  MONTH = "MONTH",
  YEAR = "YEAR",
  ITEM = "ITEM",
  USER = "USER",
}

// =====================
// Holiday Types
// =====================

export enum HOLIDAY_TYPE {
  NATIONAL = "NATIONAL",
  STATE = "STATE",
  MUNICIPAL = "MUNICIPAL",
  OPTIONAL = "OPTIONAL",
}

// =====================
// Alert Types
// =====================

export enum ALERT_TYPE {
  // Activity Alerts
  HIGH_SPENDING = "HIGH_SPENDING",
  UNUSUAL_PATTERN = "UNUSUAL_PATTERN",
  DISCREPANCY = "DISCREPANCY",
  LOW_STOCK = "LOW_STOCK",

  // Item Alerts
  STOCK_OUT = "STOCK_OUT",
  OVERSTOCK = "OVERSTOCK",
  SLOW_MOVING = "SLOW_MOVING",
  REORDER_NEEDED = "REORDER_NEEDED",

  // User Alerts
  HIGH_TURNOVER = "HIGH_TURNOVER",
  ATTENDANCE_ISSUE = "ATTENDANCE_ISSUE",

  // Order Alerts
  DELIVERY_DELAY = "DELIVERY_DELAY",

  // Customer Alerts
  SERVICE_ISSUE = "SERVICE_ISSUE",
  PAYMENT_DELAY = "PAYMENT_DELAY",

  // Task Alerts
  OVERDUE = "OVERDUE",
  CUSTOMER_COMPLAINT = "CUSTOMER_COMPLAINT",

  // Borrow Alerts
  HIGH_DEMAND = "HIGH_DEMAND",
  USER_VIOLATION = "USER_VIOLATION",

  // Vacation Alerts
  EXPIRING_DAYS = "EXPIRING_DAYS",
  PLANNING_CONFLICT = "PLANNING_CONFLICT",

  // Warning Alerts
  REPEAT_OFFENDER = "REPEAT_OFFENDER",
  ESCALATION_NEEDED = "ESCALATION_NEEDED",
  PATTERN_DETECTED = "PATTERN_DETECTED",

  // PPE Alerts
  STOCK_SHORTAGE = "STOCK_SHORTAGE",
  MISSING_DELIVERY = "MISSING_DELIVERY",

  // Supplier Alerts
  DELIVERY_DELAYS = "DELIVERY_DELAYS",
}

export enum TASK_OBSERVATION_TYPE {
  DAMAGE = "DAMAGE",
  OVERDUE = "OVERDUE",
  QUALITY = "QUALITY",
}

export enum ITEM_ISSUE_TYPE {
  OVERAGE = "OVERAGE",
  SHORTAGE = "SHORTAGE",
  DAMAGE = "DAMAGE",
  MISMATCH = "MISMATCH",
}

// =====================
// Time Ranges
// =====================

export enum TIME_RANGE {
  LAST_7_DAYS = "LAST_7_DAYS",
  LAST_30_DAYS = "LAST_30_DAYS",
  LAST_90_DAYS = "LAST_90_DAYS",
  LAST_YEAR = "LAST_YEAR",
  CUSTOM = "CUSTOM",
}

export enum DASHBOARD_TIME_PERIOD {
  TODAY = "TODAY",
  THIS_WEEK = "THIS_WEEK",
  THIS_MONTH = "THIS_MONTH",
  THIS_YEAR = "THIS_YEAR",
  TOTAL = "TOTAL",
  ALL_TIME = "ALL_TIME",
}

// =====================
// Schedule & Order Enums
// =====================

export enum RESCHEDULE_REASON {
  LOW_FUNDS = "LOW_FUNDS",
  SUPPLIER_DELAY = "SUPPLIER_DELAY",
  OPERATIONAL_ISSUE = "OPERATIONAL_ISSUE",
  PRIORITY_CHANGE = "PRIORITY_CHANGE",
  SEASONAL_ADJUSTMENT = "SEASONAL_ADJUSTMENT",
  EMERGENCY = "EMERGENCY",
  OTHER = "OTHER",
}

export enum MAINTENANCE_SCHEDULE_STATUS {
  PENDING = "PENDING",
  FINISHED = "FINISHED",
  CANCELLED = "CANCELLED",
}

// =====================
// Change Log Enums
// =====================

export enum CHANGE_LOG_ENTITY_TYPE {
  ACTIVITY = "ACTIVITY",
  AIRBRUSHING = "AIRBRUSHING",
  BONUS = "BONUS",
  BORROW = "BORROW",
  CATEGORY = "CATEGORY",
  COLLECTION = "COLLECTION",
  COMMISSION = "COMMISSION",
  CUT = "CUT",
  CUT_ITEM = "CUT_ITEM",
  CUT_PLAN = "CUT_PLAN",
  CUT_REQUEST = "CUT_REQUEST",
  DELIVERY = "DELIVERY",
  DISCOUNT = "DISCOUNT",
  PPE_DELIVERY = "PPE_DELIVERY",
  PPE_DELIVERY_ITEM = "PPE_DELIVERY_ITEM",
  PPE_REQUEST = "PPE_REQUEST",
  PPE_DELIVERY_SCHEDULE = "PPE_DELIVERY_SCHEDULE",
  PPE_SIZE = "PPE_SIZE",
  EXTERNAL_WITHDRAWAL = "EXTERNAL_WITHDRAWAL",
  EXTERNAL_WITHDRAWAL_ITEM = "EXTERNAL_WITHDRAWAL_ITEM",
  FILE = "FILE",
  GARAGE_LANE = "GARAGE_LANE",
  ITEM = "ITEM",
  ITEM_BRAND = "ITEM_BRAND",
  ITEM_CATEGORY = "ITEM_CATEGORY",
  LAYOUT = "LAYOUT",
  MAINTENANCE = "MAINTENANCE",
  MAINTENANCE_ITEM = "MAINTENANCE_ITEM",
  MAINTENANCE_SCHEDULE = "MAINTENANCE_SCHEDULE",
  NOTIFICATION = "NOTIFICATION",
  ORDER = "ORDER",
  ORDER_ITEM = "ORDER_ITEM",
  ORDER_RULE = "ORDER_RULE",
  ORDER_SCHEDULE = "ORDER_SCHEDULE",
  PAINT = "PAINT",
  PAINT_TYPE = "PAINT_TYPE",
  SERVICE = "SERVICE",
  PAINT_GROUND = "PAINT_GROUND",
  PAINT_FORMULA = "PAINT_FORMULA",
  PAINT_FORMULA_COMPONENT = "PAINT_FORMULA_COMPONENT",
  PAINT_PRODUCTION = "PAINT_PRODUCTION",
  PARKING_SPOT = "PARKING_SPOT",
  PAYROLL = "PAYROLL",
  PIECE = "PIECE",
  POSITION = "POSITION",
  PRODUCTION = "PRODUCTION",
  PURCHASE = "PURCHASE",
  WARNING = "WARNING",
  SECTOR = "SECTOR",
  SERVICE_ORDER = "SERVICE_ORDER",
  SUPPLIER = "SUPPLIER",
  TASK = "TASK",
  TIME_CLOCK_ENTRY = "TIME_CLOCK_ENTRY",
  USER = "USER",
  VACATION = "VACATION",
  PPE_CONFIG = "PPE_CONFIG",
  PRICE = "PRICE",
  HOLIDAY = "HOLIDAY",
  CUSTOMER = "CUSTOMER",
  TRUCK = "TRUCK",
  SEEN_NOTIFICATION = "SEEN_NOTIFICATION",
  NOTIFICATION_PREFERENCE = "NOTIFICATION_PREFERENCE",
  VERIFICATION = "VERIFICATION",
  EXPENSE = "EXPENSE",
  DEPLOYMENT = "DEPLOYMENT",
}

// Alias for Prisma compatibility
export { CHANGE_LOG_ENTITY_TYPE as ChangeLogEntityType };

export enum CHANGE_LOG_ACTION {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  RESTORE = "RESTORE",
  ROLLBACK = "ROLLBACK",
  ARCHIVE = "ARCHIVE",
  UNARCHIVE = "UNARCHIVE",
  ACTIVATE = "ACTIVATE",
  DEACTIVATE = "DEACTIVATE",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  CANCEL = "CANCEL",
  COMPLETE = "COMPLETE",
  RESCHEDULE = "RESCHEDULE",
  BATCH_CREATE = "BATCH_CREATE",
  BATCH_UPDATE = "BATCH_UPDATE",
  BATCH_DELETE = "BATCH_DELETE",
  VIEW = "VIEW",
}

// Alias for Prisma compatibility
export { CHANGE_LOG_ACTION as ChangeLogAction };

// =====================
// Notification Action Types
// =====================

export enum NOTIFICATION_ACTION_TYPE {
  VIEW_DETAILS = "VIEW_DETAILS",
  APPROVE_REQUEST = "APPROVE_REQUEST",
  REJECT_REQUEST = "REJECT_REQUEST",
  COMPLETE_TASK = "COMPLETE_TASK",
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  VIEW_ORDER = "VIEW_ORDER",
  VIEW_REPORT = "VIEW_REPORT",
  ACKNOWLEDGE = "ACKNOWLEDGE",
  DISMISS = "DISMISS",
}

// =====================
// SMS Verification Enums
// =====================

export enum SMS_VERIFICATION_TYPE {
  PHONE_VERIFICATION = "PHONE_VERIFICATION",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  PASSWORD_RESET = "PASSWORD_RESET",
  TWO_FACTOR_AUTH = "TWO_FACTOR_AUTH",
  ACCOUNT_CONFIRMATION = "ACCOUNT_CONFIRMATION",
}

export enum SMS_VERIFICATION_STATUS {
  PENDING = "PENDING",
  SENT = "SENT",
  VERIFIED = "VERIFIED",
  EXPIRED = "EXPIRED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  RATE_LIMITED = "RATE_LIMITED",
  BLOCKED = "BLOCKED",
}

// =====================
// Rate Limiting Enums
// =====================

export enum RATE_LIMIT_TYPE {
  PER_CODE_ATTEMPT = "PER_CODE_ATTEMPT",
  IP_VERIFICATION = "IP_VERIFICATION",
  CODE_SEND_CONTACT = "CODE_SEND_CONTACT",
  CODE_SEND_IP = "CODE_SEND_IP",
  ACCOUNT_LOCKOUT = "ACCOUNT_LOCKOUT",
  GLOBAL_RATE_LIMIT = "GLOBAL_RATE_LIMIT",
}

export enum LOCKOUT_REASON {
  EXCESSIVE_FAILED_ATTEMPTS = "EXCESSIVE_FAILED_ATTEMPTS",
  IP_ABUSE_DETECTED = "IP_ABUSE_DETECTED",
  PATTERN_ABUSE = "PATTERN_ABUSE",
  CAPTCHA_FAILURES = "CAPTCHA_FAILURES",
  MANUAL_ADMIN_LOCK = "MANUAL_ADMIN_LOCK",
  SECURITY_VIOLATION = "SECURITY_VIOLATION",
}

export enum CAPTCHA_REQUIREMENT_LEVEL {
  NONE = "NONE",
  BASIC = "BASIC",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
  MAXIMUM = "MAXIMUM",
}

export enum VERIFICATION_ABUSE_LEVEL {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
  SEVERE = "SEVERE",
}

export enum PROGRESSIVE_DELAY_TIER {
  TIER_1 = "TIER_1", // 5 seconds
  TIER_2 = "TIER_2", // 15 seconds
  TIER_3 = "TIER_3", // 30 seconds
  TIER_4 = "TIER_4", // 1 minute
  TIER_5 = "TIER_5", // 5 minutes
  TIER_6 = "TIER_6", // 15 minutes
  TIER_7 = "TIER_7", // 30 minutes
  TIER_8 = "TIER_8", // 1 hour
}

export enum VERIFICATION_SECURITY_ACTION {
  LOG_ATTEMPT = "LOG_ATTEMPT",
  DELAY_RESPONSE = "DELAY_RESPONSE",
  REQUIRE_CAPTCHA = "REQUIRE_CAPTCHA",
  TEMPORARY_BLOCK = "TEMPORARY_BLOCK",
  ESCALATE_SECURITY = "ESCALATE_SECURITY",
  NOTIFY_ADMIN = "NOTIFY_ADMIN",
  PERMANENT_BLOCK = "PERMANENT_BLOCK",
}

// =====================
// Verification System Enums (Unified)
// =====================

export enum VERIFICATION_STATUS {
  PENDING = "PENDING",
  SENT = "SENT",
  VERIFIED = "VERIFIED",
  EXPIRED = "EXPIRED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum VERIFICATION_METHOD {
  EMAIL = "EMAIL",
  PHONE = "PHONE",
  EMAIL_AND_PHONE = "EMAIL_AND_PHONE",
}

export enum VERIFICATION_PURPOSE {
  ACCOUNT_VERIFICATION = "ACCOUNT_VERIFICATION",
  PASSWORD_RESET = "PASSWORD_RESET",
  PHONE_VERIFICATION = "PHONE_VERIFICATION",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  TWO_FACTOR_AUTH = "TWO_FACTOR_AUTH",
  LOGIN_VERIFICATION = "LOGIN_VERIFICATION",
}

// =====================
// Email Enums
// =====================

export enum EMAIL_TYPE {
  PASSWORD_RESET = "PASSWORD_RESET",
  TEMPORARY_PASSWORD = "TEMPORARY_PASSWORD",
  ACCOUNT_VERIFICATION = "ACCOUNT_VERIFICATION",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  ACCOUNT_STATUS_CHANGE = "ACCOUNT_STATUS_CHANGE",
  WELCOME = "WELCOME",
  NOTIFICATION = "NOTIFICATION",
}

export enum EMAIL_STATUS {
  PENDING = "PENDING",
  SENT = "SENT",
  DELIVERED = "DELIVERED",
  FAILED = "FAILED",
  BOUNCED = "BOUNCED",
  CANCELLED = "CANCELLED",
}

// =====================
// Default Notification Settings
// =====================

export const DEFAULT_NOTIFICATION_SETTINGS: Record<string, { importance: string; channels: string[] }> = {
  // Activity Alerts
  [ALERT_TYPE.HIGH_SPENDING]: { importance: NOTIFICATION_IMPORTANCE.URGENT, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.UNUSUAL_PATTERN]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },
  [ALERT_TYPE.DISCREPANCY]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.LOW_STOCK]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.PUSH] },

  // Item Alerts
  [ALERT_TYPE.STOCK_OUT]: { importance: NOTIFICATION_IMPORTANCE.URGENT, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },
  [ALERT_TYPE.OVERSTOCK]: { importance: NOTIFICATION_IMPORTANCE.LOW, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.SLOW_MOVING]: { importance: NOTIFICATION_IMPORTANCE.LOW, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.REORDER_NEEDED]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },

  // User Alerts
  [ALERT_TYPE.HIGH_TURNOVER]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.ATTENDANCE_ISSUE]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },

  // Order Alerts
  [ALERT_TYPE.DELIVERY_DELAY]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP] },

  // Customer Alerts
  [ALERT_TYPE.SERVICE_ISSUE]: { importance: NOTIFICATION_IMPORTANCE.URGENT, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.PAYMENT_DELAY]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },

  // Task Alerts
  [ALERT_TYPE.OVERDUE]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.CUSTOMER_COMPLAINT]: { importance: NOTIFICATION_IMPORTANCE.URGENT, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },

  // Borrow Alerts
  [ALERT_TYPE.HIGH_DEMAND]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.USER_VIOLATION]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },

  // Vacation Alerts
  [ALERT_TYPE.EXPIRING_DAYS]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.PLANNING_CONFLICT]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },

  // Warning Alerts
  [ALERT_TYPE.REPEAT_OFFENDER]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },
  [ALERT_TYPE.ESCALATION_NEEDED]: { importance: NOTIFICATION_IMPORTANCE.URGENT, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.EMAIL] },
  [ALERT_TYPE.PATTERN_DETECTED]: { importance: NOTIFICATION_IMPORTANCE.NORMAL, channels: [NOTIFICATION_CHANNEL.IN_APP] },

  // PPE Alerts
  [ALERT_TYPE.STOCK_SHORTAGE]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.PUSH, NOTIFICATION_CHANNEL.IN_APP] },
  [ALERT_TYPE.MISSING_DELIVERY]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP] },

  // Supplier Alerts
  [ALERT_TYPE.DELIVERY_DELAYS]: { importance: NOTIFICATION_IMPORTANCE.HIGH, channels: [NOTIFICATION_CHANNEL.IN_APP, NOTIFICATION_CHANNEL.PUSH] },
};

// =====================
// Item Notes & Documents Enums
// =====================

export enum NOTE_CATEGORY {
  GENERAL = "GENERAL",
  QUALITY = "QUALITY",
  MAINTENANCE = "MAINTENANCE",
  COMPLIANCE = "COMPLIANCE",
  SPECIFICATION = "SPECIFICATION",
  USAGE = "USAGE",
  SUPPLIER = "SUPPLIER",
  SAFETY = "SAFETY",
  OTHER = "OTHER",
}

export enum DOCUMENT_CATEGORY {
  TECHNICAL_SPEC = "TECHNICAL_SPEC",
  CERTIFICATE = "CERTIFICATE",
  MANUAL = "MANUAL",
  SAFETY_DATA = "SAFETY_DATA",
  WARRANTY = "WARRANTY",
  INVOICE = "INVOICE",
  CONTRACT = "CONTRACT",
  COMPLIANCE = "COMPLIANCE",
  PHOTO = "PHOTO",
  OTHER = "OTHER",
}

export enum LINK_TYPE {
  MANUFACTURER = "MANUFACTURER",
  DOCUMENTATION = "DOCUMENTATION",
  TUTORIAL = "TUTORIAL",
  SUPPLIER = "SUPPLIER",
  INTERNAL = "INTERNAL",
  OTHER = "OTHER",
}

// =====================
// Item Category Types
// =====================

export enum ITEM_CATEGORY_TYPE {
  REGULAR = "REGULAR",
  TOOL = "TOOL",
  PPE = "PPE",
}

// =====================
// Financial - Expense Management
// =====================

// =====================
// Fleet & Driver Management
// =====================

export enum DRIVER_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
  LICENSE_EXPIRED = "LICENSE_EXPIRED",
}

export enum CNH_CATEGORY {
  A = "A",
  B = "B",
  C = "C",
  D = "D",
  E = "E",
  AB = "AB",
  AC = "AC",
  AD = "AD",
  AE = "AE",
}

export enum LICENSE_TYPE {
  DEFINITIVE = "DEFINITIVE",
  PROVISIONAL = "PROVISIONAL",
  INTERNATIONAL = "INTERNATIONAL",
}

export enum BLOOD_TYPE {
  A_POSITIVE = "A_POSITIVE",
  A_NEGATIVE = "A_NEGATIVE",
  B_POSITIVE = "B_POSITIVE",
  B_NEGATIVE = "B_NEGATIVE",
  AB_POSITIVE = "AB_POSITIVE",
  AB_NEGATIVE = "AB_NEGATIVE",
  O_POSITIVE = "O_POSITIVE",
  O_NEGATIVE = "O_NEGATIVE",
}

// =====================
// Favorite Pages
// =====================

export enum FAVORITE_PAGES {
  // Production - List Pages
  PRODUCAO_CRONOGRAMA_LISTAR = "/producao/cronograma",
  PRODUCAO_RECORTE_LISTAR = "/producao/recorte",
  PRODUCAO_SERVICOS_LISTAR = "/producao/servicos",
  PRODUCAO_OBSERVACOES_LISTAR = "/producao/observacoes",
  PRODUCAO_AEROGRAFIA_LISTAR = "/producao/aerografia/listar",
  PRODUCAO_GARAGENS_LISTAR = "/producao/garagens",
  PRODUCAO_ORDENS_SERVICO_LISTAR = "/producao/ordens-de-servico",
  PRODUCAO_HISTORICO_LISTAR = "/producao/historico",

  // Production - Create Pages
  PRODUCAO_CRONOGRAMA_CADASTRAR = "/producao/cronograma/cadastrar",
  PRODUCAO_RECORTE_CADASTRAR = "/producao/recorte/cadastrar",
  PRODUCAO_SERVICOS_CADASTRAR = "/producao/servicos/cadastrar",
  PRODUCAO_OBSERVACOES_CADASTRAR = "/producao/observacoes/cadastrar",
  PRODUCAO_AEROGRAFIA_CADASTRAR = "/producao/aerografia/cadastrar",
  PRODUCAO_GARAGENS_CADASTRAR = "/producao/garagens/cadastrar",
  PRODUCAO_ORDENS_SERVICO_CADASTRAR = "/producao/ordens-de-servico/cadastrar",

  // Inventory - List Pages
  ESTOQUE_MOVIMENTACOES_LISTAR = "/estoque/movimentacoes",
  ESTOQUE_PRODUTOS_LISTAR = "/estoque/produtos",
  ESTOQUE_PRODUTOS_CATEGORIAS_LISTAR = "/estoque/produtos/categorias",
  ESTOQUE_PRODUTOS_MARCAS_LISTAR = "/estoque/produtos/marcas",
  ESTOQUE_PEDIDOS_LISTAR = "/estoque/pedidos",
  ESTOQUE_PEDIDOS_AGENDAMENTOS_LISTAR = "/estoque/pedidos/agendamentos",
  ESTOQUE_PEDIDOS_AUTOMATICOS_LISTAR = "/estoque/pedidos/automaticos",
  ESTOQUE_MANUTENCAO_LISTAR = "/estoque/manutencao/listar",
  ESTOQUE_MANUTENCAO_AGENDAMENTOS_LISTAR = "/estoque/manutencao/agendamentos",
  ESTOQUE_RETIRADAS_EXTERNAS_LISTAR = "/estoque/retiradas-externas",
  ESTOQUE_FORNECEDORES_LISTAR = "/estoque/fornecedores",
  ESTOQUE_EPI_LISTAR = "/estoque/epi",
  ESTOQUE_EPI_ENTREGAS_LISTAR = "/estoque/epi/entregas",
  ESTOQUE_EPI_AGENDAMENTOS_LISTAR = "/estoque/epi/agendamentos",
  ESTOQUE_EMPRESTIMOS_LISTAR = "/estoque/emprestimos",

  // Statistics Pages
  ESTATISTICAS = "/estatisticas",
  ESTATISTICAS_ESTOQUE = "/estatisticas/estoque",
  ESTATISTICAS_ESTOQUE_CONSUMO = "/estatisticas/estoque/consumo",
  ESTATISTICAS_ESTOQUE_MOVIMENTACAO = "/estatisticas/estoque/movimentacao",
  ESTATISTICAS_ESTOQUE_TENDENCIAS = "/estatisticas/estoque/tendencias",
  ESTATISTICAS_ESTOQUE_TOP_ITENS = "/estatisticas/estoque/top-itens",

  // Inventory - Create Pages
  ESTOQUE_MOVIMENTACOES_CADASTRAR = "/estoque/movimentacoes/cadastrar",
  ESTOQUE_PRODUTOS_CADASTRAR = "/estoque/produtos/cadastrar",
  ESTOQUE_PRODUTOS_CATEGORIAS_CADASTRAR = "/estoque/produtos/categorias/cadastrar",
  ESTOQUE_PRODUTOS_MARCAS_CADASTRAR = "/estoque/produtos/marcas/cadastrar",
  ESTOQUE_PEDIDOS_CADASTRAR = "/estoque/pedidos/cadastrar",
  ESTOQUE_PEDIDOS_AGENDAMENTOS_CADASTRAR = "/estoque/pedidos/agendamentos/cadastrar",
  ESTOQUE_MANUTENCAO_CADASTRAR = "/estoque/manutencao/cadastrar",
  ESTOQUE_MANUTENCAO_AGENDAMENTOS_CADASTRAR = "/estoque/manutencao/agendamentos/cadastrar",
  ESTOQUE_RETIRADAS_EXTERNAS_CADASTRAR = "/estoque/retiradas-externas/cadastrar",
  ESTOQUE_FORNECEDORES_CADASTRAR = "/estoque/fornecedores/cadastrar",
  ESTOQUE_EPI_CADASTRAR = "/estoque/epi/cadastrar",
  ESTOQUE_EPI_ENTREGAS_CADASTRAR = "/estoque/epi/entregas/cadastrar",
  ESTOQUE_EPI_AGENDAMENTOS_CADASTRAR = "/estoque/epi/agendamentos/cadastrar",
  ESTOQUE_EMPRESTIMOS_CADASTRAR = "/estoque/emprestimos/cadastrar",

  // Painting - List Pages
  PINTURA_CATALOGO_LISTAR = "/pintura/catalogo",
  PINTURA_PRODUCOES_LISTAR = "/pintura/producoes",
  PINTURA_TIPOS_TINTA_LISTAR = "/pintura/tipos-de-tinta",
  PINTURA_FORMULAS_LISTAR = "/pintura/formulas/listar",
  PINTURA_FORMULACOES_LISTAR = "/pintura/formulacoes/listar",
  PINTURA_COMPONENTES_LISTAR = "/pintura/componentes/listar",

  // Painting - Create Pages
  PINTURA_CATALOGO_CADASTRAR = "/pintura/catalogo/cadastrar",
  PINTURA_PRODUCOES_CADASTRAR = "/pintura/producoes/cadastrar",
  PINTURA_TIPOS_TINTA_CADASTRAR = "/pintura/tipos-de-tinta/cadastrar",
  PINTURA_FORMULAS_CADASTRAR = "/pintura/formulas/cadastrar",
  PINTURA_FORMULACOES_CADASTRAR = "/pintura/formulacoes/cadastrar",
  PINTURA_COMPONENTES_CADASTRAR = "/pintura/componentes/cadastrar",

  // Administration - List Pages
  ADMINISTRACAO_COMISSOES_LISTAR = "/administracao/comissoes",
  ADMINISTRACAO_CLIENTES_LISTAR = "/administracao/clientes",
  ADMINISTRACAO_COLABORADORES_LISTAR = "/administracao/colaboradores",
  ADMINISTRACAO_ORCAMENTOS_LISTAR = "/administracao/orcamentos",
  ADMINISTRACAO_REGISTROS_ALTERACOES_LISTAR = "/administracao/registros-de-alteracoes",
  ADMINISTRACAO_ARQUIVOS_LISTAR = "/administracao/arquivos",
  ADMINISTRACAO_SETORES_LISTAR = "/administracao/setores",
  ADMINISTRACAO_NOTIFICACOES_LISTAR = "/administracao/notificacoes",
  ADMINISTRACAO_FOLHA_DE_PAGAMENTO = "/recursos-humanos/folha-de-pagamento",

  // Administration - Create Pages
  ADMINISTRACAO_CLIENTES_CADASTRAR = "/administracao/clientes/cadastrar",
  ADMINISTRACAO_COLABORADORES_CADASTRAR = "/administracao/colaboradores/cadastrar",
  ADMINISTRACAO_ORCAMENTOS_CADASTRAR = "/administracao/orcamentos/cadastrar",
  ADMINISTRACAO_ARQUIVOS_CADASTRAR = "/administracao/arquivos/upload",
  ADMINISTRACAO_SETORES_CADASTRAR = "/administracao/setores/cadastrar",
  ADMINISTRACAO_NOTIFICACOES_CADASTRAR = "/administracao/notificacoes/cadastrar/enviar",
  ADMINISTRACAO_NOTIFICACOES_EDITAR = "/administracao/notificacoes/editar",

  // Human Resources - List Pages
  RECURSOS_HUMANOS_CARGOS_LISTAR = "/recursos-humanos/cargos",
  RECURSOS_HUMANOS_FERIAS_LISTAR = "/recursos-humanos/ferias",
  RECURSOS_HUMANOS_FERIADOS_LISTAR = "/recursos-humanos/feriados",
  RECURSOS_HUMANOS_AVISOS_LISTAR = "/recursos-humanos/avisos",
  RECURSOS_HUMANOS_CALCULOS = "/recursos-humanos/calculos",
  RECURSOS_HUMANOS_EPI_LISTAR = "/recursos-humanos/epi",
  RECURSOS_HUMANOS_EPI_ENTREGAS_LISTAR = "/recursos-humanos/epi/entregas",
  RECURSOS_HUMANOS_EPI_AGENDAMENTOS_LISTAR = "/recursos-humanos/epi/agendamentos",
  RECURSOS_HUMANOS_EPI_TAMANHOS_LISTAR = "/recursos-humanos/epi/tamanhos",
  RECURSOS_HUMANOS_SETORES_LISTAR = "/recursos-humanos/setores",

  // Human Resources - Create Pages
  RECURSOS_HUMANOS_CARGOS_CADASTRAR = "/recursos-humanos/cargos/cadastrar",
  RECURSOS_HUMANOS_FERIAS_CADASTRAR = "/recursos-humanos/ferias/cadastrar",
  RECURSOS_HUMANOS_FERIADOS_CADASTRAR = "/recursos-humanos/feriados/cadastrar",
  RECURSOS_HUMANOS_AVISOS_CADASTRAR = "/recursos-humanos/avisos/cadastrar",
  RECURSOS_HUMANOS_EPI_CADASTRAR = "/recursos-humanos/epi/cadastrar",
  RECURSOS_HUMANOS_EPI_ENTREGAS_CADASTRAR = "/recursos-humanos/epi/entregas/cadastrar",
  RECURSOS_HUMANOS_EPI_AGENDAMENTOS_CADASTRAR = "/recursos-humanos/epi/agendamentos/cadastrar",
  RECURSOS_HUMANOS_EPI_TAMANHOS_CADASTRAR = "/recursos-humanos/epi/tamanhos/cadastrar",
  RECURSOS_HUMANOS_SETORES_CADASTRAR = "/recursos-humanos/setores/cadastrar",

  // Personal - List Pages
  PESSOAL_MINHAS_COMISSOES_LISTAR = "/pessoal/minhas-comissoes",
  PESSOAL_MINHAS_FERIAS_LISTAR = "/pessoal/minhas-ferias",
  PESSOAL_MEUS_FERIADOS_LISTAR = "/pessoal/meus-feriados",
  PESSOAL_MEUS_EMPRESTIMOS_LISTAR = "/pessoal/meus-emprestimos",
  PESSOAL_MEUS_EPIS_LISTAR = "/pessoal/meus-epis",
  PESSOAL_MEUS_AVISOS_LISTAR = "/pessoal/meus-avisos",
  PESSOAL_MINHAS_NOTIFICACOES_LISTAR = "/pessoal/minhas-notificacoes",

  // Catalog Basic - List Pages
  CATALOGO_BASICO_LISTAR = "/pintura/catalogo-basico",

  // Server - List Pages
  SERVIDOR_USUARIOS = "/servidor/usuarios",

  // Human Resources - Edit Pages
  RECURSOS_HUMANOS_CARGOS_EDITAR = "/recursos-humanos/cargos/editar/:id",
  RECURSOS_HUMANOS_FERIAS_EDITAR = "/recursos-humanos/ferias/editar/:id",
  RECURSOS_HUMANOS_FERIADOS_EDITAR = "/recursos-humanos/feriados/editar/:id",
  RECURSOS_HUMANOS_AVISOS_EDITAR = "/recursos-humanos/avisos/editar/:id",
  RECURSOS_HUMANOS_SETORES_EDITAR = "/recursos-humanos/setores/editar/:id",

  // Human Resources - Details Pages
  RECURSOS_HUMANOS_CARGOS_DETALHES = "/recursos-humanos/cargos/detalhes/:id",
  RECURSOS_HUMANOS_FERIAS_DETALHES = "/recursos-humanos/ferias/detalhes/:id",
  RECURSOS_HUMANOS_FERIADOS_DETALHES = "/recursos-humanos/feriados/detalhes/:id",
  RECURSOS_HUMANOS_AVISOS_DETALHES = "/recursos-humanos/avisos/detalhes/:id",

  // Human Resources - Batch Edit Pages
  RECURSOS_HUMANOS_CARGOS_EDITAR_LOTE = "/recursos-humanos/cargos/editar-lote",
  RECURSOS_HUMANOS_FERIAS_EDITAR_LOTE = "/recursos-humanos/ferias/editar-lote",
  RECURSOS_HUMANOS_FERIADOS_EDITAR_LOTE = "/recursos-humanos/feriados/editar-lote",
  RECURSOS_HUMANOS_AVISOS_EDITAR_LOTE = "/recursos-humanos/avisos/editar-lote",

  // Human Resources - Calendar Pages
  RECURSOS_HUMANOS_FERIAS_CALENDARIO = "/recursos-humanos/ferias/calendario",
  RECURSOS_HUMANOS_FERIADOS_CALENDARIO = "/recursos-humanos/feriados/calendario",

  // Human Resources - Additional Pages
  RECURSOS_HUMANOS_CARGOS_REMUNERACOES = "/recursos-humanos/cargos/:positionId/remuneracoes",

  // Administration - Edit Pages
  ADMINISTRACAO_SETORES_EDITAR = "/administracao/setores/editar/:id",

  // Administration - Details Pages
  ADMINISTRACAO_SETORES_DETALHES = "/administracao/setores/detalhes/:id",

  // Administration - Batch Edit Pages
  ADMINISTRACAO_SETORES_EDITAR_LOTE = "/administracao/setores/editar-lote",
}

export enum LAYOUT_SIDE {
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  BACK = "BACK",
}

// =====================
// Bonus & Payroll Enums
// =====================

export enum BONUS_DISCOUNT_REASON {
  ABSENCE = "ABSENCE",
  LATE_DELIVERY = "LATE_DELIVERY",
  QUALITY_ISSUE = "QUALITY_ISSUE",
  DISCIPLINARY = "DISCIPLINARY",
  OTHER = "OTHER",
}

export enum BONUS_STATUS {
  DRAFT = "DRAFT",
  CONFIRMED = "CONFIRMED",
}

export enum COMMISSION_STATUS {
  NO_COMMISSION = "NO_COMMISSION",
  PARTIAL_COMMISSION = "PARTIAL_COMMISSION",
  FULL_COMMISSION = "FULL_COMMISSION",
  SUSPENDED_COMMISSION = "SUSPENDED_COMMISSION",
}

export enum DISCOUNT_TYPE {
  PERCENTAGE = "PERCENTAGE",
  FIXED_VALUE = "FIXED_VALUE",
}

export enum PAYROLL_STATUS {
  DRAFT = "DRAFT",
  FINALIZED = "FINALIZED",
}

export enum PAYROLL_MONTH {
  JANUARY = "JANUARY",
  FEBRUARY = "FEBRUARY",
  MARCH = "MARCH",
  APRIL = "APRIL",
  MAY = "MAY",
  JUNE = "JUNE",
  JULY = "JULY",
  AUGUST = "AUGUST",
  SEPTEMBER = "SEPTEMBER",
  OCTOBER = "OCTOBER",
  NOVEMBER = "NOVEMBER",
  DECEMBER = "DECEMBER",
}

// =====================
// Deployment Enums
// =====================

export enum DEPLOYMENT_ENVIRONMENT {
  DEVELOPMENT = "DEVELOPMENT",
  STAGING = "STAGING",
  PRODUCTION = "PRODUCTION",
}

export enum DEPLOYMENT_STATUS {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  BUILDING = "BUILDING",
  TESTING = "TESTING",
  DEPLOYING = "DEPLOYING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ROLLED_BACK = "ROLLED_BACK",
  CANCELLED = "CANCELLED",
}

export enum DEPLOYMENT_TRIGGER {
  MANUAL = "MANUAL",
  AUTO = "AUTO",
  PUSH = "PUSH",
  PULL_REQUEST = "PULL_REQUEST",
  TAG = "TAG",
  SCHEDULE = "SCHEDULE",
  WEBHOOK = "WEBHOOK",
  ROLLBACK = "ROLLBACK",
  API = "API",
}

// Aliases for Prisma compatibility
export { DEPLOYMENT_ENVIRONMENT as DeploymentEnvironment };
export { DEPLOYMENT_STATUS as DeploymentStatus };
export { DEPLOYMENT_TRIGGER as DeploymentTrigger };
