// packages/constants/src/sortOrders.ts

import {
  ABC_CATEGORY,
  XYZ_CATEGORY,
  ASSIGNMENT_TYPE,
  TASK_STATUS,
  ORDER_STATUS,
  SERVICE_ORDER_STATUS,
  AIRBRUSHING_STATUS,
  USER_STATUS,
  VACATION_STATUS,
  VACATION_TYPE,
  WARNING_SEVERITY,
  WARNING_CATEGORY,
  TREND_DIRECTION,
  TREND_TYPE,
  PERIOD_TYPE,
  PRIORITY_TYPE,
  RISK_LEVEL,
  STOCK_LEVEL,
  HEALTH_STATUS,
  PERFORMANCE_LEVEL,
  URGENCY_LEVEL,
  EFFORT_LEVEL,
  CONFIDENCE_LEVEL,
  PERCENTAGE_ADJUST_TYPE,
  EXPORT_FORMAT,
  BATCH_OPERATION_STATUS,
  VALIDATION_SEVERITY,
  MONTH,
  PANTS_SIZE,
  SHIRT_SIZE,
  BOOT_SIZE,
  PAINT_BRAND,
  PAINT_BRAND_STATUS,
  PAINT_FINISH,
  PAINT_TYPE_ENUM,
  TRUCK_MANUFACTURER,
  ACTIVITY_OPERATION,
  AUDIT_ACTION,
  ENTITY_TYPE,
  CHANGE_LOG_ENTITY_TYPE,
  NOTIFICATION_IMPORTANCE,
  NOTIFICATION_TYPE,
  NOTIFICATION_CHANNEL,
  PPE_DELIVERY_MODE,
  ORDER_TRIGGER_TYPE,
  ACTIVITY_REASON,
  COLOR_SCHEMA,
  VERIFICATION_TYPE,
  VERIFICATION_ERROR_SEVERITY,
  VERIFICATION_ERROR_CATEGORY,
  WORKLOAD_LEVEL,
  FILE_ENTITY_TYPE,
  FILE_FORMAT,
  ACTIVITY_LEVEL,
  CHANGE_ACTION,
  BONUS_STATUS,
  BORROW_STATUS,
  EXTERNAL_WITHDRAWAL_STATUS,
  EVENT_TYPE,
  TIMELINE_EVENT_TYPE,
  MERGE_STRATEGY,
  GROUP_BY,
  HOLIDAY_TYPE,
  ALERT_TYPE,
  TASK_OBSERVATION_TYPE,
  ITEM_ISSUE_TYPE,
  ITEM_CATEGORY_TYPE,
  TIME_RANGE,
  PPE_REQUEST_STATUS,
  PPE_DELIVERY_STATUS,
  COLOR_PALETTE,
  MAINTENANCE_STATUS,
  MAINTENANCE_SCHEDULE_STATUS,
  SCHEDULE_FREQUENCY,
  SECTOR_PRIVILEGES,
  CHART_TYPE,
  MEASURE_UNIT,
  MEASURE_TYPE,
  MONTH_OCCURRENCE,
  CHANGE_TRIGGERED_BY,
  CUT_STATUS,
  CUT_ORIGIN,
  GARAGE_STATUS,
  SMS_VERIFICATION_STATUS,
  SMS_VERIFICATION_TYPE,
  RATE_LIMIT_TYPE,
  LOCKOUT_REASON,
  CAPTCHA_REQUIREMENT_LEVEL,
  VERIFICATION_ABUSE_LEVEL,
  PROGRESSIVE_DELAY_TIER,
  VERIFICATION_SECURITY_ACTION,
  EMAIL_TYPE,
  EMAIL_STATUS,
  VERIFICATION_STATUS,
  VERIFICATION_METHOD,
  VERIFICATION_PURPOSE,
  PPE_TYPE,
  PPE_SIZE_TYPE,
  MASK_SIZE,
  SLEEVES_SIZE,
  PPE_SIZE,
  DAY_OF_WEEK,
  DRIVER_STATUS,
  CNH_CATEGORY,
  LICENSE_TYPE,
  BLOOD_TYPE,
  DISCOUNT_TYPE,
  PAYROLL_STATUS,
  STATISTICS_GROUP_BY,
  STATISTICS_METRIC,
  STATISTICS_PERIOD,
} from "./enums";

/**
 * Maps enum values to their sort order for logical sorting
 */

// =====================
// Status Order Maps
// =====================

// =====================
// ABC/XYZ Analysis Order Maps
// =====================


export const PAINT_BRAND_STATUS_ORDER: Record<PAINT_BRAND_STATUS, number> = {
  [PAINT_BRAND_STATUS.ACTIVE]: 1,
  [PAINT_BRAND_STATUS.INACTIVE]: 2,
};

export const TASK_STATUS_ORDER: Record<string, number> = {
  [TASK_STATUS.PENDING]: 1,
  [TASK_STATUS.IN_PRODUCTION]: 2,
  [TASK_STATUS.ON_HOLD]: 3,
  [TASK_STATUS.COMPLETED]: 4,
  [TASK_STATUS.CANCELLED]: 5,
};

export const ORDER_STATUS_ORDER: Record<string, number> = {
  [ORDER_STATUS.CREATED]: 1,
  [ORDER_STATUS.PARTIALLY_FULFILLED]: 2,
  [ORDER_STATUS.FULFILLED]: 3,
  [ORDER_STATUS.OVERDUE]: 4,
  [ORDER_STATUS.PARTIALLY_RECEIVED]: 5,
  [ORDER_STATUS.RECEIVED]: 6,
  [ORDER_STATUS.CANCELLED]: 7,
};

export const ASSIGNMENT_TYPE_ORDER: Record<string, number> = {
  [ASSIGNMENT_TYPE.ALL]: 1,
  [ASSIGNMENT_TYPE.ALL_EXCEPT]: 2,
  [ASSIGNMENT_TYPE.SPECIFIC]: 3,
};

export const SERVICE_ORDER_STATUS_ORDER: Record<string, number> = {
  [SERVICE_ORDER_STATUS.PENDING]: 1,
  [SERVICE_ORDER_STATUS.IN_PROGRESS]: 2,
  [SERVICE_ORDER_STATUS.COMPLETED]: 3,
  [SERVICE_ORDER_STATUS.CANCELLED]: 4,
};

export const USER_STATUS_ORDER: Record<string, number> = {
  [USER_STATUS.EXPERIENCE_PERIOD_1]: 1,
  [USER_STATUS.EXPERIENCE_PERIOD_2]: 2,
  [USER_STATUS.CONTRACTED]: 3,
  [USER_STATUS.DISMISSED]: 4,
};

export const COLOR_PALETTE_ORDER: Record<string, number> = {
  [COLOR_PALETTE.BLACK]: 1,
  [COLOR_PALETTE.GRAY]: 2,
  [COLOR_PALETTE.SILVER]: 3,
  [COLOR_PALETTE.WHITE]: 4,
  [COLOR_PALETTE.BEIGE]: 5,
  [COLOR_PALETTE.YELLOW]: 6,
  [COLOR_PALETTE.GOLDEN]: 7,
  [COLOR_PALETTE.ORANGE]: 8,
  [COLOR_PALETTE.BROWN]: 9,
  [COLOR_PALETTE.RED]: 10,
  [COLOR_PALETTE.PINK]: 11,
  [COLOR_PALETTE.PURPLE]: 12,
  [COLOR_PALETTE.BLUE]: 13,
  [COLOR_PALETTE.GREEN]: 14,
};

export const MAINTENANCE_STATUS_ORDER: Record<string, number> = {
  [MAINTENANCE_STATUS.PENDING]: 1,
  [MAINTENANCE_STATUS.IN_PROGRESS]: 2,
  [MAINTENANCE_STATUS.COMPLETED]: 3,
  [MAINTENANCE_STATUS.CANCELLED]: 4,
  [MAINTENANCE_STATUS.OVERDUE]: 5,
};

export const MAINTENANCE_SCHEDULE_STATUS_ORDER: Record<string, number> = {
  [MAINTENANCE_SCHEDULE_STATUS.PENDING]: 1,
  [MAINTENANCE_SCHEDULE_STATUS.FINISHED]: 2,
};

export const MAINTENANCE_FREQUENCY_ORDER: Record<string, number> = {
  [SCHEDULE_FREQUENCY.ONCE]: 1,
  [SCHEDULE_FREQUENCY.DAILY]: 2,
  [SCHEDULE_FREQUENCY.WEEKLY]: 3,
  [SCHEDULE_FREQUENCY.BIWEEKLY]: 4,
  [SCHEDULE_FREQUENCY.MONTHLY]: 5,
  [SCHEDULE_FREQUENCY.BIMONTHLY]: 6,
  [SCHEDULE_FREQUENCY.QUARTERLY]: 7,
  [SCHEDULE_FREQUENCY.TRIANNUAL]: 8,
  [SCHEDULE_FREQUENCY.QUADRIMESTRAL]: 9,
  [SCHEDULE_FREQUENCY.SEMI_ANNUAL]: 10,
  [SCHEDULE_FREQUENCY.ANNUAL]: 11,
  [SCHEDULE_FREQUENCY.CUSTOM]: 12,
};
export const AIRBRUSHING_STATUS_ORDER: Record<string, number> = {
  [AIRBRUSHING_STATUS.PENDING]: 1,
  [AIRBRUSHING_STATUS.IN_PRODUCTION]: 2,
  [AIRBRUSHING_STATUS.COMPLETED]: 3,
  [AIRBRUSHING_STATUS.CANCELLED]: 4,
};

export const VACATION_STATUS_ORDER: Record<string, number> = {
  [VACATION_STATUS.PENDING]: 1,
  [VACATION_STATUS.APPROVED]: 2,
  [VACATION_STATUS.REJECTED]: 3,
  [VACATION_STATUS.CANCELLED]: 4,
  [VACATION_STATUS.IN_PROGRESS]: 5,
  [VACATION_STATUS.COMPLETED]: 6,
};

export const PPE_REQUEST_STATUS_ORDER: Record<string, number> = {
  [PPE_REQUEST_STATUS.PENDING]: 1,
  [PPE_REQUEST_STATUS.APPROVED]: 2,
  [PPE_REQUEST_STATUS.REJECTED]: 3,
  [PPE_REQUEST_STATUS.DELIVERED]: 4,
  [PPE_REQUEST_STATUS.CANCELLED]: 5,
};

export const PPE_DELIVERY_STATUS_ORDER: Record<string, number> = {
  [PPE_DELIVERY_STATUS.PENDING]: 1,
  [PPE_DELIVERY_STATUS.APPROVED]: 2,
  [PPE_DELIVERY_STATUS.DELIVERED]: 3,
  [PPE_DELIVERY_STATUS.REPROVED]: 4,
  [PPE_DELIVERY_STATUS.CANCELLED]: 5,
};

export const BATCH_OPERATION_STATUS_ORDER: Record<string, number> = {
  [BATCH_OPERATION_STATUS.PENDING]: 1,
  [BATCH_OPERATION_STATUS.PROCESSING]: 2,
  [BATCH_OPERATION_STATUS.PARTIAL]: 3,
  [BATCH_OPERATION_STATUS.COMPLETED]: 4,
  [BATCH_OPERATION_STATUS.FAILED]: 5,
};

export const BORROW_STATUS_ORDER: Record<string, number> = {
  [BORROW_STATUS.ACTIVE]: 1,
  [BORROW_STATUS.RETURNED]: 4,
  [BORROW_STATUS.LOST]: 5,
};

export const EXTERNAL_WITHDRAWAL_STATUS_ORDER: Record<string, number> = {
  [EXTERNAL_WITHDRAWAL_STATUS.PENDING]: 1,
  [EXTERNAL_WITHDRAWAL_STATUS.PARTIALLY_RETURNED]: 2,
  [EXTERNAL_WITHDRAWAL_STATUS.FULLY_RETURNED]: 3,
  [EXTERNAL_WITHDRAWAL_STATUS.CHARGED]: 4,
  [EXTERNAL_WITHDRAWAL_STATUS.CANCELLED]: 5,
};

export const CUT_STATUS_ORDER: Record<string, number> = {
  [CUT_STATUS.PENDING]: 1,
  [CUT_STATUS.CUTTING]: 2,
  [CUT_STATUS.COMPLETED]: 3,
};

export const GARAGE_STATUS_ORDER: Record<string, number> = {
  [GARAGE_STATUS.ACTIVE]: 1,
  [GARAGE_STATUS.MAINTENANCE]: 2,
  [GARAGE_STATUS.INACTIVE]: 3,
};

export const CUT_ORIGIN_ORDER: Record<string, number> = {
  [CUT_ORIGIN.PLAN]: 1,
  [CUT_ORIGIN.REQUEST]: 2,
};

// =====================
// Analytics & Trends Order Maps
// =====================

export const TREND_DIRECTION_ORDER: Record<string, number> = {
  [TREND_DIRECTION.DOWN]: 1,
  [TREND_DIRECTION.STABLE]: 2,
  [TREND_DIRECTION.UP]: 3,
};

export const TREND_TYPE_ORDER: Record<string, number> = {
  [TREND_TYPE.NEGATIVE]: 1,
  [TREND_TYPE.VOLATILE]: 2,
  [TREND_TYPE.NEUTRAL]: 3,
  [TREND_TYPE.SEASONAL]: 4,
  [TREND_TYPE.POSITIVE]: 5,
};

export const PERIOD_TYPE_ORDER: Record<string, number> = {
  [PERIOD_TYPE.DAILY]: 1,
  [PERIOD_TYPE.WEEKLY]: 2,
  [PERIOD_TYPE.MONTHLY]: 3,
  [PERIOD_TYPE.QUARTERLY]: 4,
  [PERIOD_TYPE.YEARLY]: 5,
};

// =====================
// Priority & Risk Level Order Maps
// =====================

export const PRIORITY_TYPE_ORDER: Record<string, number> = {
  [PRIORITY_TYPE.LOW]: 1,
  [PRIORITY_TYPE.MEDIUM]: 2,
  [PRIORITY_TYPE.HIGH]: 3,
  [PRIORITY_TYPE.CRITICAL]: 4,
};

export const RISK_LEVEL_ORDER: Record<string, number> = {
  [RISK_LEVEL.LOW]: 1,
  [RISK_LEVEL.MEDIUM]: 2,
  [RISK_LEVEL.HIGH]: 3,
  [RISK_LEVEL.CRITICAL]: 4,
};

export const STOCK_LEVEL_ORDER: Record<string, number> = {
  [STOCK_LEVEL.NEGATIVE_STOCK]: 0,
  [STOCK_LEVEL.OUT_OF_STOCK]: 1,
  [STOCK_LEVEL.CRITICAL]: 2,
  [STOCK_LEVEL.LOW]: 3,
  [STOCK_LEVEL.OPTIMAL]: 4,
  [STOCK_LEVEL.OVERSTOCKED]: 5,
};

export const ABC_CATEGORY_ORDER: Record<string, number> = {
  [ABC_CATEGORY.A]: 1,
  [ABC_CATEGORY.B]: 2,
  [ABC_CATEGORY.C]: 3,
};

export const XYZ_CATEGORY_ORDER: Record<string, number> = {
  [XYZ_CATEGORY.X]: 1,
  [XYZ_CATEGORY.Y]: 2,
  [XYZ_CATEGORY.Z]: 3,
};

export const HEALTH_STATUS_ORDER: Record<string, number> = {
  [HEALTH_STATUS.CRITICAL]: 1,
  [HEALTH_STATUS.POOR]: 2,
  [HEALTH_STATUS.FAIR]: 3,
  [HEALTH_STATUS.GOOD]: 4,
  [HEALTH_STATUS.EXCELLENT]: 5,
};

export const PERFORMANCE_LEVEL_ORDER: Record<string, number> = {
  [PERFORMANCE_LEVEL.POOR]: 1,
  [PERFORMANCE_LEVEL.FAIR]: 2,
  [PERFORMANCE_LEVEL.GOOD]: 3,
  [PERFORMANCE_LEVEL.EXCELLENT]: 4,
};

export const URGENCY_LEVEL_ORDER: Record<string, number> = {
  [URGENCY_LEVEL.LOW]: 1,
  [URGENCY_LEVEL.MEDIUM]: 2,
  [URGENCY_LEVEL.HIGH]: 3,
  [URGENCY_LEVEL.CRITICAL]: 4,
};

export const EFFORT_LEVEL_ORDER: Record<string, number> = {
  [EFFORT_LEVEL.LOW]: 1,
  [EFFORT_LEVEL.MEDIUM]: 2,
  [EFFORT_LEVEL.HIGH]: 3,
};

export const CONFIDENCE_LEVEL_ORDER: Record<string, number> = {
  [CONFIDENCE_LEVEL.LOW]: 1,
  [CONFIDENCE_LEVEL.MEDIUM]: 2,
  [CONFIDENCE_LEVEL.HIGH]: 3,
};

export const WORKLOAD_LEVEL_ORDER: Record<string, number> = {
  [WORKLOAD_LEVEL.LOW]: 1,
  [WORKLOAD_LEVEL.NORMAL]: 2,
  [WORKLOAD_LEVEL.HIGH]: 3,
  [WORKLOAD_LEVEL.CRITICAL]: 4,
};

export const ACTIVITY_LEVEL_ORDER: Record<string, number> = {
  [ACTIVITY_LEVEL.LOST]: 1,
  [ACTIVITY_LEVEL.DORMANT]: 2,
  [ACTIVITY_LEVEL.OCCASIONAL]: 3,
  [ACTIVITY_LEVEL.ACTIVE]: 4,
  [ACTIVITY_LEVEL.VERY_ACTIVE]: 5,
};

// =====================
// Type Categories Order Maps
// =====================

export const VACATION_TYPE_ORDER: Record<string, number> = {
  [VACATION_TYPE.ANNUAL]: 1,
  [VACATION_TYPE.COLLECTIVE]: 2,
  [VACATION_TYPE.MEDICAL]: 3,
  [VACATION_TYPE.MATERNITY]: 4,
  [VACATION_TYPE.PATERNITY]: 5,
  [VACATION_TYPE.EMERGENCY]: 6,
  [VACATION_TYPE.STUDY]: 7,
  [VACATION_TYPE.UNPAID]: 8,
  [VACATION_TYPE.OTHER]: 9,
};

export const WARNING_SEVERITY_ORDER: Record<string, number> = {
  [WARNING_SEVERITY.VERBAL]: 1,
  [WARNING_SEVERITY.WRITTEN]: 2,
  [WARNING_SEVERITY.SUSPENSION]: 3,
  [WARNING_SEVERITY.FINAL_WARNING]: 4,
};

export const WARNING_CATEGORY_ORDER: Record<string, number> = {
  [WARNING_CATEGORY.SAFETY]: 1,
  [WARNING_CATEGORY.MISCONDUCT]: 2,
  [WARNING_CATEGORY.INSUBORDINATION]: 3,
  [WARNING_CATEGORY.POLICY_VIOLATION]: 4,
  [WARNING_CATEGORY.ATTENDANCE]: 5,
  [WARNING_CATEGORY.PERFORMANCE]: 6,
  [WARNING_CATEGORY.BEHAVIOR]: 7,
  [WARNING_CATEGORY.OTHER]: 8,
};

export const NOTIFICATION_IMPORTANCE_ORDER: Record<string, number> = {
  [NOTIFICATION_IMPORTANCE.LOW]: 1,
  [NOTIFICATION_IMPORTANCE.NORMAL]: 2,
  [NOTIFICATION_IMPORTANCE.HIGH]: 3,
  [NOTIFICATION_IMPORTANCE.URGENT]: 4,
};

export const VALIDATION_SEVERITY_ORDER: Record<string, number> = {
  [VALIDATION_SEVERITY.INFO]: 1,
  [VALIDATION_SEVERITY.WARNING]: 2,
  [VALIDATION_SEVERITY.ERROR]: 3,
};

// =====================
// Calendar Order Maps
// =====================

export const DAY_OF_WEEK_ORDER: Record<string, number> = {
  [DAY_OF_WEEK.SUNDAY]: 1,
  [DAY_OF_WEEK.MONDAY]: 2,
  [DAY_OF_WEEK.TUESDAY]: 3,
  [DAY_OF_WEEK.WEDNESDAY]: 4,
  [DAY_OF_WEEK.THURSDAY]: 5,
  [DAY_OF_WEEK.FRIDAY]: 6,
  [DAY_OF_WEEK.SATURDAY]: 7,
};

export const MONTH_ORDER: Record<string, number> = {
  [MONTH.JANUARY]: 1,
  [MONTH.FEBRUARY]: 2,
  [MONTH.MARCH]: 3,
  [MONTH.APRIL]: 4,
  [MONTH.MAY]: 5,
  [MONTH.JUNE]: 6,
  [MONTH.JULY]: 7,
  [MONTH.AUGUST]: 8,
  [MONTH.SEPTEMBER]: 9,
  [MONTH.OCTOBER]: 10,
  [MONTH.NOVEMBER]: 11,
  [MONTH.DECEMBER]: 12,
};

export const MONTH_OCCURRENCE_ORDER: Record<string, number> = {
  [MONTH_OCCURRENCE.FIRST]: 1,
  [MONTH_OCCURRENCE.SECOND]: 2,
  [MONTH_OCCURRENCE.THIRD]: 3,
  [MONTH_OCCURRENCE.FOURTH]: 4,
  [MONTH_OCCURRENCE.LAST]: 5,
};

export const SCHEDULE_FREQUENCY_ORDER: Record<string, number> = {
  [SCHEDULE_FREQUENCY.ONCE]: 1,
  [SCHEDULE_FREQUENCY.DAILY]: 2,
  [SCHEDULE_FREQUENCY.WEEKLY]: 3,
  [SCHEDULE_FREQUENCY.BIWEEKLY]: 4,
  [SCHEDULE_FREQUENCY.MONTHLY]: 5,
  [SCHEDULE_FREQUENCY.BIMONTHLY]: 6,
  [SCHEDULE_FREQUENCY.QUARTERLY]: 7,
  [SCHEDULE_FREQUENCY.TRIANNUAL]: 8,
  [SCHEDULE_FREQUENCY.QUADRIMESTRAL]: 9,
  [SCHEDULE_FREQUENCY.SEMI_ANNUAL]: 10,
  [SCHEDULE_FREQUENCY.ANNUAL]: 11,
  [SCHEDULE_FREQUENCY.CUSTOM]: 12,
};

// =====================
// Size Order Maps
// =====================

export const PANTS_SIZE_ORDER: Record<string, number> = {
  [PANTS_SIZE.SIZE_36]: 1,
  [PANTS_SIZE.SIZE_38]: 2,
  [PANTS_SIZE.SIZE_40]: 3,
  [PANTS_SIZE.SIZE_42]: 4,
  [PANTS_SIZE.SIZE_44]: 5,
  [PANTS_SIZE.SIZE_46]: 6,
  [PANTS_SIZE.SIZE_48]: 7,
};

export const SHIRT_SIZE_ORDER: Record<SHIRT_SIZE, number> = {
  [SHIRT_SIZE.P]: 1,
  [SHIRT_SIZE.M]: 2,
  [SHIRT_SIZE.G]: 3,
  [SHIRT_SIZE.GG]: 4,
  [SHIRT_SIZE.XG]: 5,
};

export const BOOT_SIZE_ORDER: Record<string, number> = {
  [BOOT_SIZE.SIZE_36]: 1,
  [BOOT_SIZE.SIZE_38]: 2,
  [BOOT_SIZE.SIZE_40]: 3,
  [BOOT_SIZE.SIZE_42]: 4,
  [BOOT_SIZE.SIZE_44]: 5,
  [BOOT_SIZE.SIZE_46]: 6,
  [BOOT_SIZE.SIZE_48]: 7,
};

export const MASK_SIZE_ORDER: Record<string, number> = {
  [MASK_SIZE.P]: 1,
  [MASK_SIZE.M]: 2,
};

export const SLEEVES_SIZE_ORDER: Record<string, number> = {
  [SLEEVES_SIZE.P]: 1,
  [SLEEVES_SIZE.M]: 2,
  [SLEEVES_SIZE.G]: 3,
  [SLEEVES_SIZE.GG]: 4,
  [SLEEVES_SIZE.XG]: 5,
};

export const PPE_SIZE_ORDER: Record<string, number> = {
  [PPE_SIZE.P]: 1,
  [PPE_SIZE.M]: 2,
  [PPE_SIZE.G]: 3,
  [PPE_SIZE.GG]: 4,
  [PPE_SIZE.XG]: 5,
  [PPE_SIZE.SIZE_36]: 6,
  [PPE_SIZE.SIZE_38]: 7,
  [PPE_SIZE.SIZE_40]: 8,
  [PPE_SIZE.SIZE_42]: 9,
  [PPE_SIZE.SIZE_44]: 10,
  [PPE_SIZE.SIZE_46]: 11,
  [PPE_SIZE.SIZE_48]: 12,
};

// =====================
// Paint Order Maps
// =====================

// PAINT_TYPE_ORDER is no longer used
// Paint types are managed dynamically in the database

export const PAINT_TYPE_ENUM_ORDER: Record<string, number> = {
  [PAINT_TYPE_ENUM.POLYESTER]: 1,
  [PAINT_TYPE_ENUM.ACRYLIC]: 2,
  [PAINT_TYPE_ENUM.LACQUER]: 3,
  [PAINT_TYPE_ENUM.POLYURETHANE]: 4,
  [PAINT_TYPE_ENUM.EPOXY]: 5,
};

export const PAINT_BRAND_ORDER: Record<string, number> = {
  [PAINT_BRAND.PPG]: 1,
  [PAINT_BRAND.FARBEN]: 2,
  [PAINT_BRAND.LAZZURIL]: 3,
};

export const PAINT_FINISH_ORDER: Record<string, number> = {
  [PAINT_FINISH.SOLID]: 1,
  [PAINT_FINISH.METALLIC]: 2,
  [PAINT_FINISH.PEARL]: 3,
};

export const TRUCK_MANUFACTURER_ORDER: Record<string, number> = {
  [TRUCK_MANUFACTURER.VOLKSWAGEN]: 1,
  [TRUCK_MANUFACTURER.MERCEDES_BENZ]: 2,
  [TRUCK_MANUFACTURER.SCANIA]: 3,
  [TRUCK_MANUFACTURER.VOLVO]: 4,
  [TRUCK_MANUFACTURER.DAF]: 5,
  [TRUCK_MANUFACTURER.IVECO]: 6,
};

// =====================
// Operations & Actions Order Maps
// =====================

export const ACTIVITY_OPERATION_ORDER: Record<string, number> = {
  [ACTIVITY_OPERATION.OUTBOUND]: 1,
  [ACTIVITY_OPERATION.INBOUND]: 2,
};

export const AUDIT_ACTION_ORDER: Record<string, number> = {
  [AUDIT_ACTION.CREATE]: 1,
  [AUDIT_ACTION.UPDATE]: 2,
  [AUDIT_ACTION.DELETE]: 3,
};

export const CHANGE_ACTION_ORDER: Record<string, number> = {
  [CHANGE_ACTION.CREATE]: 1,
  [CHANGE_ACTION.UPDATE]: 2,
  [CHANGE_ACTION.DELETE]: 3,
  [CHANGE_ACTION.RESTORE]: 4,
  [CHANGE_ACTION.ARCHIVE]: 5,
  [CHANGE_ACTION.UNARCHIVE]: 6,
  [CHANGE_ACTION.ACTIVATE]: 7,
  [CHANGE_ACTION.DEACTIVATE]: 8,
  [CHANGE_ACTION.APPROVE]: 9,
  [CHANGE_ACTION.REJECT]: 10,
  [CHANGE_ACTION.CANCEL]: 11,
  [CHANGE_ACTION.COMPLETE]: 12,
  [CHANGE_ACTION.RESCHEDULE]: 13,
};

export const EVENT_TYPE_ORDER: Record<string, number> = {
  [EVENT_TYPE.CREATED]: 1,
  [EVENT_TYPE.STARTED]: 2,
  [EVENT_TYPE.PAUSED]: 3,
  [EVENT_TYPE.RESUMED]: 4,
  [EVENT_TYPE.COMPLETED]: 5,
  [EVENT_TYPE.CANCELLED]: 6,
};

export const TIMELINE_EVENT_TYPE_ORDER: Record<string, number> = {
  [TIMELINE_EVENT_TYPE.CREATED]: 1,
  [TIMELINE_EVENT_TYPE.ASSIGNED]: 2,
  [TIMELINE_EVENT_TYPE.UPDATED]: 3,
  [TIMELINE_EVENT_TYPE.STATUS_CHANGED]: 4,
  [TIMELINE_EVENT_TYPE.FILE_ADDED]: 5,
  [TIMELINE_EVENT_TYPE.FILE_REMOVED]: 6,
  [TIMELINE_EVENT_TYPE.NOTE_ADDED]: 7,
  [TIMELINE_EVENT_TYPE.COMPLETED]: 8,
};

// =====================
// Notification & Channel Order Maps
// =====================

export const NOTIFICATION_TYPE_ORDER: Record<string, number> = {
  [NOTIFICATION_TYPE.SYSTEM]: 1,
  [NOTIFICATION_TYPE.TASK]: 2,
  [NOTIFICATION_TYPE.ORDER]: 3,
  [NOTIFICATION_TYPE.PPE]: 4,
  [NOTIFICATION_TYPE.VACATION]: 5,
  [NOTIFICATION_TYPE.WARNING]: 6,
  [NOTIFICATION_TYPE.STOCK]: 7,
  [NOTIFICATION_TYPE.GENERAL]: 8,
};

export const NOTIFICATION_CHANNEL_ORDER: Record<string, number> = {
  [NOTIFICATION_CHANNEL.IN_APP]: 1,
  [NOTIFICATION_CHANNEL.EMAIL]: 2,
  [NOTIFICATION_CHANNEL.PUSH]: 3,
  [NOTIFICATION_CHANNEL.SMS]: 4,
};

export const FILE_ENTITY_TYPE_ORDER: Record<string, number> = {
  [FILE_ENTITY_TYPE.TASK]: 1,
  [FILE_ENTITY_TYPE.ORDER_BUDGET]: 2,
  [FILE_ENTITY_TYPE.ORDER_NFE]: 3,
  [FILE_ENTITY_TYPE.ORDER_RECEIPT]: 4,
  [FILE_ENTITY_TYPE.TASK_BUDGET]: 5,
  [FILE_ENTITY_TYPE.TASK_NFE]: 6,
  [FILE_ENTITY_TYPE.TASK_RECEIPT]: 7,
  [FILE_ENTITY_TYPE.CUSTOMER_LOGO]: 8,
  [FILE_ENTITY_TYPE.SUPPLIER_LOGO]: 9,
  [FILE_ENTITY_TYPE.OBSERVATION]: 10,
  [FILE_ENTITY_TYPE.WARNING]: 11,
  [FILE_ENTITY_TYPE.AIRBRUSHING_RECEIPT]: 12,
  [FILE_ENTITY_TYPE.AIRBRUSHING_NFE]: 13,
  [FILE_ENTITY_TYPE.EXTERNAL_WITHDRAWAL_BUDGET]: 14,
  [FILE_ENTITY_TYPE.EXTERNAL_WITHDRAWAL_NFE]: 15,
  [FILE_ENTITY_TYPE.EXTERNAL_WITHDRAWAL_RECEIPT]: 16,
};

// =====================
// Other Order Maps
// =====================

export const PERCENTAGE_ADJUST_TYPE_ORDER: Record<string, number> = {
  [PERCENTAGE_ADJUST_TYPE.DECREASE]: 1,
  [PERCENTAGE_ADJUST_TYPE.INCREASE]: 2,
};

export const EXPORT_FORMAT_ORDER: Record<string, number> = {
  [EXPORT_FORMAT.CSV]: 1,
  [EXPORT_FORMAT.EXCEL]: 2,
  [EXPORT_FORMAT.JSON]: 3,
  [EXPORT_FORMAT.PDF]: 4,
};

export const FILE_FORMAT_ORDER: Record<string, number> = {
  [FILE_FORMAT.CSV]: 1,
  [FILE_FORMAT.EXCEL]: 2,
  [FILE_FORMAT.JSON]: 3,
  [FILE_FORMAT.YAML]: 4,
  [FILE_FORMAT.PDF]: 5,
};

export const PPE_DELIVERY_MODE_ORDER: Record<string, number> = {
  [PPE_DELIVERY_MODE.ON_DEMAND]: 1,
  [PPE_DELIVERY_MODE.SCHEDULED]: 2,
  [PPE_DELIVERY_MODE.BOTH]: 3,
};

export const PPE_TYPE_ORDER: Record<string, number> = {
  [PPE_TYPE.SHIRT]: 1,
  [PPE_TYPE.PANTS]: 2,
  [PPE_TYPE.BOOTS]: 3,
  [PPE_TYPE.SLEEVES]: 4,
  [PPE_TYPE.MASK]: 5,
  [PPE_TYPE.GLOVES]: 6,
  [PPE_TYPE.RAIN_BOOTS]: 7,
};

export const PPE_SIZE_TYPE_ORDER: Record<string, number> = {
  [PPE_SIZE_TYPE.SHIRT]: 1,
  [PPE_SIZE_TYPE.PANTS]: 2,
  [PPE_SIZE_TYPE.BOOT]: 3,
  [PPE_SIZE_TYPE.GLOVE]: 4,
  [PPE_SIZE_TYPE.MASK]: 5,
  [PPE_SIZE_TYPE.OVERALL]: 6,
  [PPE_SIZE_TYPE.HELMET]: 7,
  [PPE_SIZE_TYPE.UNIFORM]: 8,
};

export const ORDER_TRIGGER_TYPE_ORDER: Record<string, number> = {
  [ORDER_TRIGGER_TYPE.STOCK_LEVEL]: 1,
  [ORDER_TRIGGER_TYPE.CONSUMPTION_RATE]: 2,
  [ORDER_TRIGGER_TYPE.SCHEDULED]: 3,
};

export const COLOR_SCHEMA_ORDER: Record<string, number> = {
  [COLOR_SCHEMA.LIGHT]: 1,
  [COLOR_SCHEMA.DARK]: 2,
  [COLOR_SCHEMA.SYSTEM]: 3,
};

export const VERIFICATION_TYPE_ORDER: Record<string, number> = {
  [VERIFICATION_TYPE.EMAIL]: 1,
  [VERIFICATION_TYPE.PHONE]: 2,
  [VERIFICATION_TYPE.PASSWORD_RESET]: 3,
};

export const VERIFICATION_ERROR_SEVERITY_ORDER: Record<string, number> = {
  [VERIFICATION_ERROR_SEVERITY.LOW]: 1,
  [VERIFICATION_ERROR_SEVERITY.MEDIUM]: 2,
  [VERIFICATION_ERROR_SEVERITY.HIGH]: 3,
  [VERIFICATION_ERROR_SEVERITY.CRITICAL]: 4,
};

export const VERIFICATION_ERROR_CATEGORY_ORDER: Record<string, number> = {
  [VERIFICATION_ERROR_CATEGORY.VALIDATION]: 1,
  [VERIFICATION_ERROR_CATEGORY.AUTHENTICATION]: 2,
  [VERIFICATION_ERROR_CATEGORY.RATE_LIMITING]: 3,
  [VERIFICATION_ERROR_CATEGORY.EXTERNAL_SERVICE]: 4,
  [VERIFICATION_ERROR_CATEGORY.SYSTEM]: 5,
  [VERIFICATION_ERROR_CATEGORY.SECURITY]: 6,
};

export const MERGE_STRATEGY_ORDER: Record<string, number> = {
  [MERGE_STRATEGY.KEEP_PRIMARY]: 1,
  [MERGE_STRATEGY.KEEP_NEWEST]: 2,
  [MERGE_STRATEGY.MANUAL]: 3,
};

export const GROUP_BY_ORDER: Record<string, number> = {
  [GROUP_BY.DAY]: 1,
  [GROUP_BY.WEEK]: 2,
  [GROUP_BY.MONTH]: 3,
  [GROUP_BY.YEAR]: 4,
  [GROUP_BY.ITEM]: 5,
  [GROUP_BY.USER]: 6,
};

export const HOLIDAY_TYPE_ORDER: Record<string, number> = {
  [HOLIDAY_TYPE.NATIONAL]: 1,
  [HOLIDAY_TYPE.STATE]: 2,
  [HOLIDAY_TYPE.MUNICIPAL]: 3,
  [HOLIDAY_TYPE.OPTIONAL]: 4,
};

export const TIME_RANGE_ORDER: Record<string, number> = {
  [TIME_RANGE.LAST_7_DAYS]: 1,
  [TIME_RANGE.LAST_30_DAYS]: 2,
  [TIME_RANGE.LAST_90_DAYS]: 3,
  [TIME_RANGE.LAST_YEAR]: 4,
  [TIME_RANGE.CUSTOM]: 5,
};

export const TASK_OBSERVATION_TYPE_ORDER: Record<string, number> = {
  [TASK_OBSERVATION_TYPE.DAMAGE]: 1,
  [TASK_OBSERVATION_TYPE.OVERDUE]: 2,
  [TASK_OBSERVATION_TYPE.QUALITY]: 3,
};

export const ITEM_ISSUE_TYPE_ORDER: Record<string, number> = {
  [ITEM_ISSUE_TYPE.SHORTAGE]: 1,
  [ITEM_ISSUE_TYPE.DAMAGE]: 2,
  [ITEM_ISSUE_TYPE.MISMATCH]: 3,
  [ITEM_ISSUE_TYPE.OVERAGE]: 4,
};

export const ITEM_CATEGORY_TYPE_ORDER: Record<string, number> = {
  [ITEM_CATEGORY_TYPE.REGULAR]: 1,
  [ITEM_CATEGORY_TYPE.PPE]: 2,
  [ITEM_CATEGORY_TYPE.TOOL]: 3,
};

// =====================
// Activity Reason Order Map
// =====================

export const ACTIVITY_REASON_ORDER: Record<string, number> = {
  [ACTIVITY_REASON.ORDER_RECEIVED]: 1,
  [ACTIVITY_REASON.PRODUCTION_USAGE]: 2,
  [ACTIVITY_REASON.PPE_DELIVERY]: 3,
  [ACTIVITY_REASON.BORROW]: 4,
  [ACTIVITY_REASON.RETURN]: 5,
  [ACTIVITY_REASON.EXTERNAL_WITHDRAWAL]: 6,
  [ACTIVITY_REASON.EXTERNAL_WITHDRAWAL_RETURN]: 7,
  [ACTIVITY_REASON.INVENTORY_COUNT]: 8,
  [ACTIVITY_REASON.MANUAL_ADJUSTMENT]: 9,
  [ACTIVITY_REASON.MAINTENANCE]: 10,
  [ACTIVITY_REASON.DAMAGE]: 11,
  [ACTIVITY_REASON.LOSS]: 12,
  [ACTIVITY_REASON.PAINT_PRODUCTION]: 13,
  [ACTIVITY_REASON.OTHER]: 14,
};

// =====================
// Entity Type Order Map
// =====================

export const ENTITY_TYPE_ORDER: Record<string, number> = {
  [ENTITY_TYPE.USER]: 1,
  [ENTITY_TYPE.SUPPLIER]: 2,
  [ENTITY_TYPE.ITEM]: 3,
  [ENTITY_TYPE.TASK]: 4,
  [ENTITY_TYPE.ORDER]: 5,
  [ENTITY_TYPE.ORDER_ITEM]: 6,
  [ENTITY_TYPE.SERVICE_ORDER]: 7,
  [ENTITY_TYPE.ACTIVITY]: 8,
  [ENTITY_TYPE.BORROW]: 9,
  [ENTITY_TYPE.EXTERNAL_WITHDRAWAL]: 10,
  [ENTITY_TYPE.EXTERNAL_WITHDRAWAL_ITEM]: 11,
  [ENTITY_TYPE.VACATION]: 12,
  [ENTITY_TYPE.WARNING]: 13,
  [ENTITY_TYPE.PPE_DELIVERY]: 14,
  [ENTITY_TYPE.COMMISSION]: 15,
  [ENTITY_TYPE.DISCOUNT]: 16,
  [ENTITY_TYPE.LAYOUT]: 17,
  [ENTITY_TYPE.PAYROLL]: 18,
};

export const CHANGE_LOG_ENTITY_TYPE_ORDER: Record<string, number> = {
  [CHANGE_LOG_ENTITY_TYPE.USER]: 1,
  [CHANGE_LOG_ENTITY_TYPE.SUPPLIER]: 2,
  [CHANGE_LOG_ENTITY_TYPE.ITEM]: 3,
  [CHANGE_LOG_ENTITY_TYPE.TASK]: 4,
  [CHANGE_LOG_ENTITY_TYPE.ORDER]: 5,
  [CHANGE_LOG_ENTITY_TYPE.ORDER_ITEM]: 6,
  [CHANGE_LOG_ENTITY_TYPE.SERVICE_ORDER]: 7,
  [CHANGE_LOG_ENTITY_TYPE.ACTIVITY]: 8,
  [CHANGE_LOG_ENTITY_TYPE.BORROW]: 9,
  [CHANGE_LOG_ENTITY_TYPE.EXTERNAL_WITHDRAWAL]: 10,
  [CHANGE_LOG_ENTITY_TYPE.EXTERNAL_WITHDRAWAL_ITEM]: 11,
  [CHANGE_LOG_ENTITY_TYPE.PPE_DELIVERY]: 12,
  [CHANGE_LOG_ENTITY_TYPE.PPE_DELIVERY_ITEM]: 13,
  [CHANGE_LOG_ENTITY_TYPE.PPE_REQUEST]: 14,
  [CHANGE_LOG_ENTITY_TYPE.PPE_DELIVERY_SCHEDULE]: 15,
  [CHANGE_LOG_ENTITY_TYPE.PPE_SIZE]: 16,
  [CHANGE_LOG_ENTITY_TYPE.CUT]: 17,
  [CHANGE_LOG_ENTITY_TYPE.CUT_ITEM]: 18,
  [CHANGE_LOG_ENTITY_TYPE.CUT_PLAN]: 19,
  [CHANGE_LOG_ENTITY_TYPE.CUT_REQUEST]: 20,
  [CHANGE_LOG_ENTITY_TYPE.DELIVERY]: 21,
  [CHANGE_LOG_ENTITY_TYPE.FILE]: 22,
  [CHANGE_LOG_ENTITY_TYPE.GARAGE_LANE]: 23,
  [CHANGE_LOG_ENTITY_TYPE.ITEM_BRAND]: 24,
  [CHANGE_LOG_ENTITY_TYPE.ITEM_CATEGORY]: 25,
  [CHANGE_LOG_ENTITY_TYPE.MAINTENANCE]: 26,
  [CHANGE_LOG_ENTITY_TYPE.MAINTENANCE_ITEM]: 27,
  [CHANGE_LOG_ENTITY_TYPE.MAINTENANCE_SCHEDULE]: 28,
  [CHANGE_LOG_ENTITY_TYPE.NOTIFICATION]: 29,
  [CHANGE_LOG_ENTITY_TYPE.ORDER_RULE]: 30,
  [CHANGE_LOG_ENTITY_TYPE.ORDER_SCHEDULE]: 31,
  [CHANGE_LOG_ENTITY_TYPE.PAINT]: 32,
  [CHANGE_LOG_ENTITY_TYPE.PAINT_TYPE]: 34,
  [CHANGE_LOG_ENTITY_TYPE.SERVICE]: 35,
  [CHANGE_LOG_ENTITY_TYPE.PAINT_GROUND]: 36,
  [CHANGE_LOG_ENTITY_TYPE.PAINT_FORMULA]: 37,
  [CHANGE_LOG_ENTITY_TYPE.PAINT_FORMULA_COMPONENT]: 38,
  [CHANGE_LOG_ENTITY_TYPE.PAINT_PRODUCTION]: 39,
  [CHANGE_LOG_ENTITY_TYPE.PARKING_SPOT]: 40,
  [CHANGE_LOG_ENTITY_TYPE.PIECE]: 41,
  [CHANGE_LOG_ENTITY_TYPE.POSITION]: 42,
  [CHANGE_LOG_ENTITY_TYPE.PRODUCTION]: 43,
  [CHANGE_LOG_ENTITY_TYPE.PURCHASE]: 44,
  [CHANGE_LOG_ENTITY_TYPE.WARNING]: 45,
  [CHANGE_LOG_ENTITY_TYPE.SECTOR]: 46,
  [CHANGE_LOG_ENTITY_TYPE.TRUCK]: 47,
  [CHANGE_LOG_ENTITY_TYPE.VACATION]: 48,
  [CHANGE_LOG_ENTITY_TYPE.PPE_CONFIG]: 49,
  [CHANGE_LOG_ENTITY_TYPE.PRICE]: 50,
  [CHANGE_LOG_ENTITY_TYPE.HOLIDAY]: 51,
  [CHANGE_LOG_ENTITY_TYPE.CUSTOMER]: 52,
  [CHANGE_LOG_ENTITY_TYPE.SEEN_NOTIFICATION]: 53,
  [CHANGE_LOG_ENTITY_TYPE.NOTIFICATION_PREFERENCE]: 54,
  [CHANGE_LOG_ENTITY_TYPE.VERIFICATION]: 55,
  [CHANGE_LOG_ENTITY_TYPE.AIRBRUSHING]: 56,
  [CHANGE_LOG_ENTITY_TYPE.CATEGORY]: 57,
  [CHANGE_LOG_ENTITY_TYPE.COLLECTION]: 58,
  [CHANGE_LOG_ENTITY_TYPE.TIME_CLOCK_ENTRY]: 59,
  [CHANGE_LOG_ENTITY_TYPE.LAYOUT]: 60,
  [CHANGE_LOG_ENTITY_TYPE.COMMISSION]: 61,
  [CHANGE_LOG_ENTITY_TYPE.DISCOUNT]: 62,
  [CHANGE_LOG_ENTITY_TYPE.PAYROLL]: 63,
};

// =====================
// Alert Type Order Map (Grouped by category)
// =====================

export const ALERT_TYPE_ORDER: Record<string, number> = {
  // Activity Alerts (1-10)
  [ALERT_TYPE.HIGH_SPENDING]: 1,
  [ALERT_TYPE.UNUSUAL_PATTERN]: 2,
  [ALERT_TYPE.DISCREPANCY]: 3,
  [ALERT_TYPE.LOW_STOCK]: 4,

  // Item Alerts (11-20)
  [ALERT_TYPE.STOCK_OUT]: 11,
  [ALERT_TYPE.OVERSTOCK]: 12,
  [ALERT_TYPE.SLOW_MOVING]: 13,
  [ALERT_TYPE.REORDER_NEEDED]: 14,

  // User Alerts (21-30)
  [ALERT_TYPE.HIGH_TURNOVER]: 21,
  [ALERT_TYPE.ATTENDANCE_ISSUE]: 22,

  // Order Alerts (31-40)
  [ALERT_TYPE.DELIVERY_DELAY]: 31,

  // Customer Alerts (41-50)
  [ALERT_TYPE.SERVICE_ISSUE]: 41,
  [ALERT_TYPE.PAYMENT_DELAY]: 42,

  // Task Alerts (51-60)
  [ALERT_TYPE.OVERDUE]: 51,
  [ALERT_TYPE.CUSTOMER_COMPLAINT]: 52,

  // Borrow Alerts (61-70)
  [ALERT_TYPE.HIGH_DEMAND]: 61,
  [ALERT_TYPE.USER_VIOLATION]: 62,

  // Vacation Alerts (71-80)
  [ALERT_TYPE.EXPIRING_DAYS]: 71,
  [ALERT_TYPE.PLANNING_CONFLICT]: 72,

  // Warning Alerts (81-90)
  [ALERT_TYPE.REPEAT_OFFENDER]: 81,
  [ALERT_TYPE.ESCALATION_NEEDED]: 82,
  [ALERT_TYPE.PATTERN_DETECTED]: 83,

  // PPE Alerts (91-100)
  [ALERT_TYPE.STOCK_SHORTAGE]: 91,
  [ALERT_TYPE.MISSING_DELIVERY]: 92,

  // Supplier Alerts (101-110)
  [ALERT_TYPE.DELIVERY_DELAYS]: 101,
};

// =====================
// Sector Privileges Order Map
// =====================

export const SECTOR_PRIVILEGES_ORDER: Record<SECTOR_PRIVILEGES, number> = {
  [SECTOR_PRIVILEGES.BASIC]: 1,
  [SECTOR_PRIVILEGES.PRODUCTION]: 2,
  [SECTOR_PRIVILEGES.LEADER]: 3,
  [SECTOR_PRIVILEGES.MAINTENANCE]: 4,
  [SECTOR_PRIVILEGES.WAREHOUSE]: 5,
  [SECTOR_PRIVILEGES.FINANCIAL]: 6,
  [SECTOR_PRIVILEGES.ADMIN]: 7,
  [SECTOR_PRIVILEGES.HUMAN_RESOURCES]: 8,
  [SECTOR_PRIVILEGES.EXTERNAL]: 9,
};

// =====================
// Chart Type Order Map
// =====================

export const CHART_TYPE_ORDER: Record<CHART_TYPE, number> = {
  [CHART_TYPE.PIE]: 1,
  [CHART_TYPE.DONUT]: 2,
  [CHART_TYPE.AREA]: 3,
  [CHART_TYPE.BAR]: 4,
  [CHART_TYPE.LINE]: 5,
  [CHART_TYPE.STACKED]: 6,
};

// =====================
// Measure Unit Order Map
// =====================

export const MEASURE_UNIT_ORDER: Record<MEASURE_UNIT, number> = {
  // Weight units (smallest to largest)
  [MEASURE_UNIT.GRAM]: 1,
  [MEASURE_UNIT.KILOGRAM]: 2,

  // Volume units (smallest to largest)
  [MEASURE_UNIT.MILLILITER]: 3,
  [MEASURE_UNIT.CUBIC_CENTIMETER]: 4,
  [MEASURE_UNIT.LITER]: 5,
  [MEASURE_UNIT.CUBIC_METER]: 6,

  // Length units (smallest to largest)
  [MEASURE_UNIT.MILLIMETER]: 7,
  [MEASURE_UNIT.CENTIMETER]: 8,
  [MEASURE_UNIT.INCHES]: 9,
  [MEASURE_UNIT.METER]: 10,

  // Area units (smallest to largest)
  [MEASURE_UNIT.SQUARE_CENTIMETER]: 11,
  [MEASURE_UNIT.SQUARE_METER]: 12,

  // Count units (smallest to largest)
  [MEASURE_UNIT.UNIT]: 13,
  [MEASURE_UNIT.PAIR]: 14,
  [MEASURE_UNIT.DOZEN]: 15,
  [MEASURE_UNIT.HUNDRED]: 16,
  [MEASURE_UNIT.THOUSAND]: 17,

  // Container and packaging units
  [MEASURE_UNIT.PACKAGE]: 18,
  [MEASURE_UNIT.SACK]: 19,
  [MEASURE_UNIT.BOX]: 20,
  [MEASURE_UNIT.ROLL]: 21,
  [MEASURE_UNIT.SHEET]: 22,
  [MEASURE_UNIT.SET]: 23,

  // Diameter units (fractional inches - smallest to largest)
  [MEASURE_UNIT.INCH_1_8]: 24,
  [MEASURE_UNIT.INCH_1_4]: 25,
  [MEASURE_UNIT.INCH_3_8]: 26,
  [MEASURE_UNIT.INCH_1_2]: 27,
  [MEASURE_UNIT.INCH_5_8]: 28,
  [MEASURE_UNIT.INCH_3_4]: 29,
  [MEASURE_UNIT.INCH_7_8]: 30,
  [MEASURE_UNIT.INCH_1]: 31,
  [MEASURE_UNIT.INCH_1_1_4]: 32,
  [MEASURE_UNIT.INCH_1_1_2]: 33,
  [MEASURE_UNIT.INCH_2]: 34,

  // Thread pitch units
  [MEASURE_UNIT.THREAD_MM]: 35,
  [MEASURE_UNIT.THREAD_TPI]: 36,

  // Electrical units
  [MEASURE_UNIT.WATT]: 37,
  [MEASURE_UNIT.VOLT]: 38,
  [MEASURE_UNIT.AMPERE]: 39,

  // PPE Size units (letter sizes)
  [MEASURE_UNIT.P]: 40,
  [MEASURE_UNIT.M]: 41,
  [MEASURE_UNIT.G]: 42,
  [MEASURE_UNIT.GG]: 43,
  [MEASURE_UNIT.XG]: 44,
};

export const MEASURE_TYPE_ORDER: Record<MEASURE_TYPE, number> = {
  [MEASURE_TYPE.WEIGHT]: 1,
  [MEASURE_TYPE.VOLUME]: 2,
  [MEASURE_TYPE.LENGTH]: 3,
  [MEASURE_TYPE.AREA]: 4,
  [MEASURE_TYPE.COUNT]: 5,
  [MEASURE_TYPE.DIAMETER]: 6,
  [MEASURE_TYPE.THREAD]: 7,
  [MEASURE_TYPE.ELECTRICAL]: 8,
  [MEASURE_TYPE.SIZE]: 9,
};

// =====================
// Change Triggered By Order Map
// =====================

export const CHANGE_TRIGGERED_BY_ORDER: Record<string, number> = {
  [CHANGE_TRIGGERED_BY.TASK_CREATE]: 1,
  [CHANGE_TRIGGERED_BY.TASK_UPDATE]: 2,
  [CHANGE_TRIGGERED_BY.USER_ACTION]: 3,
  [CHANGE_TRIGGERED_BY.BATCH_CREATE]: 4,
  [CHANGE_TRIGGERED_BY.BATCH_UPDATE]: 5,
  [CHANGE_TRIGGERED_BY.BATCH_DELETE]: 6,
  [CHANGE_TRIGGERED_BY.BATCH_OPERATION]: 7,
  [CHANGE_TRIGGERED_BY.SYSTEM]: 8,
  [CHANGE_TRIGGERED_BY.USER]: 9,
  [CHANGE_TRIGGERED_BY.EXTERNAL_WITHDRAWAL]: 10,
  [CHANGE_TRIGGERED_BY.EXTERNAL_WITHDRAWAL_DELETE]: 11,
  [CHANGE_TRIGGERED_BY.EXTERNAL_WITHDRAWAL_RETURN]: 12,
  [CHANGE_TRIGGERED_BY.EXTERNAL_WITHDRAWAL_ITEM]: 13,
  [CHANGE_TRIGGERED_BY.EXTERNAL_WITHDRAWAL_ITEM_UPDATE]: 14,
  [CHANGE_TRIGGERED_BY.EXTERNAL_WITHDRAWAL_ITEM_DELETE]: 15,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_COMPONENT_CREATE]: 16,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_COMPONENT_UPDATE]: 17,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_COMPONENT_DELETE]: 18,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_COMPONENT_BATCH_CREATE]: 19,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_COMPONENT_BATCH_UPDATE]: 20,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_COMPONENT_BATCH_DELETE]: 21,
  [CHANGE_TRIGGERED_BY.PAINT_PRODUCTION_CREATE]: 22,
  [CHANGE_TRIGGERED_BY.PAINT_PRODUCTION_UPDATE]: 23,
  [CHANGE_TRIGGERED_BY.PAINT_PRODUCTION_DELETE]: 24,
  [CHANGE_TRIGGERED_BY.PAINT_PRODUCTION_BATCH_CREATE]: 25,
  [CHANGE_TRIGGERED_BY.PAINT_PRODUCTION_BATCH_UPDATE]: 26,
  [CHANGE_TRIGGERED_BY.PAINT_PRODUCTION_BATCH_DELETE]: 27,
  [CHANGE_TRIGGERED_BY.PAINT_CREATE]: 28,
  [CHANGE_TRIGGERED_BY.PAINT_UPDATE]: 29,
  [CHANGE_TRIGGERED_BY.PAINT_DELETE]: 30,
  [CHANGE_TRIGGERED_BY.PAINT_BATCH_CREATE]: 31,
  [CHANGE_TRIGGERED_BY.PAINT_BATCH_UPDATE]: 32,
  [CHANGE_TRIGGERED_BY.PAINT_BATCH_DELETE]: 33,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_CREATE]: 34,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_UPDATE]: 35,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_DELETE]: 36,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_BATCH_CREATE]: 37,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_BATCH_UPDATE]: 38,
  [CHANGE_TRIGGERED_BY.PAINT_FORMULA_BATCH_DELETE]: 39,
  [CHANGE_TRIGGERED_BY.PAINT_TYPE_CREATE]: 40,
  [CHANGE_TRIGGERED_BY.PAINT_TYPE_UPDATE]: 41,
  [CHANGE_TRIGGERED_BY.PAINT_TYPE_DELETE]: 42,
  [CHANGE_TRIGGERED_BY.PAINT_TYPE_BATCH_CREATE]: 43,
  [CHANGE_TRIGGERED_BY.PAINT_TYPE_BATCH_UPDATE]: 44,
  [CHANGE_TRIGGERED_BY.PAINT_TYPE_BATCH_DELETE]: 45,
  [CHANGE_TRIGGERED_BY.PAINT_GROUND_CREATE]: 46,
  [CHANGE_TRIGGERED_BY.PAINT_GROUND_UPDATE]: 47,
  [CHANGE_TRIGGERED_BY.PAINT_GROUND_DELETE]: 48,
  [CHANGE_TRIGGERED_BY.PAINT_GROUND_BATCH_CREATE]: 49,
  [CHANGE_TRIGGERED_BY.PAINT_GROUND_BATCH_UPDATE]: 50,
  [CHANGE_TRIGGERED_BY.PAINT_GROUND_BATCH_DELETE]: 51,
  [CHANGE_TRIGGERED_BY.ORDER_UPDATE]: 52,
  [CHANGE_TRIGGERED_BY.ORDER_CREATE]: 53,
  [CHANGE_TRIGGERED_BY.ORDER_STATUS_CHANGE]: 54,
  [CHANGE_TRIGGERED_BY.ORDER_CANCEL]: 55,
  [CHANGE_TRIGGERED_BY.ORDER_ITEM_UPDATE]: 56,
  [CHANGE_TRIGGERED_BY.ORDER_ITEM_RECEIVED]: 57,
  [CHANGE_TRIGGERED_BY.ORDER_ITEM_SYNC]: 58,
  [CHANGE_TRIGGERED_BY.EXTERNAL_WITHDRAWAL_SYNC]: 59,
  [CHANGE_TRIGGERED_BY.SCHEDULE]: 60,
  [CHANGE_TRIGGERED_BY.ACTIVITY_CREATE]: 61,
  [CHANGE_TRIGGERED_BY.ACTIVITY_UPDATE]: 62,
  [CHANGE_TRIGGERED_BY.ACTIVITY_DELETE]: 63,
  [CHANGE_TRIGGERED_BY.PPE_DELIVERY]: 64,
  [CHANGE_TRIGGERED_BY.ACTIVITY_SYNC]: 65,
  [CHANGE_TRIGGERED_BY.INVENTORY_ADJUSTMENT]: 66,
  [CHANGE_TRIGGERED_BY.INVENTORY_COUNT]: 67,
  [CHANGE_TRIGGERED_BY.ITEM_MONTHLY_CONSUMPTION_UPDATE]: 68,
  [CHANGE_TRIGGERED_BY.AUTOMATIC_MIN_MAX_UPDATE]: 69,
  [CHANGE_TRIGGERED_BY.SMS_VERIFICATION_CREATE]: 70,
  [CHANGE_TRIGGERED_BY.SMS_VERIFICATION_SEND]: 71,
  [CHANGE_TRIGGERED_BY.SMS_VERIFICATION_VERIFY]: 72,
  [CHANGE_TRIGGERED_BY.SMS_VERIFICATION_EXPIRE]: 73,
  [CHANGE_TRIGGERED_BY.SMS_VERIFICATION_CANCEL]: 74,
  [CHANGE_TRIGGERED_BY.EMAIL_SERVICE]: 75,
  [CHANGE_TRIGGERED_BY.VERIFICATION_CREATE]: 76,
  [CHANGE_TRIGGERED_BY.VERIFICATION_SEND]: 77,
  [CHANGE_TRIGGERED_BY.VERIFICATION_VERIFY]: 78,
  [CHANGE_TRIGGERED_BY.VERIFICATION_EXPIRE]: 79,
  [CHANGE_TRIGGERED_BY.VERIFICATION_CANCEL]: 80,
  [CHANGE_TRIGGERED_BY.VERIFICATION_RESEND]: 81,
  [CHANGE_TRIGGERED_BY.VEHICLE_MOVEMENT]: 82,
  [CHANGE_TRIGGERED_BY.PARKING_ASSIGNMENT]: 83,
  [CHANGE_TRIGGERED_BY.GARAGE_CAPACITY_CHANGE]: 84,
};

// =====================
// SMS Status Sort Orders
// =====================

export const SMS_VERIFICATION_STATUS_ORDER: Record<string, number> = {
  [SMS_VERIFICATION_STATUS.PENDING]: 1,
  [SMS_VERIFICATION_STATUS.SENT]: 2,
  [SMS_VERIFICATION_STATUS.VERIFIED]: 3,
  [SMS_VERIFICATION_STATUS.EXPIRED]: 4,
  [SMS_VERIFICATION_STATUS.FAILED]: 5,
  [SMS_VERIFICATION_STATUS.CANCELLED]: 6,
  [SMS_VERIFICATION_STATUS.RATE_LIMITED]: 7,
  [SMS_VERIFICATION_STATUS.BLOCKED]: 8,
};

export const SMS_VERIFICATION_TYPE_ORDER: Record<string, number> = {
  [SMS_VERIFICATION_TYPE.PHONE_VERIFICATION]: 1,
  [SMS_VERIFICATION_TYPE.EMAIL_VERIFICATION]: 2,
  [SMS_VERIFICATION_TYPE.PASSWORD_RESET]: 3,
  [SMS_VERIFICATION_TYPE.TWO_FACTOR_AUTH]: 4,
  [SMS_VERIFICATION_TYPE.ACCOUNT_CONFIRMATION]: 5,
};

// =====================
// Rate Limiting Sort Orders
// =====================

export const RATE_LIMIT_TYPE_ORDER: Record<string, number> = {
  [RATE_LIMIT_TYPE.PER_CODE_ATTEMPT]: 1,
  [RATE_LIMIT_TYPE.IP_VERIFICATION]: 2,
  [RATE_LIMIT_TYPE.CODE_SEND_CONTACT]: 3,
  [RATE_LIMIT_TYPE.CODE_SEND_IP]: 4,
  [RATE_LIMIT_TYPE.ACCOUNT_LOCKOUT]: 5,
  [RATE_LIMIT_TYPE.GLOBAL_RATE_LIMIT]: 6,
};

export const LOCKOUT_REASON_ORDER: Record<string, number> = {
  [LOCKOUT_REASON.EXCESSIVE_FAILED_ATTEMPTS]: 1,
  [LOCKOUT_REASON.IP_ABUSE_DETECTED]: 2,
  [LOCKOUT_REASON.PATTERN_ABUSE]: 3,
  [LOCKOUT_REASON.CAPTCHA_FAILURES]: 4,
  [LOCKOUT_REASON.SECURITY_VIOLATION]: 5,
  [LOCKOUT_REASON.MANUAL_ADMIN_LOCK]: 6,
};

export const CAPTCHA_REQUIREMENT_LEVEL_ORDER: Record<string, number> = {
  [CAPTCHA_REQUIREMENT_LEVEL.NONE]: 1,
  [CAPTCHA_REQUIREMENT_LEVEL.BASIC]: 2,
  [CAPTCHA_REQUIREMENT_LEVEL.INTERMEDIATE]: 3,
  [CAPTCHA_REQUIREMENT_LEVEL.ADVANCED]: 4,
  [CAPTCHA_REQUIREMENT_LEVEL.MAXIMUM]: 5,
};

export const VERIFICATION_ABUSE_LEVEL_ORDER: Record<string, number> = {
  [VERIFICATION_ABUSE_LEVEL.LOW]: 1,
  [VERIFICATION_ABUSE_LEVEL.MEDIUM]: 2,
  [VERIFICATION_ABUSE_LEVEL.HIGH]: 3,
  [VERIFICATION_ABUSE_LEVEL.CRITICAL]: 4,
  [VERIFICATION_ABUSE_LEVEL.SEVERE]: 5,
};

export const PROGRESSIVE_DELAY_TIER_ORDER: Record<string, number> = {
  [PROGRESSIVE_DELAY_TIER.TIER_1]: 1,
  [PROGRESSIVE_DELAY_TIER.TIER_2]: 2,
  [PROGRESSIVE_DELAY_TIER.TIER_3]: 3,
  [PROGRESSIVE_DELAY_TIER.TIER_4]: 4,
  [PROGRESSIVE_DELAY_TIER.TIER_5]: 5,
  [PROGRESSIVE_DELAY_TIER.TIER_6]: 6,
  [PROGRESSIVE_DELAY_TIER.TIER_7]: 7,
  [PROGRESSIVE_DELAY_TIER.TIER_8]: 8,
};

export const VERIFICATION_SECURITY_ACTION_ORDER: Record<string, number> = {
  [VERIFICATION_SECURITY_ACTION.LOG_ATTEMPT]: 1,
  [VERIFICATION_SECURITY_ACTION.DELAY_RESPONSE]: 2,
  [VERIFICATION_SECURITY_ACTION.REQUIRE_CAPTCHA]: 3,
  [VERIFICATION_SECURITY_ACTION.TEMPORARY_BLOCK]: 4,
  [VERIFICATION_SECURITY_ACTION.ESCALATE_SECURITY]: 5,
  [VERIFICATION_SECURITY_ACTION.NOTIFY_ADMIN]: 6,
  [VERIFICATION_SECURITY_ACTION.PERMANENT_BLOCK]: 7,
};

// =====================
// Email Status Sort Orders
// =====================

export const EMAIL_TYPE_ORDER: Record<string, number> = {
  [EMAIL_TYPE.ACCOUNT_VERIFICATION]: 1,
  [EMAIL_TYPE.WELCOME]: 2,
  [EMAIL_TYPE.PASSWORD_RESET]: 3,
  [EMAIL_TYPE.TEMPORARY_PASSWORD]: 4,
  [EMAIL_TYPE.PASSWORD_CHANGED]: 5,
  [EMAIL_TYPE.ACCOUNT_STATUS_CHANGE]: 6,
  [EMAIL_TYPE.NOTIFICATION]: 7,
};

export const EMAIL_STATUS_ORDER: Record<string, number> = {
  [EMAIL_STATUS.PENDING]: 1,
  [EMAIL_STATUS.SENT]: 2,
  [EMAIL_STATUS.DELIVERED]: 3,
  [EMAIL_STATUS.FAILED]: 4,
  [EMAIL_STATUS.BOUNCED]: 5,
  [EMAIL_STATUS.CANCELLED]: 6,
};

// =====================
// Unified Verification Status Sort Orders
// =====================

export const VERIFICATION_STATUS_ORDER: Record<string, number> = {
  [VERIFICATION_STATUS.PENDING]: 1,
  [VERIFICATION_STATUS.SENT]: 2,
  [VERIFICATION_STATUS.VERIFIED]: 3,
  [VERIFICATION_STATUS.EXPIRED]: 4,
  [VERIFICATION_STATUS.FAILED]: 5,
  [VERIFICATION_STATUS.CANCELLED]: 6,
};

export const VERIFICATION_METHOD_ORDER: Record<string, number> = {
  [VERIFICATION_METHOD.EMAIL]: 1,
  [VERIFICATION_METHOD.PHONE]: 2,
  [VERIFICATION_METHOD.EMAIL_AND_PHONE]: 3,
};

export const VERIFICATION_PURPOSE_ORDER: Record<string, number> = {
  [VERIFICATION_PURPOSE.ACCOUNT_VERIFICATION]: 1,
  [VERIFICATION_PURPOSE.EMAIL_VERIFICATION]: 2,
  [VERIFICATION_PURPOSE.PHONE_VERIFICATION]: 3,
  [VERIFICATION_PURPOSE.LOGIN_VERIFICATION]: 4,
  [VERIFICATION_PURPOSE.TWO_FACTOR_AUTH]: 5,
  [VERIFICATION_PURPOSE.PASSWORD_RESET]: 6,
};

// =====================
// Driver Management Sort Orders
// =====================

export const DRIVER_STATUS_ORDER: Record<string, number> = {
  [DRIVER_STATUS.ACTIVE]: 1,
  [DRIVER_STATUS.SUSPENDED]: 2,
  [DRIVER_STATUS.LICENSE_EXPIRED]: 3,
  [DRIVER_STATUS.INACTIVE]: 4,
};

export const CNH_CATEGORY_ORDER: Record<string, number> = {
  [CNH_CATEGORY.A]: 1,
  [CNH_CATEGORY.B]: 2,
  [CNH_CATEGORY.AB]: 3,
  [CNH_CATEGORY.C]: 4,
  [CNH_CATEGORY.AC]: 5,
  [CNH_CATEGORY.D]: 6,
  [CNH_CATEGORY.AD]: 7,
  [CNH_CATEGORY.E]: 8,
  [CNH_CATEGORY.AE]: 9,
};

export const LICENSE_TYPE_ORDER: Record<string, number> = {
  [LICENSE_TYPE.DEFINITIVE]: 1,
  [LICENSE_TYPE.PROVISIONAL]: 2,
  [LICENSE_TYPE.INTERNATIONAL]: 3,
};

export const BLOOD_TYPE_ORDER: Record<string, number> = {
  [BLOOD_TYPE.O_POSITIVE]: 1,
  [BLOOD_TYPE.O_NEGATIVE]: 2,
  [BLOOD_TYPE.A_POSITIVE]: 3,
  [BLOOD_TYPE.A_NEGATIVE]: 4,
  [BLOOD_TYPE.B_POSITIVE]: 5,
  [BLOOD_TYPE.B_NEGATIVE]: 6,
  [BLOOD_TYPE.AB_POSITIVE]: 7,
  [BLOOD_TYPE.AB_NEGATIVE]: 8,
};

export const BONUS_STATUS_ORDER: Record<string, number> = {
  [BONUS_STATUS.DRAFT]: 1,
  [BONUS_STATUS.CONFIRMED]: 2,
};

export const DISCOUNT_TYPE_ORDER: Record<string, number> = {
  [DISCOUNT_TYPE.PERCENTAGE]: 1,
  [DISCOUNT_TYPE.FIXED_VALUE]: 2,
};

export const PAYROLL_STATUS_ORDER: Record<string, number> = {
  [PAYROLL_STATUS.DRAFT]: 1,
  [PAYROLL_STATUS.FINALIZED]: 2,
};

// =====================
// Statistics Order Maps
// =====================

export const STATISTICS_GROUP_BY_ORDER: Record<string, number> = {
  [STATISTICS_GROUP_BY.DATE]: 1,
  [STATISTICS_GROUP_BY.SECTOR]: 2,
  [STATISTICS_GROUP_BY.USER]: 3,
  [STATISTICS_GROUP_BY.CATEGORY]: 4,
  [STATISTICS_GROUP_BY.BRAND]: 5,
  [STATISTICS_GROUP_BY.SUPPLIER]: 6,
  [STATISTICS_GROUP_BY.ITEM]: 7,
  [STATISTICS_GROUP_BY.ACTIVITY_REASON]: 8,
  [STATISTICS_GROUP_BY.ACTIVITY_OPERATION]: 9,
};

export const STATISTICS_METRIC_ORDER: Record<string, number> = {
  [STATISTICS_METRIC.COUNT]: 1,
  [STATISTICS_METRIC.QUANTITY]: 2,
  [STATISTICS_METRIC.FREQUENCY]: 3,
  [STATISTICS_METRIC.UNIT_PRICE]: 4,
  [STATISTICS_METRIC.TOTAL_PRICE]: 5,
  [STATISTICS_METRIC.PERCENTAGE]: 6,
  [STATISTICS_METRIC.AVERAGE]: 7,
  [STATISTICS_METRIC.SUM]: 8,
  [STATISTICS_METRIC.MIN]: 9,
  [STATISTICS_METRIC.MAX]: 10,
};

export const STATISTICS_PERIOD_ORDER: Record<string, number> = {
  [STATISTICS_PERIOD.DAILY]: 1,
  [STATISTICS_PERIOD.WEEKLY]: 2,
  [STATISTICS_PERIOD.MONTHLY]: 3,
  [STATISTICS_PERIOD.QUARTERLY]: 4,
  [STATISTICS_PERIOD.YEARLY]: 5,
  [STATISTICS_PERIOD.THIS_WEEK]: 6,
  [STATISTICS_PERIOD.THIS_MONTH]: 7,
  [STATISTICS_PERIOD.THIS_QUARTER]: 8,
  [STATISTICS_PERIOD.THIS_YEAR]: 9,
  [STATISTICS_PERIOD.LAST_7_DAYS]: 10,
  [STATISTICS_PERIOD.LAST_30_DAYS]: 11,
  [STATISTICS_PERIOD.LAST_90_DAYS]: 12,
  [STATISTICS_PERIOD.LAST_YEAR]: 13,
  [STATISTICS_PERIOD.CUSTOM]: 14,
};

