import { NFSE_ISSUER } from "@/config/company";

/**
 * Faithful pre-emission preview of the NFS-e (Nota Fiscal de Serviços
 * eletrônica) that the Elotech OXY integration emits via the Prefeitura de
 * Ibiporã. The layout mirrors the real authorized DANFS-e block-for-block:
 * cabeçalho da prefeitura → prestador → tomador → definição → discriminação →
 * itens → tributos → totalização.
 *
 * Fields the prefeitura only assigns AFTER emission (número da NFS-e, código de
 * verificação, chave de acesso, ID DPS) render as "a ser atribuído". All money
 * and party values are the exact ones that will be sent in the emission payload.
 */
export interface NfsePreviewItem {
  descricao: string;
  quantidade: number;
  valor: number;
  desconto: number;
  descontoCondicionado: number;
  valorServico: number;
  valorLiquido: number;
}

export interface NfsePreviewData {
  /** Predicted NFS-e number (last emitted + 1). Undefined → "a ser atribuído". */
  numeroNfse?: string;
  tomador: {
    razao: string;
    cnpjCpf: string;
    isJuridica: boolean;
    inscricaoMunicipal?: string;
    inscricaoEstadual?: string;
    endereco: string;
    municipioUf: string;
    cep: string;
    telefone: string;
    email: string;
  };
  competencia: string;
  discriminacao: string;
  itens: NfsePreviewItem[];
  totalServicos: number;
  totalDescontos: number;
  totalDeducoes: number;
  baseCalculoIss: number;
  valorIss: number;
  valorLiquido: number;
}

const money = (v: number) =>
  new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(v || 0);
const qty = (v: number) =>
  new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 5, maximumFractionDigits: 5 }).format(v || 0);
const pct = (v: number) =>
  new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 5, maximumFractionDigits: 5 }).format(v || 0);

const C = {
  ink: "#111",
  line: "#555",
  tab: "#cdd0f2",
  tabInk: "#26264a",
  muted: "#9aa0a6",
};

const box: React.CSSProperties = { border: `1px solid ${C.line}`, boxSizing: "border-box" };
const lbl: React.CSSProperties = { fontSize: 7.5, color: "#444", lineHeight: 1.1 };
const val: React.CSSProperties = { fontSize: 9.5, color: C.ink, lineHeight: 1.2 };

function SectionTab({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={{
        display: "inline-block",
        background: C.tab,
        color: C.tabInk,
        fontSize: 9,
        fontWeight: 700,
        letterSpacing: 0.2,
        padding: "2px 14px",
        borderRadius: 6,
        marginBottom: -1,
        marginLeft: 2,
        position: "relative",
        zIndex: 1,
      }}
    >
      {children}
    </div>
  );
}

function Field({
  label,
  value,
  flex = 1,
  borderLeft = false,
}: {
  label: string;
  value: React.ReactNode;
  flex?: number;
  borderLeft?: boolean;
}) {
  return (
    <div
      style={{
        flex,
        padding: "3px 6px",
        borderLeft: borderLeft ? `1px solid ${C.line}` : undefined,
        minWidth: 0,
      }}
    >
      <div style={lbl}>{label}</div>
      <div style={{ ...val, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
        {value || " "}
      </div>
    </div>
  );
}

/** Faux QR placeholder — the real QR is generated by the prefeitura on emission. */
function FauxQR({ size = 58 }: { size?: number }) {
  return (
    <div
      title="QR code gerado pela prefeitura após a emissão"
      style={{
        width: size,
        height: size,
        background:
          "conic-gradient(#000 25%, #fff 0 50%, #000 0 75%, #fff 0) 0 0 / 8px 8px",
        opacity: 0.18,
        border: "3px solid #000",
        boxSizing: "border-box",
      }}
    />
  );
}

function Watermark() {
  return (
    <div
      style={{
        position: "absolute",
        inset: 0,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        pointerEvents: "none",
        zIndex: 0,
        overflow: "hidden",
      }}
    >
      <span
        style={{
          transform: "rotate(-22deg)",
          fontSize: 80,
          fontWeight: 800,
          color: "rgba(120,120,140,0.06)",
          whiteSpace: "nowrap",
          letterSpacing: 6,
        }}
      >
        PRÉVIA · NÃO EMITIDA
      </span>
    </div>
  );
}

export function NfsePreview({ data }: { data: NfsePreviewData }) {
  const P = NFSE_ISSUER.prestador;
  const t = data.tomador;

  return (
    <div
      style={{
        position: "relative",
        background: "#fff",
        color: C.ink,
        fontFamily: "Arial, Helvetica, sans-serif",
        width: 760,
        padding: 14,
        border: `1px solid ${C.line}`,
      }}
    >
      <Watermark />
      <div style={{ position: "relative", zIndex: 1 }}>
      {/* ── Cabeçalho ───────────────────────────────────────────── */}
      <div style={{ display: "flex", alignItems: "stretch", gap: 8 }}>
        {/* Brasão placeholder */}
        <div
          style={{
            width: 64,
            height: 70,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            border: `1px solid ${C.line}`,
            color: C.muted,
            fontSize: 7,
            textAlign: "center",
            padding: 2,
          }}
        >
          BRASÃO
          <br />
          PREFEITURA
        </div>

        {/* Títulos prefeitura */}
        <div style={{ flex: 1, paddingTop: 2 }}>
          <div style={{ fontSize: 12, fontWeight: 700 }}>{NFSE_ISSUER.municipio}</div>
          <div style={{ fontSize: 10, fontWeight: 600 }}>{NFSE_ISSUER.secretaria}</div>
          <div style={{ fontSize: 8, color: "#444", marginTop: 2 }}>{NFSE_ISSUER.municipioEndereco}</div>
          <div style={{ display: "flex", ...box, marginTop: 6 }}>
            <Field label="Nº do RPS:" value="-" />
            <Field label="Série do RPS:" value="-" borderLeft />
            <Field label="Tipo do RPS:" value="-" borderLeft />
            <Field label="Emissão RPS:" value="-" borderLeft />
          </div>
        </div>

        {/* Caixa NFS-e + QR */}
        <div style={{ display: "flex", gap: 6 }}>
          <div style={{ width: 150, ...box }}>
            <div style={{ padding: "3px 6px", fontSize: 8.5, fontWeight: 700, borderBottom: `1px solid ${C.line}` }}>
              Nota Fiscal de Serviços Eletrônica
            </div>
            <div style={{ padding: "3px 6px", borderBottom: `1px solid ${C.line}` }}>
              <div style={lbl}>Número:</div>
              <div style={{ ...val, fontWeight: 700 }}>
                {data.numeroNfse ? (
                  <>
                    {data.numeroNfse} <span style={{ fontSize: 7, fontWeight: 400, color: C.muted }}>(previsto)</span>
                  </>
                ) : (
                  "a ser atribuído"
                )}
              </div>
            </div>
            <div style={{ padding: "3px 6px", borderBottom: `1px solid ${C.line}` }}>
              <div style={lbl}>Data Prestação:</div>
              <div style={val}>{new Date().toLocaleDateString("pt-BR")}</div>
            </div>
            <div style={{ padding: "3px 6px" }}>
              <div style={lbl}>Autenticidade:</div>
              <div style={{ ...val, color: C.muted }}>a ser atribuído</div>
            </div>
          </div>
          <FauxQR />
        </div>
      </div>

      {/* SITE / ID DPS / Chave (gerados na emissão) */}
      <div style={{ marginTop: 6, fontSize: 7.5, color: "#333" }}>
        SITE AUTENTICIDADE: {NFSE_ISSUER.siteAutenticidade}
      </div>
      <div style={{ display: "flex", ...box, marginTop: 4, background: "#f4f4f8" }}>
        <Field label="ID DPS:" value={<span style={{ color: C.muted }}>gerado na emissão</span>} flex={1} />
        <Field label="Chave Acesso:" value={<span style={{ color: C.muted }}>gerada na emissão</span>} flex={1} borderLeft />
      </div>

      {/* ── Prestador ───────────────────────────────────────────── */}
      <div style={{ marginTop: 8 }}>
        <SectionTab>DADOS DO PRESTADOR DO SERVIÇO</SectionTab>
        <div style={{ display: "flex", ...box }}>
          <div
            style={{
              width: 64,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              borderRight: `1px solid ${C.line}`,
              padding: 4,
            }}
          >
            <img src="/logo.png" alt="logo" style={{ maxWidth: 52, maxHeight: 52, objectFit: "contain" }} />
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ display: "flex", borderBottom: `1px solid ${C.line}` }}>
              <Field label="Insc. Municipal:" value={P.inscricaoMunicipal} flex={0.8} />
              <Field label="CNPJ/CPF:" value={P.cnpj} flex={1.4} borderLeft />
              <Field label="Regime Fiscal:" value={P.regimeFiscal} flex={1.2} borderLeft />
            </div>
            <div style={{ display: "flex", borderBottom: `1px solid ${C.line}` }}>
              <Field label="Nome/Razão Social:" value={P.razaoSocial} flex={2.4} />
              <Field label="Nome Fantasia:" value={P.fantasia} flex={1} borderLeft />
            </div>
            <div style={{ display: "flex", borderBottom: `1px solid ${C.line}` }}>
              <Field label="Endereço:" value={P.endereco} flex={2.4} />
              <Field label="Insc. Estadual:" value="" flex={1} borderLeft />
            </div>
            <div style={{ display: "flex" }}>
              <Field label="Município/UF:" value={P.municipioUf} flex={1} />
              <Field label="CEP:" value={P.cep} flex={0.7} borderLeft />
              <Field label="Fone/Fax:" value={P.telefone} flex={1} borderLeft />
              <Field label="E-Mail:" value={P.email} flex={1.3} borderLeft />
            </div>
          </div>
        </div>
      </div>

      {/* ── Tomador ─────────────────────────────────────────────── */}
      <div style={{ marginTop: 8 }}>
        <SectionTab>DADOS DO TOMADOR DO SERVIÇO</SectionTab>
        <div style={box}>
          <div style={{ display: "flex", borderBottom: `1px solid ${C.line}` }}>
            <Field label="Insc. Municipal:" value={t.inscricaoMunicipal || ""} flex={0.8} />
            <Field label="CNPJ/CPF:" value={t.cnpjCpf} flex={1.4} borderLeft />
            <Field label="Insc. Estadual:" value={t.inscricaoEstadual || ""} flex={1.2} borderLeft />
          </div>
          <div style={{ display: "flex", borderBottom: `1px solid ${C.line}` }}>
            <Field label="Nome/Razão Social:" value={t.razao} flex={1} />
          </div>
          <div style={{ display: "flex", borderBottom: `1px solid ${C.line}` }}>
            <Field label="Endereço:" value={t.endereco} flex={2.4} />
            <Field label="CEP:" value={t.cep} flex={0.7} borderLeft />
          </div>
          <div style={{ display: "flex" }}>
            <Field label="Município/UF:" value={t.municipioUf} flex={1} />
            <Field label="Fone/Fax:" value={t.telefone} flex={1} borderLeft />
            <Field label="E-Mail:" value={t.email} flex={1.4} borderLeft />
          </div>
        </div>
      </div>

      {/* ── Definição do serviço ────────────────────────────────── */}
      <div style={{ marginTop: 8 }}>
        <SectionTab>DEFINIÇÃO DO SERVIÇO</SectionTab>
        <div style={box}>
          <div style={{ display: "flex", borderBottom: `1px solid ${C.line}` }}>
            <div style={{ flex: 1, padding: "3px 6px" }}>
              <div style={lbl}>Item da Lista de Serviços da LC nº 116/03:</div>
              <div style={{ ...val, marginTop: 2 }}>{NFSE_ISSUER.itemListaServico}</div>
            </div>
            <Field label="CNAE:" value={NFSE_ISSUER.cnae} flex={0.35} borderLeft />
          </div>
          <div style={{ display: "flex" }}>
            <Field label="Competência:" value={data.competencia} />
            <Field label="Local da Prestação do Serviço:" value={NFSE_ISSUER.localPrestacao} borderLeft />
            <Field label="Situação da NFS-e:" value="PRÉVIA" borderLeft />
            <Field label="Natureza da Operação:" value={NFSE_ISSUER.naturezaOperacao} borderLeft />
          </div>
        </div>
      </div>

      {/* ── Discriminação ───────────────────────────────────────── */}
      <div style={{ marginTop: 8 }}>
        <SectionTab>DISCRIMINAÇÃO DO SERVIÇO</SectionTab>
        <div style={{ ...box, padding: "5px 6px", minHeight: 56, fontSize: 9, whiteSpace: "pre-wrap", lineHeight: 1.35 }}>
          {data.discriminacao || " "}
        </div>
      </div>

      {/* ── Itens ───────────────────────────────────────────────── */}
      <div style={{ marginTop: 8 }}>
        <SectionTab>ITENS DO SERVIÇO</SectionTab>
        <table style={{ ...box, width: "100%", borderCollapse: "collapse", fontSize: 8.5 }}>
          <thead>
            <tr style={{ background: "#f4f4f8" }}>
              {["Tributável", "Descrição do Item", "Quantidade", "Valor", "Desc.", "Desc. Cond.", "Valor Serviço", "Valor Líquido"].map(
                (h, i) => (
                  <th
                    key={h}
                    style={{
                      border: `1px solid ${C.line}`,
                      padding: "3px 5px",
                      textAlign: i === 1 ? "left" : i === 0 ? "center" : "right",
                      fontWeight: 600,
                      whiteSpace: "nowrap",
                    }}
                  >
                    {h}
                  </th>
                ),
              )}
            </tr>
          </thead>
          <tbody>
            {data.itens.map((it, i) => (
              <tr key={i}>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px", textAlign: "center" }}>SIM</td>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px" }}>{it.descricao}</td>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px", textAlign: "right" }}>{qty(it.quantidade)}</td>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px", textAlign: "right" }}>{money(it.valor)}</td>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px", textAlign: "right" }}>{money(it.desconto)}</td>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px", textAlign: "right" }}>{money(it.descontoCondicionado)}</td>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px", textAlign: "right" }}>{money(it.valorServico)}</td>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px", textAlign: "right" }}>{money(it.valorLiquido)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ── Tributos incidentes ─────────────────────────────────── */}
      <div style={{ marginTop: 8 }}>
        <SectionTab>TRIBUTOS INCIDENTES</SectionTab>
        <table style={{ ...box, width: "100%", borderCollapse: "collapse", fontSize: 8.5 }}>
          <thead>
            <tr style={{ background: "#f4f4f8" }}>
              {["Tributo", "Alíquota", "Valor", "Retido"].map((h, i) => (
                <th
                  key={h}
                  style={{
                    border: `1px solid ${C.line}`,
                    padding: "3px 5px",
                    textAlign: i === 0 ? "left" : i === 3 ? "center" : "right",
                    fontWeight: 600,
                  }}
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {[
              { nome: "ISSQN", aliquota: NFSE_ISSUER.issAliquota, valor: data.valorIss },
              { nome: "PIS", aliquota: 0, valor: 0 },
              { nome: "COFINS", aliquota: 0, valor: 0 },
              { nome: "INSS", aliquota: 0, valor: 0 },
              { nome: "IR", aliquota: 0, valor: 0 },
              { nome: "CSLL", aliquota: 0, valor: 0 },
              { nome: "Impostos Federais", aliquota: 0, valor: 0 },
              { nome: "Outras Retenções", aliquota: null, valor: 0 },
            ].map((tr) => (
              <tr key={tr.nome}>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px" }}>{tr.nome}</td>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px", textAlign: "right" }}>
                  {tr.aliquota === null ? "" : pct(tr.aliquota)}
                </td>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px", textAlign: "right" }}>{pct(tr.valor)}</td>
                <td style={{ border: `1px solid ${C.line}`, padding: "3px 5px", textAlign: "center" }}>Não</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ── Totalização ─────────────────────────────────────────── */}
      <div style={{ marginTop: 8 }}>
        <SectionTab>TOTALIZAÇÃO DO DOCUMENTO FISCAL</SectionTab>
        <div style={{ display: "flex", ...box }}>
          <Field label="Base de Cálculo do ISSQN:" value={money(data.baseCalculoIss)} />
          <Field label="Valor Total Descontos:" value={money(data.totalDescontos)} borderLeft />
          <Field label="Valor Total das Deduções:" value={money(data.totalDeducoes)} borderLeft />
          <Field label="Valor Total dos Serviços:" value={money(data.totalServicos)} borderLeft />
          <Field
            label="Valor Líquido da NFS-e:"
            value={<span style={{ fontWeight: 700 }}>{money(data.valorLiquido)}</span>}
            borderLeft
          />
        </div>
      </div>

      {/* ── Rodapé ──────────────────────────────────────────────── */}
      <div style={{ display: "flex", ...box, marginTop: 8 }}>
        <div style={{ padding: "4px 6px", borderRight: `1px solid ${C.line}` }}>
          <div style={lbl}>NFS-e Nº</div>
          <div style={{ ...val, fontWeight: 700 }}>{data.numeroNfse || "—"}</div>
        </div>
        <div style={{ flex: 1, padding: "4px 6px", fontSize: 8 }}>
          Recebemos de {NFSE_ISSUER.prestador.razaoSocial}, os serviços constantes neste documento fiscal eletrônico.
          <div style={{ marginTop: 6, color: "#555" }}>DATA: ____/____/______ &nbsp;&nbsp; Assinatura: ____________________________</div>
        </div>
      </div>
      </div>
    </div>
  );
}
