import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { useTaskMutations } from "../../../../hooks";
import { TASK_STATUS } from "../../../../constants";
import { IconLoader2 } from "@tabler/icons-react";
import type { Task } from "../../../../types";

// Schema for duplicate form
const duplicateSchema = z.object({
  serialNumber: z
    .string()
    .nullable()
    .optional()
    .transform((val) => val?.trim().toUpperCase() || null),
  plate: z
    .string()
    .nullable()
    .optional()
    .transform((val) => val?.trim().toUpperCase() || null),
  chassisNumber: z
    .string()
    .nullable()
    .optional()
    .transform((val) => val?.trim().replace(/\s/g, "").toUpperCase() || null),
});

type DuplicateFormData = z.infer<typeof duplicateSchema>;

interface TaskDuplicateModalProps {
  task: Task | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess?: () => void;
}

export const TaskDuplicateModal = ({ task, open, onOpenChange, onSuccess }: TaskDuplicateModalProps) => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { createAsync } = useTaskMutations();

  const form = useForm<DuplicateFormData>({
    resolver: zodResolver(duplicateSchema),
    defaultValues: {
      serialNumber: "",
      plate: "",
      chassisNumber: "",
    },
  });

  // Reset form when task changes
  const handleOpenChange = (newOpen: boolean) => {
    if (newOpen && task) {
      form.reset({
        serialNumber: "",
        plate: "",
        chassisNumber: "",
      });
    }
    onOpenChange(newOpen);
  };

  const handleSubmit = async (data: DuplicateFormData) => {
    if (!task) return;

    try {
      setIsSubmitting(true);

      // Create new task with all the same data except:
      // - New serial number, plate and chassis from form
      // - Reset status to PENDING
      // - Reset dates
      // - New ID (generated by API)
      const newTaskData = {
        // Basic fields
        name: task.name,
        status: TASK_STATUS.PENDING,
        // Sanitize serialNumber - remove invalid characters, keep only A-Z, 0-9, and -
        serialNumber: (data.serialNumber || String(task.serialNumber || "")).replace(/[^A-Z0-9-]/gi, "").toUpperCase(),
        details: task.details,
        entryDate: task.entryDate,
        term: task.term,
        startedAt: null, // Reset
        finishedAt: null, // Reset
        paintId: task.paintId,
        customerId: task.customerId,
        sectorId: task.sectorId,
        commission: task.commission, // Required field
        budgetId: task.budgetId,
        nfeId: task.nfeId,
        receiptId: task.receiptId,

        // Relations - copy artwork and paint IDs
        artworkIds: task.artworks?.map((file) => file.id),
        paintIds: task.logoPaints?.map((paint) => paint.id),

        // Complex relations - copy nested data
        observation: task.observation
          ? {
              description: task.observation.description,
              artworkIds: task.observation.artworks?.map((file) => file.id) || [],
            }
          : null,

        services: task.services?.map((service) => ({
          status: service.status,
          statusOrder: service.statusOrder,
          description: service.description,
          startedAt: null, // Reset service dates
          finishedAt: null,
        })),

        // Truck with new plate and chassis from form
        truck: {
          plate: data.plate || task.truck?.plate || null,
          chassisNumber: data.chassisNumber || task.truck?.chassisNumber || null,
          model: task.truck?.model || "",
          manufacturer: task.truck?.manufacturer || "OTHER",
          xPosition: null,
          yPosition: null,
        },

        // Note: cuts are not duplicated as they are separate records
        // The new task will need new cut entries if required
        cut: null,

        // Note: airbrushings are not duplicated as they are separate records
        // The new task will need new airbrushing entries if required
      };

      const result = await createAsync(newTaskData);

      if (result.success) {
        handleOpenChange(false);
        onSuccess?.();
      }
    } catch (error) {
      console.error("Error duplicating task:", error);
      // Error is handled by the mutation hook
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!task) return null;

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Duplicar Tarefa</DialogTitle>
          <DialogDescription>Criando uma cópia de "{task.name}". Informe o número de série, placa e chassi para a nova tarefa.</DialogDescription>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-4">
            {/* Serial Number */}
            <FormField
              control={form.control}
              name="serialNumber"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Número de Série</FormLabel>
                  <FormControl>
                    <Input
                      {...field}
                      placeholder="Ex: ABC-12345"
                      className="uppercase"
                      onChange={(e) => field.onChange(e.target.value.toUpperCase())}
                      disabled={isSubmitting}
                      autoFocus
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Plate */}
            <FormField
              control={form.control}
              name="plate"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Placa</FormLabel>
                  <FormControl>
                    <Input
                      {...field}
                      value={field.value || ""}
                      placeholder="Ex: ABC1D23"
                      className="uppercase"
                      onChange={(e) => field.onChange(e.target.value.toUpperCase())}
                      disabled={isSubmitting}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Chassis Number */}
            <FormField
              control={form.control}
              name="chassisNumber"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Número do Chassi</FormLabel>
                  <FormControl>
                    <Input
                      {...field}
                      value={field.value || ""}
                      placeholder="Ex: 9BWZZZ377VT004251"
                      className="uppercase"
                      onChange={(e) => field.onChange(e.target.value.toUpperCase())}
                      disabled={isSubmitting}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => handleOpenChange(false)} disabled={isSubmitting}>
                Cancelar
              </Button>
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting && <IconLoader2 className="mr-2 h-4 w-4 animate-spin" />}
                Duplicar Tarefa
              </Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
};
