// packages/interfaces/src/index.ts

// Export common types
export * from "./common";

// Export entity interfaces
export * from "./activity";
export * from "./airbrushing";
export * from "./borrow";
export * from "./changelog";
export * from "./customer";
export * from "./cut";
export * from "./ppe";
export * from "./externalWithdrawal";
export * from "./file";
export * from "./garage";
export * from "./holiday";
export * from "./item";
export * from "./maintenance";
export * from "./measure";
export * from "./notification";
export * from "./observation";
export * from "./order";
export * from "./paint";
export * from "./paint-brand";
export * from "./position";
export * from "./preferences";
export * from "./warning";
export * from "./sector";
export * from "./service";
export * from "./serviceOrder";
export * from "./summary";
export * from "./supplier";
export * from "./task";
export * from "./timeClockEntry";
export * from "./truck";
export * from "./layout";
export * from "./layoutSection";
export * from "./user";
export * from "./vacation";
export * from "./dashboard";
export * from "./auth";
export * from "./bonus";
export * from "./bonusDiscount";
export * from "./payroll";
export * from "./payrollDetails";
export * from "./sms";
export * from "./verification";
export * from "./monitoring";
export * from "./statistics";
export * from "./deployment";
