/**
 * Order code shown as the title of the order PDFs: e.g. `Pedido 0001-01.1 - Bases`.
 *
 *   Pedido  — hardcoded
 *   0001    — order.orderNumber, 4-digit zero-padded (incremental, starts at 0001)
 *   01      — order.supplier.sequentialNumber, 2-digit zero-padded (Nth supplier by createdAt)
 *   .1 / .2 — order type: automatic (created by an order schedule) = 1, manual = 2
 *   Bases   — the order's single item category; "Variados" when items span >1 category
 *
 * Accepts a loose structural shape so it works both for a persisted order and for the
 * not-yet-saved create/edit form data (where orderNumber may be absent → "0000").
 */
export interface OrderCodeInput {
  orderNumber?: number | null;
  /** Present when the order was generated by an order schedule → marks it automatic. */
  orderScheduleId?: string | null;
  supplier?: { sequentialNumber?: number | null } | null;
  items?: Array<{ item?: { category?: { name?: string | null } | null } | null } | null> | null;
}

export function formatOrderNumber(n?: number | null): string {
  if (n === null || n === undefined) return "0000";
  return String(n).padStart(4, "0");
}

export function formatSupplierNumber(n?: number | null): string {
  if (n === null || n === undefined) return "00";
  return String(n).padStart(2, "0");
}

/** Distinct category names across an order's real (non-temporary) items. */
export function getOrderCategoryLabel(order: OrderCodeInput): string | null {
  const names = new Set<string>();
  for (const orderItem of order?.items ?? []) {
    const name = orderItem?.item?.category?.name;
    if (name) names.add(name);
  }
  if (names.size === 0) return null;
  if (names.size === 1) return [...names][0];
  return "Variados";
}

/** Build the full order code string used as the PDF document title. */
export function buildOrderCode(order: OrderCodeInput): string {
  const num = formatOrderNumber(order?.orderNumber);
  const supplier = formatSupplierNumber(order?.supplier?.sequentialNumber);
  const typeDigit = order?.orderScheduleId ? 1 : 2;
  const base = `Pedido ${num}-${supplier}.${typeDigit}`;
  const category = getOrderCategoryLabel(order);
  return category ? `${base} - ${category}` : base;
}
