export { BasicInfoCard } from "./basic-info-card";
export { ContactDetailsCard } from "./contact-details-card";
export { AddressInfoCard } from "./address-info-card";
export { RelatedServiceOrdersCard } from "./related-service-orders-card";
export { CustomerActivityCard } from "./customer-activity-card";
export { RelatedInvoicesCard } from "./related-invoices-card";
export { CustomerTasksTable } from "./customer-tasks-table";
export { CustomerTasksList } from "./customer-tasks-list";
export { DocumentsCard } from "./documents-card";
